src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HyojunBaika__c</fullName>
        <formula>ShohinShizaiM__r.HyojunBaika__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>標準売価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NohinKakaku__c</fullName>
        <label>販売価格</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuUriageKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>受注データを確定し売掛データへの金額は集計を行う場合ON。</description>
        <inlineHelpText>納品の確定と請求の確定をする場合にON。

例）注文書FAXを受領し契約の意思確認が取れた。
例）商品を発送し先方から受領書を受け取った。</inlineHelpText>
        <label>納品請求確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuUriageKakuteibi__c</fullName>
        <inlineHelpText>受注確定フラグONの場合に、売掛データの締期間を検索する日付。</inlineHelpText>
        <label>請求基準日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shohizeiritsu__c</fullName>
        <defaultValue>$Setup.SystemParam__c.Shohizeiritsu__c</defaultValue>
        <label>消費税率</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JuchuSuryo__c</fullName>
        <label>受注数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MeisaiJyogai__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求書の明細に表示しない場合にON。</inlineHelpText>
        <label>請求隠</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Shohizeiritsu__c</fullName>
        <defaultValue>$Setup.SystemParam__c.Shohizeiritsu__c</defaultValue>
        <label>消費税率</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TorihikisakiTanka__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>該当する取引先の該当商品資材マスターに設定された条件マスタが存在する場合に設定される。
受注データの日付（納品予定日/売上計上日）により、売掛データの期間設定が考慮され設定される。</inlineHelpText>
        <label>取引先条件</label>
        <referenceTo>AccountTankaM__c</referenceTo>
        <relationshipName>JuchuMeisaiData_TorihikisakiTanka</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KeshikomiData__c.object
<CustomObject>
    <fields>
        <fullName>KeshikomiKakuninBi__c</fullName>
        <label>消込確認日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KeshikomiKingaku__c</fullName>
        <label>消込入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>消込値引データ</relationshipLabel>
        <relationshipName>NyukinData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消込値引データ</label>
    <nameField>
        <label>消込値引名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HyojunBaika__c</fullName>
        <inlineHelpText>取引先条件マスタが存在しない場合に採用される商品の販売単価。</inlineHelpText>
        <label>標準売価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shohizeiritsu__c</fullName>
        <defaultValue>$Setup.SystemParam__c.Shohizeiritsu__c</defaultValue>
        <inlineHelpText>ここに値が入っている場合、各トランザクションデータの消費税率の初期値はこの値となる。</inlineHelpText>
        <label>消費税率</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>SeikyushoMeisaiMaxNum__c</fullName>
        <defaultValue>36</defaultValue>
        <label>請求書明細最大行数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shohizeiritsu__c</fullName>
        <defaultValue>0.08</defaultValue>
        <label>消費税率</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shohizeiritsu__c</fullName>
        <defaultValue>$Setup.SystemParam__c.Shohizeiritsu__c</defaultValue>
        <label>消費税率</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N01_SeikyushoControllerTest.cls
@isTest
private class N01_SeikyushoControllerTest {
    static testMethod void myUnitTest1() {

        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト１０２N01', AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテスト１０２N01', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        juchuList.add(new JuchuData__c(name = '受注データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, JuchuUriageKakuteiFlg__c = false, JuchuUriageKakuteiBi__c = Date.today()));
        juchuList.add(new JuchuData__c(name = '受注データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, JuchuUriageKakuteiFlg__c = false, JuchuUriageKakuteiBi__c = Date.today()));
        juchuList.add(new JuchuData__c(name = '受注データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, JuchuUriageKakuteiFlg__c = false, JuchuUriageKakuteiBi__c = Date.today()));
        juchuList.add(new JuchuData__c(name = '受注データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, JuchuUriageKakuteiFlg__c = false, JuchuUriageKakuteiBi__c = Date.today()));
        insert juchuList;
        
        // 商品資材マスタ作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN011', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN012', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN013', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN014', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN015', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN016', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN017', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN018', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN019', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN01a', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN01b', HyojunBaika__c = 1));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テストN01c', HyojunBaika__c = 1));
        insert shohinList;

        // 取引先単価マスタ
        List<AccountTankaM__c> tankMList = new List<AccountTankaM__c>();
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[0].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[1].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[2].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[3].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[4].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[5].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[6].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[7].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[8].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[9].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[10].Id));
        tankMList.add(new AccountTankaM__c(NohinKakaku__c = 123.00, Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[11].Id));
        insert tankMList;

        
        // 受注明細データ作成
        List<JuchuMeisaiData__c> meisaiList = new List<JuchuMeisaiData__c>();
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[0].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[0].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[1].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[1].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[2].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[2].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[3].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[3].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[4].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[4].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[5].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[5].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[6].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[6].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[7].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[7].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[8].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[8].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[9].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[9].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[10].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[10].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[0].Id, TorihikisakiTanka__c = tankMList[11].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[11].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[0].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[0].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[1].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[1].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[2].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[2].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[3].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[3].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[4].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[4].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[5].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[5].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[6].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[6].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[7].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[7].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[8].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[8].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[9].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[9].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[10].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[10].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[1].Id, TorihikisakiTanka__c = tankMList[11].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[11].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[0].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[0].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[1].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[1].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[2].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[2].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[3].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[3].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[4].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[4].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[5].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[5].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[6].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[6].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[7].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[7].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[8].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[8].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[9].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[9].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[10].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[10].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[2].Id, TorihikisakiTanka__c = tankMList[11].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[11].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[0].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[0].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[1].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[1].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[2].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[2].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[3].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[3].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[4].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[4].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[5].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[5].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[6].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[6].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[7].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[7].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[8].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[8].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[9].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[9].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[10].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[10].Id));
        meisaiList.add(new JuchuMeisaiData__c(name = '受注明細データテスト１０２N01', JuchuData__c = juchuList[3].Id, TorihikisakiTanka__c = tankMList[11].Id, MeisaiJyogai__c = False, JuchuSuryo__c  = 5, Shohizeiritsu__c = 0.08, ShohinShizaiM__c = shohinList[11].Id));
        
        insert meisaiList;
        
        // 消込データ作成
        List<KeshikomiData__c> keshikomiList = new List<KeshikomiData__c>();
        keshikomiList.add(new KeshikomiData__c(name = '入金データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today()));
        keshikomiList.add(new KeshikomiData__c(name = '入金データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today()));
        keshikomiList.add(new KeshikomiData__c(name = '入金データテスト１０２N01', UrikakeData__c = urikakeList[0].Id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today()));
        insert keshikomiList;

		// 受注データ　受注確定フラグTRUE
		juchuList[0].JuchuUriageKakuteiFlg__c = true;
        juchuList[1].JuchuUriageKakuteiFlg__c = true;
		juchuList[2].JuchuUriageKakuteiFlg__c = true;
		juchuList[3].JuchuUriageKakuteiFlg__c = true;
        update juchuList;

        Test.startTest();
        
        // 売掛データIDをURLに設定

        // カスタム設定取得
        SystemParam__c SysParam = SystemParam__c.getOrgDefaults();

        // 請求書明細最大行数2
        SysParam.SeikyushoMeisaiMaxNum__c = 2;
        insert SysParam;

        Test.setCurrentPage(Page.N01_Seikyusho);   
        ApexPages.currentPage().getParameters().put('UdId', urikakeList[0].Id);

        N01_SeikyushoController controller1 = new N01_SeikyushoController();
        controller1.doUpdate();

        Integer atesakiHidariChoseiMm = controller1.atesakiHidariChoseiMm;
        Integer atesakiUeChoseiMm = controller1.atesakiUeChoseiMm;
        Integer titleUeMm = controller1.titleUeMm;
        Integer titleShitaMm = controller1.titleShitaMm;

        // 請求書明細最大行数1
        SysParam.SeikyushoMeisaiMaxNum__c = 1;
        update SysParam;

        Test.setCurrentPage(Page.N01_Seikyusho);   
        ApexPages.currentPage().getParameters().put('UdId', urikakeList[0].Id);

        N01_SeikyushoController controller2 = new N01_SeikyushoController();
        controller2.doUpdate();

        // 請求書明細最大行数36
        SysParam.SeikyushoMeisaiMaxNum__c = 99;
        update SysParam;

        Test.setCurrentPage(Page.N01_Seikyusho);   
        ApexPages.currentPage().getParameters().put('UdId', urikakeList[0].Id);

        N01_SeikyushoController controller3 = new N01_SeikyushoController();
        controller3.doUpdate();

        Test.stopTest();

    }
}