src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuData__c.object
<CustomObject>
    <fields>
        <fullName>HachuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>発注確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nohinsaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納品先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Nohinsaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shiiresaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>仕入先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Shiiresaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注データ</label>
    <nameField>
        <displayFormat>発注-{0000000000}</displayFormat>
        <label>発注番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>HachuData__c</fullName>
        <label>発注データ</label>
        <referenceTo>HachuData__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_HachuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HachuKakuteiFlg__c</fullName>
        <formula>HachuData__r.HachuKakuteiFlg__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_発注確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HachuSuryoPC__c</fullName>
        <label>発注数量PC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KonyuKakaku__c</fullName>
        <inlineHelpText>空白　の　場合　商品資材マスタ　の　標準原価　となる。</inlineHelpText>
        <label>購入単価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_ShohinShizaiM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>HatchuJidoNyuko__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>発注確定時に在庫データを自動的に入庫させる場合ON。
例：発注数量と入庫数量が食い違うことのない商品資材など。</inlineHelpText>
        <label>発注自動入庫</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YukoZaikoYotei__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>予定入庫フラグONの入出庫データは確実な入庫が保証される場合OK。
最長販売期限日付に影響有り。
引当処理の検索対象に影響有り。
例）物品ではなくライセンスなどの無形商品。
例）仕入直送など入庫予定数量や入庫日を無視できる商品。</inlineHelpText>
        <label>予定入庫保証</label>
        <type>Checkbox</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HachuDataTriggerHandlerTest.cls
@isTest
private class HachuDataTriggerHandlerTest {

    static testMethod void myUnitTest1() {
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, Type= '仕入先');
        Account acc3 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, Type= '仕入先');
        insert acc1;
        insert acc3;
        
        // 納品先作成
        Account acc2 = new Account(Name = 'テスト納品先', Shimebi__c = 20, Kijitsu__c = 15, Type= '納品先');
        insert acc2;
        
        // 商品資材作成
        ShohinShizaiM__c shohin = new ShohinShizaiM__c(name = 'テスト商品1', HatchuJidoNyuko__c = true, YukoZaikoYotei__c = true);
        insert shohin;

        // 発注データ作成
        HachuData__c hachu = new HachuData__c (shiiresaki__c = acc1.Id, Nohinsaki__c = acc2.Id );
        insert hachu;
        
        // 発注明細データ作成
        HachuMeisaiData__c meisai = new HachuMeisaiData__c(HachuData__c = hachu.Id, ShohinShizaiM__c = shohin.Id, HachuSuryoPC__c = 1, KonyuKakaku__c = 123);
        insert meisai;
        update meisai;
        
        
        Test.startTest();
        
        // 発注データ更新
        hachu.HachuKakuteiFlg__c = true;
        update hachu;
                
        // 発注データ作成
        HachuData__c hachu2 = new HachuData__c (shiiresaki__c = acc1.Id, Nohinsaki__c = acc2.Id );
        insert hachu2;
        
        // 発注明細データ作成
        HachuMeisaiData__c meisai2 = new HachuMeisaiData__c(HachuData__c = hachu2.Id, ShohinShizaiM__c = shohin.Id, HachuSuryoPC__c = 1, KonyuKakaku__c = 123);
        insert meisai2;
        update meisai2;
        
        // 発注データ更新
        hachu2.HachuKakuteiFlg__c = true;
        update hachu2;
                
        // 発注データ作成
        HachuData__c hachu3 = new HachuData__c (shiiresaki__c = acc3.Id, Nohinsaki__c = acc2.Id );
        insert hachu3;
        
        // 発注明細データ作成
        HachuMeisaiData__c meisai3 = new HachuMeisaiData__c(HachuData__c = hachu3.Id, ShohinShizaiM__c = shohin.Id, HachuSuryoPC__c = 1, KonyuKakaku__c = 123);
        insert meisai3;
        update meisai3;
        
        // 発注データ更新
        hachu3.HachuKakuteiFlg__c = true;
        update hachu3;

        // 発注データ削除
        delete hachu;
        delete hachu2;
        delete hachu3;
                
        Test.stopTest();

    }
}