src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LotKonzaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>受注の在庫引当処理で複数の在庫データ（パレット/ロット）を混在させる動きを標準とする場合チェックONにする。通常OFF。（ON例：直営店）</inlineHelpText>
        <label>ロット混在フラグ</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>HikiateKanryoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>全ての商品の引当に成功した場合にON。
引当解除と再引当を行う場合は　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当成功完了</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JidoHikiateFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有りで　後ほど　システムにより　受注確定引当　を行います。

継続的に引当スタンバイ状態にする場合は　引当スタンバイ予約　も合わせて設定が必要。</inlineHelpText>
        <label>引当スタンバイ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JidoHikiateYoyaku__c</fullName>
        <inlineHelpText>引当スタンバイを特定日付移行に継続的にONとする日付。

本日付移行に引当できなかった場合は納品請求日が自動的に繰上げされる。


例）入荷し次第に納品引当する場合。
例）未入荷の商品を先行し受注登録する場合。
例）入荷し引当した日付を納品請求日とする場合。</inlineHelpText>
        <label>引当スタンバイ予約</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JuchuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>引当可能フラグON　かつ　当フラグ　ON　で在庫データの引当を試みます。
引当解除と再引当を行う場合は　引当成功完了　OFF　かつ　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当即時確定</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LotKonzaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>複数の在庫データ（パレット/ユニット）を引き当てる事を許可します。
伝票の明細に同じ賞味期限の行が複数表記される可能性があります。</inlineHelpText>
        <label>ユニット混在フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>受注確定フラグOFFの場合に、売掛データの締期間を検索する日付。

出荷引当の試行時に、入出庫データの賞味期限を検索する日付。</inlineHelpText>
        <label>納品請求日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ZaikoHikiateSaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷引当先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>JuchuData_ZaikoHikiateSaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>JuchuMeisaiSaidaiTorokusu__c</fullName>
        <defaultValue>35</defaultValue>
        <label>受注明細最大登録数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J06_ShukkoRendoBatchSchedulerTest.cls
@isTest
private class J06_ShukkoRendoBatchSchedulerTest{
    static testMethod void myUnitTest1() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
                
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テストJ06', Type = '納品先'));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテストJ06', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();

        juchuList.add(new JuchuData__c(
            name = '受注データテストJ06', 
            UrikakeData__c = urikakeList[0].Id,
            JuchuKakuteiFlg__c = FALSE,
            HikiateKanryoFlg__c = FALSE,
            JidoHikiateFlg__c = TRUE,
            ZaikoHikiateSaki__c = accList[0].Id,
            JidoHikiateYoyaku__c = Date.today().addDays(1),
            NohinYoteibi__c = Date.today().addDays(10),
            LotKonzaiFlg__c = TRUE));

        insert juchuList;

        Test.startTest();
        String jobId = System.schedule('Test J06_ShukkoRendoBatchScheduler', '0 0 * * * ?', new J06_ShukkoRendoScheduler());
        Test.stopTest();
    }
}