src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuData__c.object
<CustomObject>
    <fields>
        <fullName>Shiiresaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>仕入先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Shiiresaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注データ</label>
    <nameField>
        <displayFormat>発注-{0000000000}</displayFormat>
        <label>発注番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>HachuData__c</fullName>
        <label>発注データ</label>
        <referenceTo>HachuData__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_HachuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KaikakeData__c.object
<CustomObject>
    <fields>
        <fullName>Shiiresaki__c</fullName>
        <label>支払先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>買掛データ</relationshipLabel>
        <relationshipName>KaikakeData_Shiiresaki</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShimeHizuke__c</fullName>
        <label>￥￥_締基準日</label>
        <type>Date</type>
    </fields>
    <label>買掛データ</label>
    <nameField>
        <label>支払名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShiharaiMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>HachuMeisaiData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>発注明細データ</label>
        <referenceTo>HachuMeisaiData__c</referenceTo>
        <relationshipLabel>支払明細データ</relationshipLabel>
        <relationshipName>ShiharaiMeisaiData_HachuMeisaiData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KaikakeData__c</fullName>
        <label>買掛データ</label>
        <referenceTo>KaikakeData__c</referenceTo>
        <relationshipLabel>支払明細データ</relationshipLabel>
        <relationshipName>ShiharaiMeisaiData_KaikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nohinbi__c</fullName>
        <inlineHelpText>支払計上を行う日付。
買掛データの締期間に合わせて集計される。</inlineHelpText>
        <label>計上日</label>
        <type>Date</type>
    </fields>
    <label>支払明細データ</label>
    <nameField>
        <displayFormat>支払明細-{0000000000}</displayFormat>
        <label>支払明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShiharaiMeisaiDataTriggerHandlerTest.cls
@isTest
private class ShiharaiMeisaiDataTriggerHandlerTest {

    // 支払明細データ．発注明細データ．発注データ．都度支払フラグがTrueの場合
    // かつ、支払明細データ．買掛データ．都度支払フラグがTrueではない）場合
    static testMethod void myUnitTest1() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20);
        Account acc2 = new Account(name = '株式会社仕入先1', Shimebi__c = 20, Type='仕入先');
        accList.add(acc1);
        accList.add(acc2);
        insert accList;
        
        // 発注データ作成
        List<HachuData__c> hachuList = new List<HachuData__c>();
        HachuData__c hachu1 = new HachuData__c(Shiiresaki__c = acc2.Id);
        hachuList.add(hachu1);
        insert hachuList;
        
        // 発注明細データ作成
        List<HachuMeisaiData__c> hachuMeisaiList = new List<HachuMeisaiData__c>();
        HachuMeisaiData__c hachuMeisai1 = new HachuMeisaiData__c(HachuData__c = hachu1.Id);
        hachuMeisaiList.add(hachuMeisai1);
        insert hachuMeisaiList;
        
        // 買掛データ作成
        List<KaikakeData__c> kaikakeList = new List<KaikakeData__c>();
        KaikakeData__c kaikake1 = new KaikakeData__c(name='買掛テスト1', Shiiresaki__c = acc2.Id);
        kaikakeList.add(kaikake1);
        insert kaikakeList;
        
        Test.startTest();
        
        ShiharaiMeisaiData__c shiiremeisai = new ShiharaiMeisaiData__c();
        shiiremeisai.KaikakeData__c = kaikake1.Id;
        shiiremeisai.HachuMeisaiData__c = hachuMeisai1.Id;
        insert shiiremeisai;
        update shiiremeisai;
        
        Test.stopTest();
    }
    
    
    //支払明細データ．発注明細データ．発注データ．都度支払フラグがTrueではない場合
    static testMethod void myUnitTest2() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20);
        Account acc2 = new Account(name = '株式会社仕入先1', Shimebi__c = 20, Type='仕入先');
        accList.add(acc1);
        accList.add(acc2);
        insert accList;
        
        // 発注データ作成
        List<HachuData__c> hachuList = new List<HachuData__c>();
        HachuData__c hachu1 = new HachuData__c(Shiiresaki__c = acc2.Id);
        hachuList.add(hachu1);
        insert hachuList;
        
        // 発注明細データ作成
        List<HachuMeisaiData__c> hachuMeisaiList = new List<HachuMeisaiData__c>();
        HachuMeisaiData__c hachuMeisai1 = new HachuMeisaiData__c(HachuData__c = hachu1.Id);
        hachuMeisaiList.add(hachuMeisai1);
        insert hachuMeisaiList;
        
        // 買掛データ作成
        List<KaikakeData__c> kaikakeList = new List<KaikakeData__c>();
        KaikakeData__c kaikake1 = new KaikakeData__c(name='買掛テスト1', Shiiresaki__c = acc2.Id, ShimeHizuke__c = Date.newInstance(2015, 2, 1));
        kaikakeList.add(kaikake1);
        insert kaikakeList;
        
        Test.startTest();
        
        ShiharaiMeisaiData__c shiharaiMeisai = new ShiharaiMeisaiData__c();
        shiharaiMeisai.KaikakeData__c = kaikake1.Id;
        shiharaiMeisai.HachuMeisaiData__c = hachuMeisai1.Id;
        shiharaiMeisai.Nohinbi__c = Date.newInstance(2015, 4, 1);
        insert shiharaiMeisai;
        update shiharaiMeisai;
        Test.stopTest();
    }
}