src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HikiateNashiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>出荷引当を行わない場合ON。 
受注データの引当無フラグへWFRで反映。</inlineHelpText>
        <label>引当無納品モード</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuSokuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>納品確認を行わず受注データを受注確定するフラグ。

受注確定の条件
・受注データの引当無納品モードがONの場合。
・受注データの引当成功完了がONの場合。

例：納品確認を必要としない取引先はON。
例：受注数量と納品（売上）数量が変化しない取引先はON。
例：納品を伴わない商品（サービスやライセンス）の販売先はON。</inlineHelpText>
        <label>受注即確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SeishikiMeisho__c</fullName>
        <label>正式名称</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>HikiateNashiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>出荷引当を行わない場合ON。
取引先の引当無フラグからWFRで反映。</inlineHelpText>
        <label>引当無納品モード</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuUriageKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>受注データを確定し売掛データへの金額は集計を行う場合ON。</description>
        <inlineHelpText>納品の確定と請求の確定をする場合にON。

例）注文書FAXを受領し契約の意思確認が取れた。
例）商品を発送し先方から受領書を受け取った。</inlineHelpText>
        <label>納品請求確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>受注確定フラグOFFの場合に、売掛データの締期間を検索する日付。

出荷引当の試行時に、入出庫データの賞味期限を検索する日付。</inlineHelpText>
        <label>納品請求日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SaikenMihasseiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>商品（サービス）の納品前に請求を行う場合にON。
債権未発生フラグONの売掛データに集約される。
先払請求を行う際にON。</inlineHelpText>
        <label>先払債権無フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONする。
受注データの都度請求フラグONが集約される。
部分請求を行う際にON。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JuchuSuryoPC__c</fullName>
        <label>PC数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KeshikomiData__c.object
<CustomObject>
    <fields>
        <fullName>KeshikomiKakuninBi__c</fullName>
        <label>消込確認日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KeshikomiKingaku__c</fullName>
        <label>消込入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SokuKeshikomi__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求集計の未回収残高に合わせた　消込値引データを自動作成する　チェックボックス。

自動作成させる場合は消込入金額を　￥０円　とした状態でONする。</inlineHelpText>
        <label>￥￥_自動消込チェック</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>消込値引データ</relationshipLabel>
        <relationshipName>NyukinData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消込値引データ</label>
    <nameField>
        <label>消込値引名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NyukinData__c.object
<CustomObject>
    <fields>
        <fullName>NyukinBi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>入金日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NyukinGaku__c</fullName>
        <label>入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SeikyuAccounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>入金データ</label>
    <nameField>
        <displayFormat>入金-{0000000000}</displayFormat>
        <label>入金データ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HyojunBaika__c</fullName>
        <inlineHelpText>取引先条件マスタが存在しない場合に採用される商品の販売単価。</inlineHelpText>
        <label>標準売価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SaikenMihasseiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>商品（サービス）の納品前に請求を行う場合にON。トリガによりONされる。
受注データの債権未発生フラグONが集約される。</inlineHelpText>
        <label>先払債権無フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SeikyuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求を締切ってロックする場合ON。
NOの場合新たな受注データの納品確定が禁止。
NOの場合請求期間内の受注確定引当が禁止。</inlineHelpText>
        <label>請求確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShimeHizuke__c</fullName>
        <inlineHelpText>締め期間算出用の基準となる日付。

本日付を含む形で締期間（請求起算日～請求締日）が算出される。</inlineHelpText>
        <label>請求起算基準日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONされる。トリガによりONされる。
受注データの都度請求フラグONが集約される。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N07_NyukinIkkatsuTourokuControllerTest.cls
@isTest
private class N07_NyukinIkkatsuTourokuControllerTest {

    static testMethod void myUnitTest1() {

        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', HyojunBaika__c = 1000);
        shohinList.add(shohin1);
        insert shohinList;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        Account acc1 = new Account(name = '株式会社テスト1',SeishikiMeisho__c = '１', AccountTankaMHuyouFlg__c = true, JuchuSokuKakuteiFlg__c = true, HikiateNashiFlg__c = true);
        Account acc2 = new Account(name = '株式会社テスト2',SeishikiMeisho__c = '２', AccountTankaMHuyouFlg__c = true, JuchuSokuKakuteiFlg__c = true, HikiateNashiFlg__c = true);
        Account acc3 = new Account(name = '株式会社テスト3',SeishikiMeisho__c = '３', AccountTankaMHuyouFlg__c = true, JuchuSokuKakuteiFlg__c = true, HikiateNashiFlg__c = true);
        Account acc4 = new Account(name = '株式会社テスト4',SeishikiMeisho__c = '４', AccountTankaMHuyouFlg__c = true, JuchuSokuKakuteiFlg__c = true, HikiateNashiFlg__c = true);
        accList.add(acc1);
        accList.add(acc2);
        accList.add(acc3);
        accList.add(acc4);
        insert accList;
        
        //不明入金データ作成
        List<NyukinData__c> nkdList = new List<NyukinData__c>();
        NyukinData__c nkd1 = new NyukinData__c(SeikyuAccount__c = acc1.Id, NyukinGaku__c = 10000, NyukinBi__c = Date.today());
        NyukinData__c nkd2 = new NyukinData__c(SeikyuAccount__c = acc2.Id, NyukinGaku__c = 10000, NyukinBi__c = Date.today());
        NyukinData__c nkd3 = new NyukinData__c(SeikyuAccount__c = acc3.Id, NyukinGaku__c = 10, NyukinBi__c = Date.today());
        NyukinData__c nkd4 = new NyukinData__c(SeikyuAccount__c = acc4.Id, NyukinGaku__c = 10, NyukinBi__c = Date.today());
        nkdList.add(nkd1);
        nkdList.add(nkd2);
        nkdList.add(nkd3);
        nkdList.add(nkd4);
        insert nkdList;

        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        UrikakeData__c urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id, ShimeHizuke__c = Date.today(), SaikenMihasseiFlg__c = true, TsudoSeikyuFlg__c = true);
        UrikakeData__c urikake2 = new UrikakeData__c(name = acc2.Name, SeikyuAccount__c = acc2.Id, ShimeHizuke__c = Date.today(), SaikenMihasseiFlg__c = true);
        UrikakeData__c urikake3 = new UrikakeData__c(name = acc3.Name, SeikyuAccount__c = acc3.Id, ShimeHizuke__c = Date.today(), TsudoSeikyuFlg__c = false);
        UrikakeData__c urikake4 = new UrikakeData__c(name = acc4.Name, SeikyuAccount__c = acc4.Id, ShimeHizuke__c = Date.today().addMonths (-2) );
        urikakeList.add(urikake1);
        urikakeList.add(urikake2);
        urikakeList.add(urikake3);
        urikakeList.add(urikake4);
        insert urikakeList;

        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, NohinYoteibi__c = Date.today(), SaikenMihasseiFlg__c = true, TsudoSeikyuFlg__c = true);
        JuchuData__c juchu2 = new JuchuData__c(UrikakeData__c = urikake2.id, name = urikake2.Name, NohinYoteibi__c = Date.today(), SaikenMihasseiFlg__c = true);
        JuchuData__c juchu3 = new JuchuData__c(UrikakeData__c = urikake3.id, name = urikake3.Name, NohinYoteibi__c = Date.today(), TsudoSeikyuFlg__c = true);
        JuchuData__c juchu4 = new JuchuData__c(UrikakeData__c = urikake4.id, name = urikake4.Name, NohinYoteibi__c = Date.today());
        juchuList.add(juchu1);
        juchuList.add(juchu2);
        juchuList.add(juchu3);
        juchuList.add(juchu4);
        insert juchuList;

        // 受注明細作成
        List<JuchuMeisaiData__c> meisaiList = new List<JuchuMeisaiData__c>();
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(name = 'XXX', JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, JuchuSuryoPC__c = 10);
        JuchuMeisaiData__c meisai2 = new JuchuMeisaiData__c(name = 'XXX', JuchuData__c = juchu2.Id, ShohinShizaiM__c = shohin1.Id, JuchuSuryoPC__c = 10);
        JuchuMeisaiData__c meisai3 = new JuchuMeisaiData__c(name = 'XXX', JuchuData__c = juchu3.Id, ShohinShizaiM__c = shohin1.Id, JuchuSuryoPC__c = 10);
        JuchuMeisaiData__c meisai4 = new JuchuMeisaiData__c(name = 'XXX', JuchuData__c = juchu4.Id, ShohinShizaiM__c = shohin1.Id, JuchuSuryoPC__c = 10);
        meisaiList.add(meisai1);
        meisaiList.add(meisai2);
        meisaiList.add(meisai3);
        meisaiList.add(meisai4);
        insert meisaiList;

        // 受注確定
        juchuList[0].JuchuUriageKakuteiFlg__c = TRUE;
        juchuList[1].JuchuUriageKakuteiFlg__c = TRUE;
        juchuList[2].JuchuUriageKakuteiFlg__c = TRUE;
        juchuList[3].JuchuUriageKakuteiFlg__c = TRUE;
        update juchuList;

        // 請求確定
        urikakeList[0].SeikyuKakuteiFlg__c = TRUE;
        urikakeList[1].SeikyuKakuteiFlg__c = TRUE;
        urikakeList[2].SeikyuKakuteiFlg__c = TRUE;
        urikakeList[3].SeikyuKakuteiFlg__c = TRUE;
        update urikakeList;

        // 消込データ作成
        List<KeshikomiData__c> keshikomiListExist = new List<KeshikomiData__c>();
        KeshikomiData__c keshikomiE1 = new KeshikomiData__c(UrikakeData__c = urikake1.id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today().addDays(-1));
        KeshikomiData__c keshikomiE2 = new KeshikomiData__c(UrikakeData__c = urikake2.id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today().addDays(-1));
        KeshikomiData__c keshikomiE3 = new KeshikomiData__c(UrikakeData__c = urikake3.id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today().addDays(-1));
        KeshikomiData__c keshikomiE4 = new KeshikomiData__c(UrikakeData__c = urikake4.id, KeshikomiKingaku__c = 1, KeshikomiKakuninbi__c = Date.today().addDays(-1));
        keshikomiListExist.add(keshikomiE1);
        keshikomiListExist.add(keshikomiE2);
        keshikomiListExist.add(keshikomiE3);
        keshikomiListExist.add(keshikomiE4);
        insert keshikomiListExist;
        
        Test.startTest();
        
        N07_NyukinIkkatsuTourokuController controller = new N07_NyukinIkkatsuTourokuController();

        // 絞込無全件ボタン押下
        controller.initButtonFull();

        // 締払絞込ボタン押下
        controller.initButtonShimeBarai();
        controller.initButtonFull();

        // 取引先名絞込ボタン押下
        controller.RefineString = '１';
        controller.initButton();

        // 取引先名絞込ボタン押下
        controller.RefineString = NULL;
        controller.initButton();

        // 近似期日絞込ボタン押下
        controller.RefineDate = '1231';
        controller.initButton();

        // 近似期日絞込ボタン押下
        controller.RefineDate = '';
        controller.initButton();

        // 近似金額絞込ボタン押下
        controller.RefineValue = '1000';
        controller.initButton();

        // 近似金額絞込ボタン押下
        controller.RefineValue = '';
        controller.initButton();

        // 近似金額と期日絞込ボタン押下
        controller.RefineValue = '1000';
        controller.RefineDate = '1231';
        controller.initButton();
        controller.initButtonFull();

        // 都度払絞込ボタン押下
        controller.initButtonTsudoBarai();

        // 先払絞込ボタン押下
        controller.initButtonSakiBarai();
        
        // 都度と先払絞込ボタン押下
        controller.initButtonSakiBarai();
        controller.initButtonTsudoBarai();

        // 督促絞込ボタン押下
        controller.initButtonTokusokuTaisho();

        // 充当絞込ボタン押下
        controller.initButtonJutoTaisho();

        // 督促と充当絞込ボタン押下
        controller.initButtonTokusokuTaisho();
        controller.initButtonJutoTaisho();

        // 絞込無
        controller.initButtonFull();

        // 全件ボタン押下
        controller.saveButtonAll();

        // 新規追加された行の入金額を入力
        controller.accUrikakeList[0].urikakeKeshikomi[0].keshikomi[1].SokuKeshikomi__c = true;
        controller.accUrikakeList[1].urikakeKeshikomi[0].keshikomi[1].SokuKeshikomi__c = true;
        controller.saveButtonAll();        
        
        Test.stopTest();

    }

    // データが全くない状態でもエラーにならないかのテスト
    static testMethod void myUnitTest2() {
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        Account acc1 = new Account(name = '株式会社テスト1', SeishikiMeisho__c = '正式名称１', Shimebi__c = 20, Kijitsu__c = 15,  AccountTankaMHuyouFlg__c = true);
        accList.add(acc1);
        insert accList;
        
        Test.startTest();
        
        N07_NyukinIkkatsuTourokuController controller = new N07_NyukinIkkatsuTourokuController();
        // 画面表示時
        controller.initButtonFull();

        Test.stopTest();
    }

}