src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanKara__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>適用期間から</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanMade__c</fullName>
        <defaultValue>TODAY()  + 36500</defaultValue>
        <label>適用期間まで</label>
        <type>Date</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>Juchusaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注先店舗</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>受注出荷データ (受注先)</relationshipLabel>
        <relationshipName>JuchuData_Juchusaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UrikakeDataShokaibi__c</fullName>
        <formula>IF ( JuchuUriageKakuteiFlg__c ,
  JuchuUriageKakuteibi__c ,
  NohinYoteibi__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売掛データを検索する際の基準となる日付。

売掛データの新規生成時は、締期間起算日に代入される。

受注確定フラグONの場合は受注確定日。
受注確定フラグOFFの場合は提供予定日。</inlineHelpText>
        <label>￥￥_売掛データ照会日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TorihikisakiTanka__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>該当する取引先の該当商品資材マスターに設定された条件マスタが存在する場合に設定される。
受注データの日付（納品予定日/売上計上日）により、売掛データの期間設定が考慮され設定される。</inlineHelpText>
        <label>取引先条件</label>
        <referenceTo>AccountTankaM__c</referenceTo>
        <relationshipName>JuchuMeisaiData_TorihikisakiTanka</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J05_NohinKakakuRendoLogic.cls
public with sharing class J05_NohinKakakuRendoLogic {    

    // コンストラクタ
    public J05_NohinKakakuRendoLogic(){
        // 何もしない。
    }

    //受注明細登録前処理
    public void setTankaInsert(Map<Id,JuchuMeisaiData__c> newMap){
        // 全てが対象
        doSetContactId(newMap);
    }
    
    //受注明細更新前処理
    public void setTankaUpdate(Map<Id, JuchuMeisaiData__c>oldMap, Map<Id, JuchuMeisaiData__c>newMap){
        // 更新対象受注明細Map
        Map<Id, JuchuMeisaiData__c> targetMeisaiMap = new Map<Id,JuchuMeisaiData__c>();
        
        for(Id meisaiId :newMap.keySet()){
            // 商品資材が更新された場合のみ動作する。
            if(oldMap.get(meisaiId).ShohinShizaiM__c != newMap.get(meisaiId).ShohinShizaiM__c){
                // 更新対象受注明細リストに追加
                targetMeisaiMap.put(meisaiId, newMap.get(meisaiId));
            }
        }
        
        if(!targetMeisaiMap.isEmpty()){
            doSetContactId(targetMeisaiMap);
        }
    }
    
    //取引先単価マスタを紐付ける処理
    private void doSetContactId(Map<Id, JuchuMeisaiData__c> meisaiMap){
        // アップデート対象リスト
        List<JuchuMeisaiData__c> updMeisaiList = new List<JuchuMeisaiData__c>();
        
        // 単価マスタ不要フラグを取得
        List<JuchuMeisaiData__c> fullMeisaiDataList = new List<JuchuMeisaiData__c>();

        fullMeisaiDataList = [SELECT jm.Id, jm.ShohinShizaiM__c, ss.Name, jm.TorihikisakiTanka__c, jm.ShohinShizaiM__r.AccountTankaMHuyouFlg__c, jd.Juchusaki__c, jd.UrikakeDataShokaibi__c, sa.AccountTankaMHuyouFlg__c
                              FROM JuchuMeisaiData__c jm, JuchuMeisaiData__c.JuchuData__r jd,JuchuMeisaiData__c.JuchuData__r.UrikakeData__r.SeikyuAccount__r sa, JuchuMeisaiData__c.ShohinShizaiM__r ss
                              WHERE Id IN :meisaiMap.keySet()
                             ];
                       
        for(JuchuMeisaiData__c item :fullMeisaiDataList){

            // 取引先条件マスタ取得
            List<AccountTankaM__c> tanka = new List<AccountTankaM__c>();
            tanka = getTanka(item);

            // 取引先条件マスタを設定
            if(!tanka.isEmpty()){
                item.TorihikisakiTanka__c = tanka[0].Id;
            }else{
                item.TorihikisakiTanka__c = null;
            }
            updMeisaiList.add(item);
        }
        
        // 受注明細をアップデート
        if(!updMeisaiList.isEmpty()){
            update updMeisaiList;
        }
    }
    
    //該当する取引先単価マスタを取得する処理。該当なしの場合、空白のリストを返す。
    private List<AccountTankaM__c> getTanka(JuchuMeisaiData__c meisai){
        //返却用リスト
        List<AccountTankaM__c> tanka = new List<AccountTankaM__c>();

        // 商品資材 ＝ 受注明細データ．商品資材
        // かつ、取引先 ＝ 受注明細データ．受注データ．売掛データ．請求取引先
        // かつ、摘要期間から ≦ 受注明細データ．受注データ．売掛データ照会日
        // かつ、摘要期間まで ≧ 受注明細データ．受注データ．売掛データ照会日
        tanka = [SELECT Id FROM AccountTankaM__c
                 WHERE ShohinShizaiM__c = :meisai.ShohinShizaiM__c
                 AND Account__c = :meisai.JuchuData__r.UrikakeData__r.SeikyuAccount__c
                 AND TekiyoKikanKara__c <= :meisai.JuchuData__r.UrikakeDataShokaibi__c
                 AND TekiyoKikanMade__c >= :meisai.JuchuData__r.UrikakeDataShokaibi__c
                 LIMIT 1];
        return tanka;
    }
    
    //受注データの納品予定日を更新した時に取引先単価を更新する処理
    public void updateTorihikisakiTanka(JuchuData__c[] oldObjs, JuchuData__c[] newObjs){

        // アップデート対象リスト
        List<JuchuMeisaiData__c> updMeisaiList = new List<JuchuMeisaiData__c>();

        for(Integer i = 0; i < newObjs.size(); i++){
            // 保存前後のデータの売掛データ照会日が異なる場合のみ動作する。
            if(oldObjs[i].UrikakeDataShokaibi__c != newObjs[i].UrikakeDataShokaibi__c){
                // 請求先と取引先単価不要フラグを取得
                UrikakeData__c urikake = [SELECT ud.Id, ud.SeikyuAccount__c, sa.AccountTankaMHuyouFlg__c
                                          FROM UrikakeData__c ud, urikakeData__c.SeikyuAccount__r sa 
                                          WHERE Id = :newObjs[i].UrikakeData__c
                                          LIMIT 1
                                         ];
                                          
                // ぶら下がる受注明細データと参照する商品資材の取引先単価不要フラグを取得
                List<JuchuMeisaiData__c> juchuMeisaiList = [SELECT jm.Id, jm.ShohinShizaiM__c, jm.TorihikisakiTanka__c, ss.Name, ss.AccountTankaMHuyouFlg__c FROM JuchuMeisaiData__c jm, JuchuMeisaiData__c.ShohinShizaiM__r ss WHERE JuchuData__c = :newObjs[i].Id];

                // 請求先、適用期間と納品予定日が一致する単価マスタと商品資材を全て取得
                List<AccountTankaM__c> tankaList = [SELECT Id, ShohinShizaiM__c, Account__c, TekiyoKikanKara__c, TekiyoKikanMade__c
                                                    FROM AccountTankaM__c
                                                    WHERE Account__c = :urikake.SeikyuAccount__c
                                                        AND TekiyoKikanKara__c <= :newObjs[i].UrikakeDataShokaibi__c
                                                        AND TekiyoKikanMade__c >= :newObjs[i].UrikakeDataShokaibi__c
                                                   ];
                                                   
                // 受注明細のリストと取引先単価マスタのリストをまわし、商品資材が一致すれば紐付ける。
                
                // 取引先単価マスタが見つかったかどうか
                Boolean isFind;
                            
                for(JuchuMeisaiData__c meisaiItem :juchuMeisaiList){
                    isFind = false;
                    for(AccountTankaM__c tankaItem :tankaList){
                        // 見つかった場合は取引先単価マスタを紐付ける
                        if(meisaiItem.ShohinShizaiM__c.equals(tankaItem.ShohinShizaiM__c)){
                            meisaiItem.TorihikisakiTanka__c = tankaItem.Id;
                            isFind = true;
                            updMeisaiList.add(meisaiItem);
                        }
                    }
                
                    // 見つからない場合
                    if(!isFind){
                        // 取引先条件マスターを解除
                        meisaiItem.TorihikisakiTanka__c = null;
                        updMeisaiList.add(meisaiItem);
                    }
                }

            }

        }

        // 受注明細データをアップデートする。
        if(!updMeisaiList.isEmpty()){
            update updMeisaiList;
        }

    }
}