src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigenKakuhoNissu__c</fullName>
        <description>商品資材マスタ　の　販売管理期限日数　が　標準値</description>
        <inlineHelpText>出荷時に担保する必要のある消費期限の期間。
例：販売管理期限など。
例：納品管理期限など。</inlineHelpText>
        <label>消費期限確保日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>ShomiKigenNissu__c</fullName>
        <inlineHelpText>製品が製造完了後に正常に消費（使用)出来る期間。
例：食品であれば賞味期限など。
例：機械部品であれば保証期間など。</inlineHelpText>
        <label>消費期限日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/J44_AccountTankaMControllerExtentionTest.cls
@isTest
private class J44_AccountTankaMControllerExtentionTest {
    static testMethod void myUnitTest1() {
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99));
        insert accList;
        
        // 取引先単価マスタ作成
        List<AccountTankaM__c> tankaList = new List<AccountTankaM__c>();
        tankaList.add(new AccountTankaM__c(Account__c = accList[0].Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10));
        insert tankaList; 
        
        Test.startTest();
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from AccountTankaM__c'));
        ssc.setSelected(tankaList);
        J44_AccountTankaMControllerExtension extension = new J44_AccountTankaMControllerExtension(ssc);

        //ApexPages.currentPage().getParameters().put('retUrl', 'hogehoge');
        //J44_AccountTankaMControllerExtention controller = new J44_AccountTankaMControllerExtention();
        //controller.init();
        extension.init();
        
        Test.stopTest();
    }
}