src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KobetsuHikiateJikkoFlg__c</fullName>
        <formula>NOT( ISBLANK( KobetsuHikiateSaki__c ) )</formula>
        <label>￥￥_個別引当実行フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KobetsuHikiateSakiShokai__c</fullName>
        <formula>KobetsuHikiateSaki__r.Id</formula>
        <label>￥￥_個別引当先照会</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YusenHikiateSakiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>標準の受注引当を行う在庫先（引当先）の場合ON。
システム全体で１レコードのみON設定とする前提。
複数レコードに指定した場合はIDの若番のみが有効。</inlineHelpText>
        <label>優先引当先フラグ</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>HyojunHikiateJikkoFlg__c</fullName>
        <formula>AND( 
 ISBLANK( ZaikoHikiateSaki__c ) , 
 NOT(DenpyoKingakuZeroFlg__c ), 
 NOT(Juchusaki__r.KobetsuHikiateJikkoFlg__c)  , 
 NOT(Nohinsaki__r.KobetsuHikiateJikkoFlg__c)  
)</formula>
        <inlineHelpText>レコード作成直後のトリガの処理実行を避けるため￥￥_伝票金額ゼロフラグOFFが必須。
受注先と納品先の両方で個別引当実行フラグOFFが必須。</inlineHelpText>
        <label>￥￥_標準引当実行フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KobetsuHikiateJikkoFlg__c</fullName>
        <formula>AND(
 ISBLANK( ZaikoHikiateSaki__c ) ,
 NOT( DenpyoKingakuZeroFlg__c ), 
OR(
 Juchusaki__r.KobetsuHikiateJikkoFlg__c  ,
 Nohinsaki__r.KobetsuHikiateJikkoFlg__c 
) 
)</formula>
        <inlineHelpText>優先引当先の在庫先以外に取引先マスタに個別設定した在庫先から引当を行う。

ON条件。

受注データ　出荷引当先　空白
　かつ
伝票金額ゼロフラグ　OFF。

　または

受注先　個別引当実行フラグ　ON。
　あるいは
納品先　個別引当実行フラグ　ON。

レコード作成直後のトリガの処理実行を避けるため伝票金額ゼロフラグOFFが必須。</inlineHelpText>
        <label>￥￥_個別引当実行フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KobetsuHikiateSakiShokai__c</fullName>
        <formula>IF ( ISBLANK( Nohinsaki__c ) ,
 Juchusaki__r.KobetsuHikiateSakiShokai__c ,
 Nohinsaki__r.KobetsuHikiateSakiShokai__c 
)</formula>
        <inlineHelpText>納品先が空白：受注先の個別引当先のID。
納品先が選択済み：納品先の個別引当先のID。</inlineHelpText>
        <label>￥￥_個別引当先照会</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZaikoHikiateSaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷引当先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>JuchuData_ZaikoHikiateSaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Z99_JuchuHikiateSakiRendoLogic.cls
public with sharing class Z99_JuchuHikiateSakiRendoLogic {

	public void ZaikoHikiateSakiUpdate(List<JuchuData__c> newObjs){

        //優先引当先フラグONの既存の取引先マスタを取得する。
        List<Account> YusenHikiateSaki = new List<Account>();
        YusenHikiateSaki = [SELECT Id, Name, YusenHikiateSakiFlg__c FROM Account WHERE YusenHikiateSakiFlg__c = TRUE LIMIT 1];

        system.debug('*** YusenHikiateSaki: ' + YusenHikiateSaki);

		//受注データ一覧を順に処理する。
		for(JuchuData__c jd : newObjs){

			if(jd.KobetsuHikiateJikkoFlg__c){
				jd.ZaikoHikiateSaki__c = jd.KobetsuHikiateSakiShokai__c;
			}else{
                if(jd.HyojunHikiateJikkoFlg__c){
					//優先引当先フラグONの取引先が無かった場合を考慮。
					if(!YusenHikiateSaki.isEmpty()){
						jd.ZaikoHikiateSaki__c = YusenHikiateSaki[0].Id;

                        system.debug('*** YusenHikiateSaki[0]: ' + YusenHikiateSaki[0]);

                    }
				}
			}

		}

	}

}