src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanKara__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>適用期間から</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanMade__c</fullName>
        <defaultValue>TODAY()  + 36500</defaultValue>
        <label>適用期間まで</label>
        <type>Date</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>Juchusaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注先店舗</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>受注出荷データ (受注先)</relationshipLabel>
        <relationshipName>JuchuData_Juchusaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>受注確定フラグOFFの場合に、売掛データの締期間を検索する日付。

出荷引当の試行時に、入出庫データの賞味期限を検索する日付。</inlineHelpText>
        <label>納品請求日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JuchuMeisaiDataTriggerHandlerTest.cls
@isTest
private class JuchuMeisaiDataTriggerHandlerTest {
    
    static testMethod void myUnitTest1() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト20150216J05', Type = '納品先', AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテスト20150216J05', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        juchuList.add(new JuchuData__c(name = '受注データテスト20150216J05', UrikakeData__c = urikakeList[0].Id, 
            Juchusaki__c = accList[0].Id, NohinYoteibi__c = Date.newInstance(2015, 2, 15)) );
        insert juchuList;
        
        // 商品資材マスタ作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150216J05_1', AccountTankaMHuyouFlg__c = true));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150216J05_2'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150216J05_3'));
        insert shohinList;
        
        // 取引先単価マスタデータ作成
        List<AccountTankaM__c> accMList = new List<AccountTankaM__c>();
        accMList.add(new AccountTankaM__c(Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[0].Id, 
            TekiyoKikanKara__c = Date.newInstance(2015, 2, 1), TekiyoKikanMade__c = Date.newInstance(2015, 2, 28)));
        insert accMList;

        Test.startTest();

        // 受注明細データ作成
        List<JuchuMeisaiData__c> meisaiList1 = new List<JuchuMeisaiData__c>();
        meisaiList1.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501a', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[0].Id
            ));
        insert meisaiList1;
                
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c();
        meisai1.name = '受注明細データテスト20150216J0502';
        meisai1.JuchuData__c = juchuList[0].Id;
        meisai1.ShohinShizaiM__c = shohinList[1].Id;
        insert meisai1;
        meisai1.ShohinShizaiM__c = shohinList[2].Id;
        update meisai1;

        delete meisai1;

        Test.stopTest();
    }

    static testMethod void myUnitTest2() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト20150216J05', Type = '納品先', AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテスト20150216J05', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        juchuList.add(new JuchuData__c(name = '受注データテスト20150216J05', UrikakeData__c = urikakeList[0].Id, 
            Juchusaki__c = accList[0].Id, NohinYoteibi__c = Date.newInstance(2015, 2, 15)) );
        insert juchuList;
        
        // 商品資材マスタ作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150216J05_1', AccountTankaMHuyouFlg__c = true));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150216J05_2'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150216J05_3'));
        insert shohinList;
        
        // 取引先単価マスタデータ作成
        List<AccountTankaM__c> accMList = new List<AccountTankaM__c>();
        accMList.add(new AccountTankaM__c(Account__c = accList[0].Id, ShohinShizaiM__c = shohinList[0].Id, 
            TekiyoKikanKara__c = Date.newInstance(2015, 2, 1), TekiyoKikanMade__c = Date.newInstance(2015, 2, 28)));
        insert accMList;

        Test.startTest();

        // 受注明細データ作成
        List<JuchuMeisaiData__c> meisaiList1 = new List<JuchuMeisaiData__c>();
        meisaiList1.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501a', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[0].Id
            ));
        meisaiList1.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501b', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[1].Id
            ));
        meisaiList1.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501c', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[2].Id
            ));
        insert meisaiList1;

        List<JuchuMeisaiData__c> meisaiList2 = new List<JuchuMeisaiData__c>();
        meisaiList2.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501d', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[0].Id
            ));
        meisaiList2.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501e', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[1].Id
            ));
        meisaiList2.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150216J0501f', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[2].Id
            ));

        try{
            insert meisaiList2;
        }catch (DmlException e){
            System.debug('### ' + 'DmlException');
        }

        Test.stopTest();
    }

}