src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Biko__c</fullName>
        <inlineHelpText>受注登録時に表示させたい内容（例：午前の便出荷必須）を記入。</inlineHelpText>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <type>TextArea</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>JuchuMeisaiSaidaiTorokusu__c</fullName>
        <defaultValue>35</defaultValue>
        <label>受注明細最大登録数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J01_JuchuDataControllerExtensionTest.cls
@isTest
public class J01_JuchuDataControllerExtensionTest {

    static testMethod void myUnitTest() {

        // カスタム設定
        SystemParam__c SystemParam = SystemParam__c.getOrgDefaults();
        SystemParam.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert SystemParam;

        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品1'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品2'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品3'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品4'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品5'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品6'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品7'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品8'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品9'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品10'));
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品11'));
        insert shohinList;

        // 取引先作成
        Account acc = new Account();
        acc = new Account(name = 'XXX', AccountTankaMHuyouFlg__c = true);
        insert acc;

        // 売掛データ作成
        UrikakeData__c Urikake = new UrikakeData__c();
        urikake = new UrikakeData__c(name = 'XXX', SeikyuAccount__c = acc.Id);
        insert urikake;

        // 受注データ作成
        JuchuData__c juchu = new JuchuData__c();
        juchu = new JuchuData__c(name = 'XXX', UrikakeData__c = urikake.id );
        insert juchu;

        // 受注明細データ作成
        List<JuchuMeisaiData__c> juchuMeisaiDataList = new List<JuchuMeisaiData__c>();
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[0].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[1].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[2].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[3].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[4].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[5].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[6].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[7].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[8].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[9].Id, Biko__c = '', JuchuData__c = juchu.Id));
        juchuMeisaiDataList.add(new JuchuMeisaiData__c(name = 'XXXXX', ShohinShizaiM__c = shohinList[10].Id, Biko__c = '', JuchuData__c = juchu.Id));
        insert juchuMeisaiDataList;

        // テスト実行時の画面を設定
        PageReference pageRef = new PageReference('/' + juchu.Id);
        Test.setCurrentPage(pageRef);

        // コントローラー起動
        ApexPages.Standardcontroller stdController =  new ApexPages.Standardcontroller(juchu);
        J01_JuchuDataControllerExtension extController = new J01_JuchuDataControllerExtension(stdController);
        
        // テスト実行開始
        Test.startTest();

        // 保存ボタン
        extController.saveButton();

        //再表示ボタン
        extController.reDisplay();

        // ページ次ページ
        extController.next();

        // ページ前ページ
        extController.previous();

        // DmlException発生
        extController.targetMeisaiList[0].Biko__c = 'ｱ';
        extController.saveButton();
        
        // テスト実行終了
        Test.stopTest();
        
    }

}