src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MeisaiJyogai__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求書の明細に表示しない場合にON。</inlineHelpText>
        <label>請求隠</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinJogai__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>納品書の明細に表示しない場合にON。</inlineHelpText>
        <label>納品隠</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>NohinshoMeisaiMaxNum__c</fullName>
        <defaultValue>18</defaultValue>
        <label>納品書明細最大行数</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JuchuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注明細</label>
        <referenceTo>JuchuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J22_NohinshoControllerTest.cls
@isTest
private class J22_NohinshoControllerTest {
    // 在庫データが存在する場合
    static testMethod void myUnitTest1() {

        // 明細最大表示件数
        insert new SystemParam__c(NohinshoMeisaiMaxNum__c = 6);
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト20150213J22', Type = '納品先', AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテスト20150213J22', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        juchuList.add(new JuchuData__c(name = '受注データテスト20150213J22', UrikakeData__c = urikakeList[0].Id));
        insert juchuList;
        
        // 商品資材マスタ作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J221'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J222'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J223'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J224'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J225'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J226'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J227'));
        shohinList.add(new ShohinShizaiM__c(name = '商品資材名テスト20150213J228'));
        insert shohinList;
        
        // 受注明細データ作成
        List<JuchuMeisaiData__c> meisaiList = new List<JuchuMeisaiData__c>();
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2201', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[0].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2202', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[1].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2203', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[2].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2204', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[3].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2205', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[4].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2206', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[5].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2207', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[6].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));
        meisaiList.add(new JuchuMeisaiData__c(
            name = '受注明細データテスト20150213J2208', 
            JuchuData__c = juchuList[0].Id,
            ShohinShizaiM__c = shohinList[7].Id,
            MeisaiJyogai__c = False,
            NohinJogai__c = FALSE
            ));

        insert meisaiList;
        
        // 在庫データ作成
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2201', ShohinShizaiM__c = shohinList[0].Id, JuchuMeisai__c = meisaiList[0].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2202', ShohinShizaiM__c = shohinList[1].Id, JuchuMeisai__c = meisaiList[1].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2203', ShohinShizaiM__c = shohinList[2].Id, JuchuMeisai__c = meisaiList[2].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2204', ShohinShizaiM__c = shohinList[3].Id, JuchuMeisai__c = meisaiList[3].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2205', ShohinShizaiM__c = shohinList[4].Id, JuchuMeisai__c = meisaiList[4].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2206', ShohinShizaiM__c = shohinList[5].Id, JuchuMeisai__c = meisaiList[5].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2207', ShohinShizaiM__c = shohinList[6].Id, JuchuMeisai__c = meisaiList[6].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2208', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J2209', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220a', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220b', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220c', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220d', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220e', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220f', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220g', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220h', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220i', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        zaikoList.add(new ZaikoData__c(name = '在庫データテスト20150213J220j', ShohinShizaiM__c = shohinList[7].Id, JuchuMeisai__c = meisaiList[7].Id));
        insert zaikoList;
        
        Test.startTest();

        // 受注データIDをURLに設定
        Test.setCurrentPage(Page.J22_Nohinsho);   
        ApexPages.currentPage().getParameters().put('JdId', juchuList[0].Id);

        J22_NohinshoController controller = new J22_NohinshoController();
        controller.doUpdate();
        
        Test.stopTest();
    }
    
    
    // 在庫データが存在しない場合
    static testMethod void myUnitTest2() {

        // 明細最大表示件数
        insert new SystemParam__c(NohinshoMeisaiMaxNum__c = 2);
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト20150213J2202', Type = '納品先', AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテスト20150213J2202', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        juchuList.add(new JuchuData__c(name = '受注データテスト20150213J2202', UrikakeData__c = urikakeList[0].Id));
        insert juchuList;
        
        Test.startTest();

        // 受注データIDをURLに設定
        Test.setCurrentPage(Page.J22_Nohinsho);   
        ApexPages.currentPage().getParameters().put('JdId', juchuList[0].Id);

        J22_NohinshoController controller = new J22_NohinshoController();
        controller.doUpdate();

        Integer nohinshoFontSize = controller.nohinshoFontSize;
        
        Test.stopTest();
    }
}