src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HyojunBaika__c</fullName>
        <formula>ShohinShizaiM__r.HyojunBaika__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>標準売価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanKara__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>適用期間から</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanMade__c</fullName>
        <defaultValue>TODAY()  + 36500</defaultValue>
        <label>適用期間まで</label>
        <type>Date</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HachuData__c.object
<CustomObject>
    <fields>
        <fullName>HachuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>発注確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hachubi__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>発注日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <label>納品予定日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nohinsaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納品先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Nohinsaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shiiresaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>仕入先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Shiiresaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注データ</label>
    <nameField>
        <displayFormat>発注-{0000000000}</displayFormat>
        <label>発注番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>HachuData__c</fullName>
        <label>発注データ</label>
        <referenceTo>HachuData__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_HachuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HachuKakuteiFlg__c</fullName>
        <formula>HachuData__r.HachuKakuteiFlg__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_発注確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HachuSuryoPC__c</fullName>
        <label>発注数量PC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KonyuKakaku__c</fullName>
        <inlineHelpText>空白　の　場合　商品資材マスタ　の　標準原価　となる。</inlineHelpText>
        <label>購入単価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <description>発注時には決まらず、納期回答があれば入力する</description>
        <inlineHelpText>発注時には決まらず、納期回答があれば入力する</inlineHelpText>
        <label>納品予定日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_ShohinShizaiM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>HyojunBaika__c</fullName>
        <inlineHelpText>取引先条件マスタが存在しない場合に採用される商品の販売単価。</inlineHelpText>
        <label>標準売価</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>HachuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>発注明細</label>
        <referenceTo>HachuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_HachuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NyukoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>実在庫状態以降。オフの場合は予約データ（未入庫）となる。</description>
        <inlineHelpText>実際に入庫を確認したことを表す。オフの場合は確認未実施となる。</inlineHelpText>
        <label>入庫フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukoNichiji__c</fullName>
        <inlineHelpText>当在庫場所へ入庫した日時
・製造完了した日付を表す場合は消費期限の算出基準となる。
・在庫を移動した日付を表す場合は入庫確認の実施タイミングとなる。</inlineHelpText>
        <label>入庫日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zaikobasho__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>場所</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>入出庫データ</relationshipLabel>
        <relationshipName>ZaikoData_Zaikobasho</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZaikoDataTriggerHandlerTest.cls
@isTest
private class ZaikoDataTriggerHandlerTest {

    static testMethod void myUnitTest1() {
        // 商品資材作成
        ShohinShizaiM__c shohin = new ShohinShizaiM__c(name = 'テスト商品1', HyojunBaika__c = 1);
        insert shohin;
        
        // 仕入先作成
        Account acc1 = new Account(Name = 'テスト取引先');
        insert acc1;
        
        // 納品先作成
        Account acc2 = new Account(Name = 'テスト納品先');
        insert acc2;

        // 発注データ作成
        HachuData__c hachu = new HachuData__c (Shiiresaki__c = acc1.Id, Hachubi__c = Date.today(), Nohinsaki__c = acc2.Id, NohinYoteibi__c = Date.today().addDays(10));
        insert hachu;
        
        // 発注明細データ作成
        HachuMeisaiData__c meisai = new HachuMeisaiData__c(HachuData__c = hachu.Id, ShohinShizaiM__c = shohin.Id, HachuSuryoPC__c = 1, KonyuKakaku__c = 123);
        insert meisai;
        update meisai;
        
        Test.startTest();
        // 発注データ更新
        hachu.HachuKakuteiFlg__c = true;
        update hachu;
        
        // 在庫データが作成されている
        ZaikoData__c zaiko = [SELECT Id, NyukoFlg__c FROM ZaikoData__c WHERE HachuMeisai__c = :meisai.Id];
        
        // 在庫データ更新
        zaiko.NyukoFlg__c = true;
        update zaiko;
        
        // 在庫データ更新
        zaiko.NyukoFlg__c = false;
        update zaiko;

        // 在庫データ削除
        delete zaiko;
        
        Test.stopTest();
    }
    
    static testMethod void myUnitTest2() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト'));
        insert accList;
        
        // 商品資材マスタ作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(
            name = '商品資材名テスト'
            ));
        insert shohinList;
        
        // 取引先単価マスタ作成
        List<AccountTankaM__c> tankaMs = new List<AccountTankaM__c>();
        tankaMs.add(new AccountTankaM__c(
            ShohinShizaiM__c = shohinList[0].Id,
            Account__c = accList[0].Id,
            TekiyoKikanKara__c = Date.today(),
            TekiyoKikanMade__c = Date.today().addDays(10)));
        insert tankaMs;
        
        Test.startTest();
        // 在庫データ作成
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        zaikoList.add(new ZaikoData__c(
            name = '在庫データテスト', 
            ShohinShizaiM__c = shohinList[0].Id, 
            Zaikobasho__c = accList[0].Id,
            NyukoNichiji__c = Datetime.now()
            ));
        insert zaikoList;
        
        Test.stopTest();
    }
}