src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KobetsuHikiateSaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>標準の引当先以外から受注引当を行うばあい指定。
選択がない場合は標準引当先フラグONの倉庫（取引先マスタ）が割り当てられる。
通常は受注データの受注先から個別引当先が選択される。
受注データの納品先が設定される場合は納品先から個別引当先が選択される。</inlineHelpText>
        <label>個別引当先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>取引先 (優先引当先)</relationshipLabel>
        <relationshipName>YusenHikiateSakis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YusenHikiateSakiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>標準の受注引当を行う在庫先（引当先）の場合ON。
システム全体で１レコードのみON設定とする前提。
複数レコードに指定した場合はIDの若番のみが有効。</inlineHelpText>
        <label>優先引当先フラグ</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>Juchubi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>受注登録日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>受注確定フラグOFFの場合に、売掛データの締期間を検索する日付。

出荷引当の試行時に、入出庫データの賞味期限を検索する日付。</inlineHelpText>
        <label>納品請求日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONする。
受注データの都度請求フラグONが集約される。
部分請求を行う際にON。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShimeHizuke__c</fullName>
        <inlineHelpText>締め期間算出用の基準となる日付。

本日付を含む形で締期間（請求起算日～請求締日）が算出される。</inlineHelpText>
        <label>請求起算基準日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONされる。トリガによりONされる。
受注データの都度請求フラグONが集約される。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JuchuDataTriggerHandlerTest.cls
@isTest
private class JuchuDataTriggerHandlerTest {
    
    // 都度請求でない、同じ売掛データに紐付く場合
    static testMethod void myUnitTest1() {

        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true));
        upsert accList;
        //Z99を考慮し優先引当先情報を持つ取引先マスタを作成
        accList.add(new Account(name = '標準引当先テスト2', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, YusenHikiateSakiFlg__c = true));
        upsert accList;
        accList.add(new Account(name = '株式会社テスト3', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, KobetsuHikiateSaki__c = accList[1].Id));
        upsert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> UrikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = accList[0].Name, SeikyuAccount__c = accList[0].Id, ShimeHizuke__c = Date.newInstance(2015, 1, 1)));
        insert urikakeList;

        // 受注データ作成
        JuchuData__c juchu = new JuchuData__c();
        juchu = new JuchuData__c(UrikakeData__c = urikakeList[0].id, name = urikakeList[0].Name, Juchubi__c = Date.newInstance(2015, 1, 1));
        insert juchu;
        
        Test.startTest();
        
        juchu.NohinYoteibi__c = Date.newInstance(2015, 1, 2);
        update juchu;
        
        Test.stopTest();

    }
    
    // 都度請求でない、同じ売掛データに紐付かない場合
    static testMethod void myUnitTest2() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true));
        upsert accList;
        //Z99を考慮し優先引当先情報を持つ取引先マスタを作成
        accList.add(new Account(name = '標準引当先テスト2', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, YusenHikiateSakiFlg__c = true));
        upsert accList;
        accList.add(new Account(name = '株式会社テスト3', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, KobetsuHikiateSaki__c = accList[1].Id));
        upsert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> UrikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = accList[0].Name, SeikyuAccount__c = accList[0].Id));
        insert urikakeList;

        // 受注データ作成
        JuchuData__c juchu = new JuchuData__c();
        juchu = new JuchuData__c(UrikakeData__c = urikakeList[0].id, name = urikakeList[0].Name, Juchubi__c = Date.today());
        insert juchu;
        
        Test.startTest();
        
        juchu.NohinYoteibi__c = juchu.Juchubi__c.addYears(1);
        update juchu;
        
        Test.stopTest();
    }
    
    // 都度請求の場合
    static testMethod void myUnitTest3() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true));
        upsert accList;
        //Z99を考慮し優先引当先情報を持つ取引先マスタを作成
        accList.add(new Account(name = '標準引当先テスト2', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, YusenHikiateSakiFlg__c = true));
        upsert accList;        
        accList.add(new Account(name = '株式会社テスト3', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, KobetsuHikiateSaki__c = accList[1].Id));
        upsert accList;

        // 売掛データ作成
        List<UrikakeData__c> UrikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = accList[0].Name, SeikyuAccount__c = accList[0].Id));
        insert urikakeList;

        // 受注データ作成
        JuchuData__c juchu = new JuchuData__c();
        juchu = new JuchuData__c(UrikakeData__c = urikakeList[0].id, name = urikakeList[0].Name, Juchubi__c = Date.today());
        insert juchu;
        
        Test.startTest();
        
        juchu.TsudoSeikyuFlg__c = true;
        update juchu;
        
        Test.stopTest();
    }
}