src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <inlineHelpText>受注登録時に表示させたい内容（例：午前の便出荷必須）を記入。</inlineHelpText>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nohinsaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納品先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Nohinsaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注データ</label>
    <nameField>
        <displayFormat>発注-{0000000000}</displayFormat>
        <label>発注番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachuData__c</fullName>
        <label>発注データ</label>
        <referenceTo>HachuData__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_HachuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_ShohinShizaiM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <type>TextArea</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>HachushoMeisaiMaxNum__c</fullName>
        <defaultValue>5</defaultValue>
        <label>発注書明細最大行数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/classes/K01_HachushoControllerTest.cls
@isTest
private class K01_HachushoControllerTest {
    static testMethod void myUnitTest1() {

        //発注書明細最大行数
        insert new SystemParam__c(HachushoMeisaiMaxNum__c = 1);
        
        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = '商品テスト20150206J22'));
        insert shohinList;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト20150206J22', Type = '納品先'));
        insert accList;
        
        // 発注データ作成
        List<HachuData__c> hachuDataList = new List<HachuData__c>();
        hachuDataList .add(new HachuData__c(Nohinsaki__c= accList[0].Id, Biko__c = 'ABCDFFG'));
        insert hachuDataList ;
        
        // 発注明細データ作成
        List<HachuMeisaiData__c> meisaiList = new List<HachuMeisaiData__c>();
        meisaiList .add(new HachuMeisaiData__c(ShohinShizaiM__c= shohinList[0].id, HachuData__c= hachuDataList[0].Id));
        meisaiList .add(new HachuMeisaiData__c(ShohinShizaiM__c= shohinList[0].id, HachuData__c= hachuDataList[0].Id));
        insert meisaiList ;
        
        Test.startTest();
        
        // 発注データIDをURLに設定
        Test.setCurrentPage(Page.K01_Hachusho);   
        ApexPages.currentPage().getParameters().put('HdId', hachuDataList[0].Id);

        K01_HachushoController controller = new K01_HachushoController();
        
        Test.stopTest();
    }
}