src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <inlineHelpText>受注登録時に表示させたい内容（例：午前の便出荷必須）を記入。</inlineHelpText>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeishoMaruchiKensaku__c</fullName>
        <formula>Name  + &quot; &quot; + 
SeishikiMeisho__c + &quot; &quot; + 
SeishikiMeisho__c + &quot; &quot; + 
Ryakusho__c + &quot; &quot; + 
TorihikisakiCode__c + &quot; &quot;</formula>
        <inlineHelpText>取引先名 正式名称 略称 取引先コード を元に検索するための文字列を出力。</inlineHelpText>
        <label>￥￥_名称マルチ検索</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MikakuteiJutoFlg__c</fullName>
        <formula>OR(
 KeshikomiMikakuteiCounter__c   &gt; 0,
 FumeiNyukinZengakuNamachi__c  &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>消込未確定フラグ　がONの　入金充当リンク　が存在する場合にON。
あるいは　不明入金残額計　が　￥１円以上の場合にON。</inlineHelpText>
        <label>充当未確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MinyukinZandakaSokei__c</fullName>
        <formula>SeikyuKingakuSokei__c  -  KaishuGakuSokei__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>請求金額総計－回収消込額総計</inlineHelpText>
        <label>未回収残高総計</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NyukinSaidaiGaku__c</fullName>
        <inlineHelpText>各　不明入金データ　中の　残金額　の最大額</inlineHelpText>
        <label>入金最大額</label>
        <summarizedField>NyukinData__c.ZanKingaku__c</summarizedField>
        <summaryFilterItems>
            <field>NyukinData__c.KeshikomiJutoZumiFlg__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>NyukinData__c.SeikyuAccount__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NyukinSaishoGaku__c</fullName>
        <inlineHelpText>各　不明入金データ　中の　残金額　の最小額</inlineHelpText>
        <label>入金最小額</label>
        <summarizedField>NyukinData__c.ZanKingaku__c</summarizedField>
        <summaryFilterItems>
            <field>NyukinData__c.KeshikomiJutoZumiFlg__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>NyukinData__c.SeikyuAccount__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NyukinZengaku__c</fullName>
        <inlineHelpText>不明入金データ　残金額　の合計額</inlineHelpText>
        <label>入金済金額</label>
        <summarizedField>NyukinData__c.ZanKingaku__c</summarizedField>
        <summaryFilterItems>
            <field>NyukinData__c.KeshikomiJutoZumiFlg__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>NyukinData__c.SeikyuAccount__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SeikyuTaishoFlg__c</fullName>
        <formula>MinyukinZandakaSokei__c &lt;&gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>未入金残高総計　が　￥０　の場合ON。
入金値引登録の対象となる。</inlineHelpText>
        <label>￥￥_請求対象フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SeishikiMeisho__c</fullName>
        <label>正式名称</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokusokuFlg__c</fullName>
        <formula>TokusokuCounter__c  &gt;= 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>督促カウンタ　≧　１　の場合ON</inlineHelpText>
        <label>督促フラグ</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KeshikomiData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KeshikomiKakuninBi__c</fullName>
        <label>消込確認日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KeshikomiKingaku__c</fullName>
        <label>消込入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SokuKeshikomi__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求集計の未回収残高に合わせた　消込値引データを自動作成する　チェックボックス。

自動作成させる場合は消込入金額を　￥０円　とした状態でONする。</inlineHelpText>
        <label>￥￥_自動消込チェック</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>消込値引データ</relationshipLabel>
        <relationshipName>NyukinData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消込値引データ</label>
    <nameField>
        <label>消込値引名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>HizukeMaruchiKensaku__c</fullName>
        <formula>&quot; &quot; +

 TEXT( SeikyuKaishuKigen__c )

+ &quot; &quot; + 

RIGHT( TEXT(SeikyuKaishuKigen__c), 5) 

+ &quot; &quot; + 

 SUBSTITUTE(TEXT(SeikyuKaishuKigen__c), &quot;-&quot;, &quot;/&quot;)

+ &quot; &quot; + 

RIGHT( SUBSTITUTE(TEXT(SeikyuKaishuKigen__c), &quot;-&quot;, &quot;/&quot;), 5) 

+ &quot; &quot; + 

 SUBSTITUTE(TEXT(SeikyuKaishuKigen__c), &quot;-&quot;, &quot;&quot;) 

+ &quot; &quot; + 

RIGHT( SUBSTITUTE(TEXT(SeikyuKaishuKigen__c), &quot;-&quot;, &quot;&quot;), 4)

+ &quot; &quot; + 

RIGHT( TEXT(SeikyuKaishuKigen__c), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>ハイフン区切り
例）2016/12/01→2016-12-01
例）2016/12/01→12-01
スラッシュ区切り
例）2016/12/01→2016/12/01
例）2016/12/01→12/01
区切り無
例）2016/12/01→20161201
例）2016/12/01→1201
日付部分
例）2016/12/01→01</inlineHelpText>
        <label>￥￥_日付マルチ検索</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KeshikomiTaishoFlg__c</fullName>
        <formula>AND(
 KekuteiMiKaishuZandaka__c  &lt;&gt; 0,
 SaishuSeikyuKingaku__c &lt;&gt; 0,
  SeikyuKakuteiFlg__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>消込値引登録画面に表示する対象を表す。

ON条件
　売掛確定フラグがON。
　未入金残高が0円以外。
　最終請求金額が0円以外。</inlineHelpText>
        <label>消込登録対象</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KingakuMaruchiKensaku__c</fullName>
        <formula>&quot; &quot; + 

TEXT( FLOOR(SaishuSeikyuKingakuNamachi__c/ 10) * 10  ) 

 + &quot; &quot; + 

TEXT( FLOOR( (SaishuSeikyuKingakuNamachi__c -  KakuteiKaishuNebikiGaku__c ) / 10) * 10  )  + &quot; &quot;

 + &quot; &quot; + 

TEXT( FLOOR(SaishuSeikyuKingakuNamachi__c/ 100) * 100  ) 

 + &quot; &quot; + 

TEXT( FLOOR( (SaishuSeikyuKingakuNamachi__c -  KakuteiKaishuNebikiGaku__c ) / 100) * 100  )  + &quot; &quot;

 + &quot; &quot; + 

TEXT( FLOOR(SaishuSeikyuKingakuNamachi__c/ 1000) * 1000  ) 

 + &quot; &quot; + 

TEXT( FLOOR( (SaishuSeikyuKingakuNamachi__c -  KakuteiKaishuNebikiGaku__c ) / 1000) * 1000  )  + &quot; &quot;

 + &quot; &quot; + 

TEXT( SaishuSeikyuKingakuNamachi__c )

 + &quot; &quot; + 

TEXT( SaishuSeikyuKingakuNamachi__c -  KakuteiKaishuNebikiGaku__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>請求金額　未入金売掛残高　を元に検索するための文字列を出力。

1,000円切り捨て
例）￥25,102　→　25000
例）￥23,243　→　23000
100円切り捨て
例）￥25,102　→　25100
例）￥23,243　→　23200
10円切り捨て
例）￥25,102　→　25100
例）￥23,243　→　23240</inlineHelpText>
        <label>￥￥_金額マルチ検索</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MikomiKaishuNebikiGaku__c</fullName>
        <inlineHelpText>未確定の入金消込（値引）の合計額。</inlineHelpText>
        <label>予定回収値引額</label>
        <summarizedField>KeshikomiData__c.KeshikomiKingaku__c</summarizedField>
        <summaryForeignKey>KeshikomiData__c.UrikakeData__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MikomiMikaishuZandaka__c</fullName>
        <formula>SaishuSeikyuKingaku__c  -  MikomiKaishuNebikiGaku__c</formula>
        <inlineHelpText>確定請求金額 － 予定回収値引</inlineHelpText>
        <label>予定未回収額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SaikenMihasseiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>商品（サービス）の納品前に請求を行う場合にON。トリガによりONされる。
受注データの債権未発生フラグONが集約される。</inlineHelpText>
        <label>先払債権無フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SaishuSeikyuKingaku__c</fullName>
        <formula>IF ( MeisaibetsuZeigakuFlg__c ,
  ZeiKomiGakuKei__c ,
  ShohiZeikomiGaku__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>合計額ベースの消費税か明細ベースの消費税の選択結果。
明細別税額フラグで制御。</inlineHelpText>
        <label>確定請求金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SeikyuJoken__c</fullName>
        <formula>LPAD(TEXT( MONTH(ShimeKikanKara__c) ), 2, &quot;0&quot;) + &quot;月&quot; 

+ &quot; &quot; + 

IF ( SaikenMihasseiFlg__c , &quot;先払&quot;,&quot;後払&quot; ) 

+ &quot; &quot; + 

IF ( TsudoSeikyuFlg__c , &quot;都度&quot;,&quot;締&quot; ) 

+ &quot; &quot; + 

IF ( SeikyuKakuteiFlg__c , IF ( FurikaeSeikyuFlg__c , &quot;振替&quot;,&quot;振込&quot; ) , &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_請求条件</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyuKaishuKigen__c</fullName>
        <description>WFR自動記入</description>
        <inlineHelpText>請求書のお支払い期限に反映。
任意の日付に書き換え可能。

取引サイト月数と回収前倒日数から算出。</inlineHelpText>
        <label>請求回収期日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShimeKikanKara__c</fullName>
        <formula>IF( KahenSeikyuFlg__c, 
 ShimeKikanKaraShudo__c , 

IF( TsudoSeikyuFlg__c, 
 ShimeHizuke__c, 

IF( SeikyuAccount__r.Shimebi__c = 99, 
 DATE( YEAR(ShimeHizuke__c), MONTH(ShimeHizuke__c), 1), 

IF( SeikyuAccount__r.Shimebi__c &lt; DAY( ShimeHizuke__c ),  
 DATE( YEAR(ShimeHizuke__c), MONTH(ShimeHizuke__c), SeikyuAccount__r.Shimebi__c) + 1, 

 IF(
    MONTH(ShimeHizuke__c)==1,
    DATE(YEAR(ShimeHizuke__c)-1,12                                  ,SeikyuAccount__r.Shimebi__c) + 1,
    DATE(YEAR(ShimeHizuke__c)  ,MONTH(ShimeHizuke__c)-1,SeikyuAccount__r.Shimebi__c) + 1
 )

))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売掛データに集計される受注データの計上日範囲。

可変請求ON
　請求起算日（手動）
　
都度請求ON
　請求起算基準日

締日＝９９
　締基準日の月　の　同月　の　初日

締日＜締基準日
　締基準日の月　の　同月　の　締日＋１日

締日≧締基準日
　締基準日の月　の　前月　の　締日＋１日</inlineHelpText>
        <label>請求起算日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShimeKikanMade__c</fullName>
        <formula>IF( KahenSeikyuFlg__c, 
 ShimeKikanMadeShudo__c , 

IF( TsudoSeikyuFlg__c, 
 ShimeHizuke__c, 

IF( SeikyuAccount__r.Shimebi__c = 99, 
 IF(
    MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c&gt;12,
    DATE(YEAR(ShimeKikanKaraNamachi__c)+1,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c-12,1),
    DATE(YEAR(ShimeKikanKaraNamachi__c)  ,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c   ,1)
 )-1
 ,
 IF(
    MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c&gt;12,
    DATE(YEAR(ShimeKikanKaraNamachi__c)+1,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c-12,SeikyuAccount__r.Shimebi__c),
    DATE(YEAR(ShimeKikanKaraNamachi__c)  ,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c   ,SeikyuAccount__r.Shimebi__c)
 )

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売掛データに集計される受注データの計上日範囲。

可変請求ON
　請求締日（手動）
　
都度請求ON
　請求起算基準日

締日＝９９
　締期間から＋締期間月数の月－１ヶ月　の　最終日

締日≠９９
　締期間から＋締期間月数の月　の　締日</inlineHelpText>
        <label>請求締日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TokusokuAlertFlg__c</fullName>
        <formula>AND(
 SeikyuKaishuKigen__c  &lt;  TODAY() ,
 NOT( KaishuKanryoFlg__c ) ,
 KekuteiMiKaishuZandaka__c  &gt;= 1
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>請求入金期限を過ぎ回収完了していない　かつ　先払ではない（債権無フラグOFF）　かつ　未回収残高が￥１円以上　場合にON。</inlineHelpText>
        <label>督促警告フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONされる。トリガによりONされる。
受注データの都度請求フラグONが集約される。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UriageKeijoTsuki__c</fullName>
        <formula>IF ( UriageKakuteiFlg__c ,

IF ( SaikenMihasseiFlg__c ,

TEXT(YEAR(   KaishuKanryoBiNamachi__c ))   +&quot;年&quot;+
IF (4 &lt;= MONTH( KaishuKanryoBiNamachi__c ) , &quot;.&quot;, &quot;&quot;) +
TEXT(MONTH( KaishuKanryoBiNamachi__c )) +&quot;月&quot;
,
TEXT(YEAR(   ShimeKikanMadeNamachi__c ))   +&quot;年&quot;+
IF (4 &lt;= MONTH( ShimeKikanMadeNamachi__c ) , &quot;.&quot;, &quot;&quot;) +
TEXT(MONTH( ShimeKikanMadeNamachi__c )) +&quot;月&quot;

) 
,
TEXT(YEAR(    SeikyuKaishuKigen__c ))   +&quot;年&quot;+
IF (4 &lt;= MONTH( SeikyuKaishuKigen__c ) , &quot;.&quot;, &quot;&quot;) +
TEXT(MONTH( SeikyuKaishuKigen__c )) +&quot;月&quot;

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>先払の場合は、回収完了日。
後払の場合は、締期間の最終日（締期間まで）。</inlineHelpText>
        <label>売上計上月</label>
        <type>Text</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N07_NyukinIkkatsuTourokuController.cls
public without sharing class N07_NyukinIkkatsuTourokuController {

    //現在のガバナリミットSystem.limits.getLimitQueryRowsを取得する。
    Integer limitQueryRows = System.limits.getLimitQueryRows()/3;
    
    /** プロパティ */
    // 画面表示用データ
    public List<AccUrikake> accUrikakeList{get; set;}
    
    //ページ側絞込文字列値
    public String RefineString { get; set; }

    //ページ側絞込数値
    public String RefineValue { get; set; }
    
    //ページ側絞込日付
    public String RefineDate { get; set; }
    
    //ページ側先払フラグ値
    public Boolean SakiBarai { get; set; }

    //ページ側都度フラグ値
    public Boolean TsudoBarai { get; set; }

    //ページ側締めフラグ値
    public Boolean ShimeBarai { get; set; }

    //ページ側充当フラグ値
    public Boolean JutoTaisho { get; set; }

    //ページ側督促フラグ値
    public Boolean TokusokuTaisho { get; set; }

    //保存ボタン表示フラグ値
    public Boolean SaveOk { get; set; }

    // コンストラクタ
    public N07_NyukinIkkatsuTourokuController(){
        
    }
    
    /**
     * 画面描画時処理
     */
    public pageReference init(){

        //処理対象の取引先一覧
        List<Account> accList = new List<Account>();
        //絞込検索用の文字列
        String likeStringSearchKey;

        // 名称マルチ検索が空白であれば取引先を全件取得
        if(RefineString == null){
            accList = [SELECT 
                       Id, Name, MinyukinZandakaSokei__c, SeishikiMeisho__c, 
                       NyukinSaidaiGaku__c, NyukinSaishoGaku__c, NyukinZengaku__c, 
                       TokusokuFlg__c, MikakuteiJutoFlg__c
                       FROM Account
                       WHERE SeikyuTaishoFlg__c = true
                       ORDER BY Name ASC LIMIT :limitQueryRows];            
        //名称マルチ検索が入力済ならば取引先を絞込取得
        }else{
            likeStringSearchKey = '%' + RefineString + '%';
            accList = [SELECT 
                       Id, Name, MinyukinZandakaSokei__c, SeishikiMeisho__c, 
                       NyukinSaidaiGaku__c, NyukinSaishoGaku__c, NyukinZengaku__c, 
                       TokusokuFlg__c, MikakuteiJutoFlg__c, 
                       MeishoMaruchiKensaku__c 
                       FROM Account
                       WHERE MeishoMaruchiKensaku__c LIKE: likeStringSearchKey
                       AND SeikyuTaishoFlg__c = true
                       ORDER BY Name ASC LIMIT :limitQueryRows];                        
        }

        // 取得した取引先一覧から処理対象のIDのリストに絞込
        List<Id> accIdList = new List<Id>();
        for(Account acc :accList){
            //督促対象かつ充当対象の場合
            if(TokusokuTaisho && JutoTaisho){
                if(acc.TokusokuFlg__c && acc.MikakuteiJutoFlg__c){
                    //処理対象の取引先としてID追加
                    accIdList.add(acc.Id);
                }
            }
            //督促対象の場合
            else if(TokusokuTaisho){
                if(acc.TokusokuFlg__c){
                    //処理対象の取引先としてID追加
                    accIdList.add(acc.Id);
                }
            }
            //充当対象の場合
            else if(JutoTaisho){
                if(acc.MikakuteiJutoFlg__c){
                    //処理対象の取引先としてID追加
                    accIdList.add(acc.Id);
                }
            }
            //絞り込まない（督促でも充当でもない）場合
            else if(!TokusokuTaisho && !JutoTaisho){
                //処理対象の取引先としてID追加
                accIdList.add(acc.Id);
            }
        }

        //処理対象の売掛データ一覧
        List<UrikakeData__c> urikakeFullList = new List<UrikakeData__c>();
        //金額絞込検索用の文字列
        String likeValueSearchKey;
        //期日絞込検索用の文字列
        String likeDateSearchKey;

        // 金額と期日マルチ検索が両方入力済であれば消込対象フラグtrueの売掛データを絞込取得
        if( RefineValue.length() > 0 && RefineDate.length() > 0 ){
            likeValueSearchKey = '%' + RefineValue+ '%';
            likeDateSearchKey = '%' + RefineDate+ '%';
            urikakeFullList = [SELECT 
                               Id, Name, UriageKeijoTsuki__c, SeikyuKaishuKigen__c, 
                               SaikenMihasseiFlg__c, MikomiMikaishuZandaka__c, 
                               SeikyuAccount__c, SeikyuJoken__c, ShimeKikanKara__c, ShimeKikanMade__c, SaishuSeikyuKingaku__c, MikomiKaishuNebikiGaku__c, TsudoSeikyuFlg__c, TokusokuAlertFlg__c , KingakuMaruchiKensaku__c, HizukeMaruchiKensaku__c
                               FROM UrikakeData__c 
                               WHERE KingakuMaruchiKensaku__c LIKE: likeValueSearchKey
                               AND HizukeMaruchiKensaku__c LIKE: likeDateSearchKey
                               AND SeikyuAccount__c IN :accIdList 
                               AND KeshikomiTaishoFlg__c = true
                               ORDER BY SeikyuKaishuKigen__c ASC, ShimeKikanKara__c ASC, ShimeKikanMade__c ASC LIMIT :limitQueryRows];
        // 金額マルチ検索が入力済ならば消込対象フラグtrueの売掛データを絞込取得
        }else if( RefineValue.length() > 0 && RefineDate.length() == 0 ){
            likeValueSearchKey = '%' + RefineValue+ '%';
            urikakeFullList = [SELECT 
                               Id, Name, UriageKeijoTsuki__c, SeikyuKaishuKigen__c, 
                               SaikenMihasseiFlg__c, MikomiMikaishuZandaka__c, 
                               SeikyuAccount__c, SeikyuJoken__c, ShimeKikanKara__c, ShimeKikanMade__c, SaishuSeikyuKingaku__c, MikomiKaishuNebikiGaku__c, TsudoSeikyuFlg__c, TokusokuAlertFlg__c, KingakuMaruchiKensaku__c, HizukeMaruchiKensaku__c
                               FROM UrikakeData__c 
                               WHERE KingakuMaruchiKensaku__c LIKE: likeValueSearchKey
                               AND SeikyuAccount__c IN :accIdList 
                               AND KeshikomiTaishoFlg__c = true
                               ORDER BY SeikyuKaishuKigen__c ASC, ShimeKikanKara__c ASC, ShimeKikanMade__c ASC LIMIT :limitQueryRows];
        // 期日マルチ検索が入力済ならば消込対象フラグtrueの売掛データを絞込取得
        }else if( RefineValue.length() == 0 && RefineDate.length() > 0 ){
            likeDateSearchKey = '%' + RefineDate+ '%';
            urikakeFullList = [SELECT 
                               Id, Name, UriageKeijoTsuki__c, SeikyuKaishuKigen__c, 
                               SaikenMihasseiFlg__c, MikomiMikaishuZandaka__c, 
                               SeikyuAccount__c, SeikyuJoken__c, ShimeKikanKara__c, ShimeKikanMade__c, SaishuSeikyuKingaku__c, MikomiKaishuNebikiGaku__c, TsudoSeikyuFlg__c, TokusokuAlertFlg__c, KingakuMaruchiKensaku__c, HizukeMaruchiKensaku__c
                               FROM UrikakeData__c 
                               WHERE HizukeMaruchiKensaku__c LIKE: likeDateSearchKey
                               AND SeikyuAccount__c IN :accIdList 
                               AND KeshikomiTaishoFlg__c = true
                               ORDER BY SeikyuKaishuKigen__c ASC, ShimeKikanKara__c ASC, ShimeKikanMade__c ASC LIMIT :limitQueryRows];
        // 金額と期日マルチ検索が両方空白（入力が無い）であれば消込対象フラグtrueの売掛データを全件取得
        }else{
            urikakeFullList = [SELECT 
                               Id, Name, UriageKeijoTsuki__c, SeikyuKaishuKigen__c, 
                               SaikenMihasseiFlg__c, MikomiMikaishuZandaka__c, 
                               SeikyuAccount__c, SeikyuJoken__c, ShimeKikanKara__c, ShimeKikanMade__c, SaishuSeikyuKingaku__c, MikomiKaishuNebikiGaku__c, TsudoSeikyuFlg__c, TokusokuAlertFlg__c, KingakuMaruchiKensaku__c, HizukeMaruchiKensaku__c
                               FROM UrikakeData__c 
                               WHERE SeikyuAccount__c IN :accIdList 
                               AND KeshikomiTaishoFlg__c = true
                               ORDER BY SeikyuKaishuKigen__c ASC, ShimeKikanKara__c ASC, ShimeKikanMade__c ASC LIMIT :limitQueryRows];
        }

        // 売掛データのIdのリストを作成
        List<Id> urikakeIdList = new List<Id>();

        // 売掛データのリストを作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();

        // 売掛データの絞込リストを作成
        List<UrikakeData__c> urikakeRefineList = new List<UrikakeData__c>();

        // 売掛データを順に処理し督促の絞込を適用
        for(UrikakeData__c urikakeFull :urikakeFullList){
            //督促に絞る場合
            if(TokusokuTaisho){
                if(urikakeFull.TokusokuAlertFlg__c){
                    urikakeRefineList.add(urikakeFull);
                }
            }
            //絞らない場合
            else{
                urikakeRefineList.add(urikakeFull);
            }
        }

        // 売掛データを順に処理し先払/都度/締の絞込を適用
        for(UrikakeData__c urikakeRefine :urikakeRefineList){

            //全件
            if(!ShimeBarai && !TsudoBarai && !SakiBarai){
                urikakeIdList.add(urikakeRefine.Id);
                urikakeList.add(urikakeRefine);
            }
            //締払
            else if(ShimeBarai){
                if(!urikakeRefine.TsudoSeikyuFlg__c){
		            urikakeIdList.add(urikakeRefine.Id);
		            urikakeList.add(urikakeRefine);
                }
            }
            //都度先払
            else if(TsudoBarai && SakiBarai){
                if(urikakeRefine.TsudoSeikyuFlg__c && urikakeRefine.SaikenMihasseiFlg__c){
                    urikakeIdList.add(urikakeRefine.Id);
                    urikakeList.add(urikakeRefine);
                }
            }
            //都度
            else if(TsudoBarai){
                if(urikakeRefine.TsudoSeikyuFlg__c){
		            urikakeIdList.add(urikakeRefine.Id);
		            urikakeList.add(urikakeRefine);
                }
            }
            //その他全件
            else{
                urikakeIdList.add(urikakeRefine.Id);
                urikakeList.add(urikakeRefine);                
            }
        }

        // 消込データを取得
        List<KeshikomiData__c>keshikomiList = 
            [SELECT Id, SokuKeshikomi__c, KeshikomiKingaku__c, KeshikomiKakuninbi__c, Biko__c, UrikakeData__c
             FROM KeshikomiData__c
             WHERE UrikakeData__c IN :urikakeIdList
             ORDER BY KeshikomiKakuninbi__c,Biko__c,KeshikomiKingaku__c  DESC LIMIT :limitQueryRows];
        
        accUrikakeList = new List<AccUrikake>();

        List<AccUrikake> tmpAccUrikakeList = new List<AccUrikake>();
        
        for(Account accItem :accList){
            // 取引先　一時保存変数
            AccUrikake tmpAU = new AccUrikake();
            tmpAU.acc = accItem;
            // 取引先毎の売掛のリスト
            List<UrikakeKeshikomi> UNList = new List<UrikakeKeshikomi>();
            // 取得した売掛データを全てまわす。
            for(UrikakeData__c urikakeItem :urikakeList){
                // 取引先が一致する
                if((accItem.Id).equals(urikakeItem.SeikyuAccount__c)){
                    UrikakeKeshikomi tmpUN = new UrikakeKeshikomi();
                    tmpUN.urikake = urikakeItem;
                    // 売掛毎の消込データのリスト
                    List<KeshikomiData__c> tmpKeshikomiList = new List<KeshikomiData__c>();
                    // 取得した消込データ全てをまわす。
                    for(KeshikomiData__c keshikomiItem :keshikomiList){
                        // 売掛データが一致する。
                        if((urikakeItem.Id).equals(keshikomiItem.UrikakeData__c)){
                            // 消込データのリストを作成
                            tmpKeshikomiList.add(keshikomiItem);
                        }
                    }
                    // 新規登録用の空の消込データを代入
                    tmpKeshikomiList.add(new KeshikomiData__c(KeshikomiKingaku__c = 0, KeshikomiKakuninbi__c = date.today(), Biko__c = '', UrikakeData__c = urikakeItem.Id));
                    tmpUN.keshikomi = tmpKeshikomiList;
                    // 売掛データと消込データリストのリストを作成
                    UNList.add(tmpUN);
                }
                tmpAU.UrikakeKeshikomi = UNList;
            }
            tmpAccUrikakeList.add(tmpAU);
        }
        
        if(!urikakeList.isEmpty()){
            // リストから消込対象=trueの売掛データのみ抽出
            for(AccUrikake item :tmpAccUrikakeList){
                if(item.UrikakeKeshikomi.size() != 0){
                    accUrikakeList.add(item);
                }
            }
        }

        return null;
    }
    
    /**
     * 保存ボタンを押したときの処理
     */
    public pageReference saveButtonAll(){
        //保存処理
        allSave();
        init();
        return null;
    }

    /**
     * 名称・日付・金額絞込ボタンを押したときの処理
     */
    public pageReference initButton(){
        // 画面再描画
        SaveOk = true;
        init();
        return null;
    }

    /**
     * 全件ボタンを押したときの処理
     */
    public pageReference initButtonFull(){
        SaveOk = true;
        RefineString = '';
        RefineValue = '';
        RefineDate = '';
        ShimeBarai = False;
        TsudoBarai = False;
        SakiBarai = False;
        JutoTaisho = False;
        TokusokuTaisho = False;
        init();
        return null;
    }

    /**
     * 充当絞込ボタンを押したときの処理
     */
    public pageReference initButtonJutoTaisho(){
        SaveOk = true;
        JutoTaisho = True;
        init();
        return null;
    }

    /**
     * 督促絞込ボタンを押したときの処理
     */
    public pageReference initButtonTokusokuTaisho(){
        SaveOk = true;
        TokusokuTaisho = True;
        init();
        return null;
    }

    /**
     * 締払絞込ボタンを押したときの処理
     */
    public pageReference initButtonShimeBarai(){
        SaveOk = true;
        ShimeBarai = True;
        TsudoBarai = False;
        SakiBarai = False;
        init();
        return null;
    }

    /**
     * 都度絞込ボタンを押したときの処理
     */
    public pageReference initButtonTsudoBarai(){
        SaveOk = true;
        TsudoBarai = True;
        ShimeBarai = False;
        init();
        return null;
    }

    /**
     * 先払い絞込ボタンを押したときの処理
     */
    public pageReference initButtonSakiBarai(){
        SaveOk = true;
        SakiBarai = True;
        TsudoBarai = True;
        ShimeBarai = False;
        init();
        return null;
    }


    /**
     * 画面の入力内容を保存する処理（全体）
     */
    private void allSave(){
        
        // 更新追加対象消込データリスト
        List<KeshikomiData__c> upsKeshikomiData = new List<KeshikomiData__c>();
        
        if(!accUrikakeList.isEmpty()){
            
            for(AccUrikake accItem :accUrikakeList){
                for(UrikakeKeshikomi urikakeItem :accItem.UrikakeKeshikomi){
                    for(KeshikomiData__c keshikomiItem :urikakeItem.keshikomi){
                        // 消込データの一番下の行の扱い
                        if(keshikomiItem.id == null){
                            // 金額が0以外または消込チェックONの場合のみ追加の対象にする
                            if(keshikomiItem.KeshikomiKingaku__c != 0 || keshikomiItem.SokuKeshikomi__c ){
                                upsKeshikomiData.add(keshikomiItem);
                            }
                        }else{
                            // 一番下の行以外は無条件で更新/追加対象リストに設定
                            upsKeshikomiData.add(keshikomiItem);
                        }
                    }
                }
            }
            
            // 配列が空白でなければアップサート
            if(!upsKeshikomiData.isEmpty()){
                upsert upsKeshikomiData;
            }
            
        }

    }

    /**
     * 売掛データと（消込データのリスト）
     */
    public class UrikakeKeshikomi{
        public UrikakeData__c urikake{get; set;}
        public List<KeshikomiData__c> keshikomi{get; set;}
        
        /** コンストラクタ */
        public UrikakeKeshikomi(){
            urikake = new UrikakeData__c();
            keshikomi = new List<KeshikomiData__c>();
        }
    }

    /**
     * 取引先と（売掛データと（消込データのリスト）のリスト）
     */
    public class AccUrikake{
        public Account acc{get; set;}
        public List<UrikakeKeshikomi> UrikakeKeshikomi{get; set;}
        
        /** コンストラクタ */
        public AccUrikake(){
            acc = new Account(); 
        }
    }
}