src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KobetsuHikiateSaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>標準の引当先以外から受注引当を行うばあい指定。
選択がない場合は標準引当先フラグONの倉庫（取引先マスタ）が割り当てられる。
通常は受注データの受注先から個別引当先が選択される。
受注データの納品先が設定される場合は納品先から個別引当先が選択される。</inlineHelpText>
        <label>個別引当先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>取引先 (優先引当先)</relationshipLabel>
        <relationshipName>YusenHikiateSakis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LotKonzaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>受注の在庫引当処理で複数の在庫データ（パレット/ロット）を混在させる動きを標準とする場合チェックONにする。通常OFF。（ON例：直営店）</inlineHelpText>
        <label>ロット混在フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShomiKigenKonzaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>受注の在庫引当処理で複数の賞味期限を混在させる動きを標準とする場合チェックONにする。通常OFF。（ON例：直営店）</inlineHelpText>
        <label>消費期限混在フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SuryoYusenFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>賞味期限の早く切れる在庫からではなく個数の少ない在庫データから優先して引き当てる動きを標準とする場合チェックON。通常OFF。（ON例：直営店）</inlineHelpText>
        <label>小口在庫優先フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YusenHikiateSakiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>標準の受注引当を行う在庫先（引当先）の場合ON。
システム全体で１レコードのみON設定とする前提。
複数レコードに指定した場合はIDの若番のみが有効。</inlineHelpText>
        <label>優先引当先フラグ</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigenKakuhoNissu__c</fullName>
        <description>商品資材マスタ　の　販売管理期限日数　が　標準値</description>
        <inlineHelpText>出荷時に担保する必要のある消費期限の期間。
例：販売管理期限など。
例：納品管理期限など。</inlineHelpText>
        <label>消費期限確保日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>HikiateKanryoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>全ての商品の引当に成功した場合にON。
引当解除と再引当を行う場合は　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当成功完了</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>引当可能フラグON　かつ　当フラグ　ON　で在庫データの引当を試みます。
引当解除と再引当を行う場合は　引当成功完了　OFF　かつ　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当即時確定</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LotKonzaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>複数の在庫データ（パレット/ユニット）を引き当てる事を許可します。
伝票の明細に同じ賞味期限の行が複数表記される可能性があります。</inlineHelpText>
        <label>ユニット混在フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>受注確定フラグOFFの場合に、売掛データの締期間を検索する日付。

出荷引当の試行時に、入出庫データの賞味期限を検索する日付。</inlineHelpText>
        <label>納品請求日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShomiKigenKonzaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>複数の賞味期限を混在した引当を許可します。
伝票の明細に複数の賞味期限の行が複数表記される可能性があります。</inlineHelpText>
        <label>消費期限混在フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SuryoYusenFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェックがない場合は賞味期限が近い在庫優先となります。</inlineHelpText>
        <label>小口在庫優先フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ZaikoHikiateSaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷引当先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>JuchuData_ZaikoHikiateSaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JuchuSuryoPC__c</fullName>
        <label>PC数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NohinSuryo__c</fullName>
        <label>納品数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShomiKigenNissu__c</fullName>
        <inlineHelpText>製品が製造完了後に正常に消費（使用)出来る期間。
例：食品であれば賞味期限など。
例：機械部品であれば保証期間など。</inlineHelpText>
        <label>消費期限日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>JuchuMeisaiSaidaiTorokusu__c</fullName>
        <defaultValue>35</defaultValue>
        <label>受注明細最大登録数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NyukoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>実在庫状態以降。オフの場合は予約データ（未入庫）となる。</description>
        <inlineHelpText>実際に入庫を確認したことを表す。オフの場合は確認未実施となる。</inlineHelpText>
        <label>入庫フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigen__c</fullName>
        <label>消費期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ZaikoSuryo__c</fullName>
        <label>在庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zaikobasho__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>場所</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>入出庫データ</relationshipLabel>
        <relationshipName>ZaikoData_Zaikobasho</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Z02_JuchuSyukoRendoLogicTest.cls
@isTest
private class Z02_JuchuSyukoRendoLogicTest {

    // パターンA 在庫有り
    static testMethod void myUnitTest1() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1',AccountTankaMHuyouFlg__c = true);
        insert acc1;
        Account acc2 = new Account(name = 'テスト倉庫A');
        insert acc2;
        Account acc3 = new Account(name = 'テスト倉庫B', YusenHikiateSakiFlg__c = true);
        insert acc3;

        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko3 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc3.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko4 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc3.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        insert zaiko3;
        insert zaiko4;

        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        

        Test.startTest();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);

        //パターンA
        juchu1.ShomiKigenKonzaiFlg__c = true;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = false;
        juchu1.JuchuKakuteiFlg__c = true;
        update juchu1;

        //個別引当先を設定
        acc1.KobetsuHikiateSaki__c = acc2.Id;
        update acc1;

        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;

        //パターンB
        juchu1.ShomiKigenKonzaiFlg__c = true;
        juchu1.LotKonzaiFlg__c = false;
        juchu1.SuryoYusenFlg__c  = false;
        juchu1.JuchuKakuteiFlg__c = true;
        update juchu1;

        //個別引当先を解除
        acc1.KobetsuHikiateSaki__c = null;
        update acc1;

        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;

        //パターンC
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = true;
        juchu1.JuchuKakuteiFlg__c = true;        
        update juchu1;
        
        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;


        Test.stopTest();
    }
    
    // パターンA 在庫なし
    static testMethod void myUnitTest2() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc2 = new Account(name = 'テスト倉庫', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        insert acc2;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, zaikoHikiateSaki__c = acc2.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 5, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 5, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        
        Test.startTest();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = true;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        
        try{
            update juchu1;
        }catch(exception e){
            
        }

        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;

        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = true;
        juchu1.LotKonzaiFlg__c = false;
        juchu1.JuchuKakuteiFlg__c = true;
        
        try{
            update juchu1;
        }catch(exception e){
            
        }

        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;        

        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = true;
        juchu1.LotKonzaiFlg__c = false;
        juchu1.JuchuKakuteiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = true;
        
        try{
            update juchu1;
        }catch(exception e){
            
        }
        
        Test.stopTest();
    }
    
    // パターンB 在庫有り
    static testMethod void myUnitTest3() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc2 = new Account(name = 'テスト倉庫', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        insert acc2;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, zaikoHikiateSaki__c = acc2.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 1, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        ZaikoData__c zaiko3 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        insert zaiko3;
        
        Test.startTest();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        
        update juchu1;
                
        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;

        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = true;

        update juchu1;

        Test.stopTest();
    }
    
    // パターンB 在庫なし
    static testMethod void myUnitTest4() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc2 = new Account(name = 'テスト倉庫', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        insert acc2;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, zaikoHikiateSaki__c = acc2.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 14, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 2, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        ZaikoData__c zaiko3 = new ZaikoData__c(ZaikoSuryo__c = 12, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        insert zaiko3;
        
        Test.startTest();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        
        try{
            update juchu1;
        }catch(Exception e){
            
        }

        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;
                
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = true;
        
        try{
            update juchu1;
        }catch(Exception e){
            
        }

        Test.stopTest();
    }
    
    // パターンC 在庫あり
    static testMethod void myUnitTest5() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc2 = new Account(name = 'テスト倉庫', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        insert acc2;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, zaikoHikiateSaki__c = acc2.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 5, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 5, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        ZaikoData__c zaiko3 = new ZaikoData__c(ZaikoSuryo__c = 15, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        insert zaiko3;
        
        Test.startTest();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = false;
        juchu1.JuchuKakuteiFlg__c = true;
        
        update juchu1;

        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;

        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = false;
        juchu1.JuchuKakuteiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = true;
        
        update juchu1;        
        
        Test.stopTest();
    }

    // 一度に複数の受注データを更新するパターン
    static testMethod void myUnitTest6() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc2 = new Account(name = 'テスト倉庫', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc3 = new Account(name = '株式会社テスト2', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        insert acc2;
        insert acc3;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc3.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        UrikakeData__c Urikake2 = new UrikakeData__c(name = acc3.Name, SeikyuAccount__c = acc3.Id);
        insert urikake1;
        insert urikake2;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, zaikoHikiateSaki__c = acc2.Id);
        JuchuData__c juchu2 = new JuchuData__c(UrikakeData__c = urikake2.id, name = urikake2.Name, zaikoHikiateSaki__c = acc2.Id);
        insert juchu1;
        insert juchu2;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        JuchuMeisaiData__c meisai2 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu2.name, JuchuData__c = juchu2.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        insert meisai2;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 5, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 5, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        ZaikoData__c zaiko3 = new ZaikoData__c(ZaikoSuryo__c = 150, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        insert zaiko3;
        
        Test.startTest();
        
        List<JuchuData__c> updJuchuList = new List<JuchuData__c>();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = false;
        juchu1.JuchuKakuteiFlg__c = true;
        updJuchuList.add(juchu1);
        
        juchu2.NohinYoteibi__c = Date.today().addDays(1);
        juchu2.ShomiKigenKonzaiFlg__c = false;
        juchu2.LotKonzaiFlg__c = false;
        juchu2.JuchuKakuteiFlg__c = true;
        updJuchuList.add(juchu2);
        
        update updJuchuList;
        
        Test.stopTest();
    }
    
    // パターンB 在庫有り （数量が近い在庫を優先）
    static testMethod void myUnitTest7() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        Account acc2 = new Account(name = 'テスト倉庫', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        insert acc2;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, zaikoHikiateSaki__c = acc2.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryoPC__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 1, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(120), NyukoFlg__c = true);
        ZaikoData__c zaiko2 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        ZaikoData__c zaiko3 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc2.Id, ShomiKigen__c = Date.today().addDays(121), NyukoFlg__c = true);
        insert zaiko1;
        insert zaiko2;
        insert zaiko3;
        
        Test.startTest();
        
        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        
        update juchu1;
                
        juchu1.HikiateKanryoFlg__c = false;
        update juchu1;

        juchu1.NohinYoteibi__c = Date.today().addDays(1);
        juchu1.ShomiKigenKonzaiFlg__c = false;
        juchu1.LotKonzaiFlg__c = true;
        juchu1.JuchuKakuteiFlg__c = true;
        juchu1.SuryoYusenFlg__c  = true;
        
        update juchu1;

        Test.stopTest();
    }
    
}