src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchusakiChofukuJogaiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>受注明細データの登録時に登録済みの商品を確認するフラグ。

受注データ単位で重複確認する場合OFF。
取引先の受注データ全体で重複を確認する場合ON。</inlineHelpText>
        <label>受注先重複確認モード</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigenKakuhoNissu__c</fullName>
        <description>商品資材マスタ　の　販売管理期限日数　が　標準値</description>
        <inlineHelpText>出荷時に担保する必要のある消費期限の期間。
例：販売管理期限など。
例：納品管理期限など。</inlineHelpText>
        <label>消費期限確保日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>JuchusakiChofukuJogaiFlg__c</fullName>
        <formula>Juchusaki__r.JuchusakiChofukuJogaiFlg__c</formula>
        <inlineHelpText>受注先の受注先重複除外モードを反映。

受注明細データの登録時に受注先全体で重複した商品資材マスタの明細登録を禁止する場合ON。 
受注データ単位で重複禁止する場合OFF。</inlineHelpText>
        <label>￥￥_受注先重複除外モード</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShomiKigenNissu__c</fullName>
        <inlineHelpText>製品が製造完了後に正常に消費（使用)出来る期間。
例：食品であれば賞味期限など。
例：機械部品であれば保証期間など。</inlineHelpText>
        <label>消費期限日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>JuchuMeisaiIkkatsuTsuikaJogen__c</fullName>
        <defaultValue>35</defaultValue>
        <label>受注明細一括追加上限</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JuchuMeisaiSaidaiTorokusu__c</fullName>
        <defaultValue>35</defaultValue>
        <label>受注明細最大登録数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShimeHizuke__c</fullName>
        <inlineHelpText>締め期間算出用の基準となる日付。

本日付を含む形で締期間（請求起算日～請求締日）が算出される。</inlineHelpText>
        <label>請求起算基準日</label>
        <type>Date</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J02_ShohinShizaiMControllerExtensionTest.cls
@isTest
private class J02_ShohinShizaiMControllerExtensionTest {

    // 受注データボタンから遷移するパターン
    static testMethod void myUnitTest1() {

        // 請求書明細最大行数
        SystemParam__c SysParam = SystemParam__c.getOrgDefaults();
        SysParam.JuchuMeisaiIkkatsuTsuikaJogen__c = 35;
        insert SysParam;

        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品1'));
        insert shohinList;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true, JuchusakiChofukuJogaiFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> UrikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = accList[0].Name, SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        // 受注データ作成
        List<JuchuData__c> juchuList = new List<JuchuData__c>();
        juchuList.add(new JuchuData__c(UrikakeData__c = urikakeList[0].id, name = urikakeList[0].Name));
        insert juchuList;
        
        Test.startTest();
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ShohinShizaiM__c'));
        // 選択するレコードを設定
        ssc.setSelected(shohinList);
        ApexPages.currentPage().getParameters().put('accountId', 'null');
        ApexPages.currentPage().getParameters().put('juchuId', juchuList[0].id);
        J02_ShohinShizaiMControllerExtension extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();
        
        Test.stopTest();
    }
    
    // 取引先データボタンから遷移するパターン（売掛データなし）
    static testMethod void myUnitTest2() {

        // 請求書明細最大行数
        SystemParam__c SysParam = SystemParam__c.getOrgDefaults();
        SysParam.JuchuMeisaiIkkatsuTsuikaJogen__c = 35;
        insert SysParam;

        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品1'));
        insert shohinList;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        Test.startTest();
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ShohinShizaiM__c'));
        // 選択するレコードを設定
        ssc.setSelected(shohinList);
        ApexPages.currentPage().getParameters().put('accountId', accList[0].Id);
        ApexPages.currentPage().getParameters().put('juchuId', 'null');
        J02_ShohinShizaiMControllerExtension extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();
        
        Test.stopTest();
    }

    
    // 取引先データボタンから遷移するパターン（売掛データあり）
    static testMethod void myUnitTest3() {

        // 請求書明細最大行数
        SystemParam__c SysParam = SystemParam__c.getOrgDefaults();
        SysParam.JuchuMeisaiIkkatsuTsuikaJogen__c = 35;
        insert SysParam;

        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品1'));
        insert shohinList;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        // 売掛データ作成
        List<UrikakeData__c> UrikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = accList[0].Name, SeikyuAccount__c = accList[0].Id, ShimeHizuke__c = Date.today()));
        insert urikakeList;
        
        Test.startTest();
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ShohinShizaiM__c'));
        // 選択するレコードを設定
        ssc.setSelected(shohinList);
        ApexPages.currentPage().getParameters().put('accountId', accList[0].Id);
        ApexPages.currentPage().getParameters().put('juchuId', 'null');
        J02_ShohinShizaiMControllerExtension extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();
        
        Test.stopTest();
    }
    
    // 取引先データボタンから遷移するパターン（都度請求の顧客）
    static testMethod void myUnitTest4() {

        // 請求書明細最大行数
        SystemParam__c SysParam = SystemParam__c.getOrgDefaults();
        SysParam.JuchuMeisaiIkkatsuTsuikaJogen__c = 35;
        insert SysParam;

        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        shohinList.add(new ShohinShizaiM__c(name = 'テスト商品1'));
        insert shohinList;
        
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = true));
        insert accList;
        
        Test.startTest();
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ShohinShizaiM__c'));
        // 選択するレコードを設定
        ssc.setSelected(shohinList);
        ApexPages.currentPage().getParameters().put('accountId', accList[0].Id);
        ApexPages.currentPage().getParameters().put('juchuId', 'null');
        J02_ShohinShizaiMControllerExtension extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();
        
        Test.stopTest();
    }
    
    // 取引先単価マスタが存在しないパターンと選択した商品が既に登録されている場合
    static testMethod void myUnitTest5() {

        // 請求書明細最大行数
        SystemParam__c SysParam = SystemParam__c.getOrgDefaults();
        SysParam.JuchuMeisaiIkkatsuTsuikaJogen__c = 35;
        SysParam.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert SysParam;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        insert shohin1;
        insert shohin2;
        
        List<ShohinShizaiM__c> shohinList1 = new List<ShohinShizaiM__c>();
        shohinList1.add(shohin1);
        List<ShohinShizaiM__c> shohinList2 = new List<ShohinShizaiM__c>();
        shohinList2.add(shohin1);
        shohinList2.add(shohin2);
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 15, AccountTankaMHuyouFlg__c = false, JuchusakiChofukuJogaiFlg__c = true);
        insert acc1;

        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10);
        insert tanka1;

        Test.startTest();

        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ShohinShizaiM__c'));
        // 選択するレコードを設定
        ssc.setSelected(shohinList1);
        ApexPages.currentPage().getParameters().put('accountId', acc1.Id);
        ApexPages.currentPage().getParameters().put('juchuId', 'null');
        J02_ShohinShizaiMControllerExtension extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();
        
        // 選択するレコードを設定
        ssc.setSelected(shohinList2);
        ApexPages.currentPage().getParameters().put('accountId', acc1.Id);
        ApexPages.currentPage().getParameters().put('juchuId', 'null');
        extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();

        // 選択するレコードを設定
        ssc.setSelected(shohinList2);
        ApexPages.currentPage().getParameters().put('accountId', 'null');
        JuchuData__c juchu = [SELECT ID FROM JuchuData__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('juchuId', juchu.Id);
        extension = new J02_ShohinShizaiMControllerExtension(ssc);
        
        extension.init();
        ApexPages.currentPage().getParameters().put('retUrl', 'hogeaccountIdhoge');
        extension.ikkatsuHensyuButton();
        
        Test.stopTest();

    }
}