src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求先の取引先商品マスタの有無に寄らず全ての商品を受注登録可能にする場合チェックONにする。
請求先を他にもつ得意先の場合は請求先のチェックONにする。
通常OFF。（ON例：個人客）</inlineHelpText>
        <label>取引先条件マスタ不要</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kijitsu__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの回収期日に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>期日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shimebi__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>売掛/買掛データの締め期間に反映

20＝20日
25＝25日
99＝末日</inlineHelpText>
        <label>締日</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountTankaM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTankaM_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>AccountTankaM_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigenKakuhoNissu__c</fullName>
        <description>商品資材マスタ　の　販売管理期限日数　が　標準値</description>
        <inlineHelpText>出荷時に担保する必要のある消費期限の期間。
例：販売管理期限など。
例：納品管理期限など。</inlineHelpText>
        <label>消費期限確保日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanKara__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>適用期間から</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TekiyoKikanMade__c</fullName>
        <defaultValue>TODAY()  + 36500</defaultValue>
        <label>適用期間まで</label>
        <type>Date</type>
    </fields>
    <label>取引条件マスタ</label>
    <nameField>
        <displayFormat>取引条件-{0000000000}</displayFormat>
        <label>取引条件番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuUriageKakuteibi__c</fullName>
        <inlineHelpText>受注確定フラグONの場合に、売掛データの締期間を検索する日付。</inlineHelpText>
        <label>請求基準日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Juchusaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注先店舗</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>受注出荷データ (受注先)</relationshipLabel>
        <relationshipName>JuchuData_Juchusaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JuchuSuryo__c</fullName>
        <label>受注数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NohinSuryo__c</fullName>
        <label>納品数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>AccountTankaMHuyouFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有り　で　本商品は取引先単価マスタを持たない取引先でも受注登録可能と成ります。
通常は備品などをチェック有りにします。</inlineHelpText>
        <label>取引先条件不要フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShomiKigenNissu__c</fullName>
        <inlineHelpText>製品が製造完了後に正常に消費（使用)出来る期間。
例：食品であれば賞味期限など。
例：機械部品であれば保証期間など。</inlineHelpText>
        <label>消費期限日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>JuchuMeisaiSaidaiTorokusu__c</fullName>
        <defaultValue>35</defaultValue>
        <label>受注明細最大登録数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J05_NohinKakakuRendoLogicTest.cls
@isTest
private class J05_NohinKakakuRendoLogicTest {
    // 正常：受注明細更新時、取引先マスタが存在する。
    static testMethod void myUnitTest1() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        insert shohin1;
        insert shohin2;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99, AccountTankaMHuyouFlg__c = false);
        insert acc1;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin2.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        insert tanka1;
        insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, Juchusaki__c = acc1.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryo__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        Test.startTest();
        
        meisai1.ShohinShizaiM__c = shohin2.Id;
        update meisai1;
        
        Test.stopTest();
    }
        
    // エラー：受注明細更新時、取引先単価マスタが存在しない
    static testMethod void myUnitTest2() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        insert shohin1;
        insert shohin2;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99, AccountTankaMHuyouFlg__c = false);
        insert acc1;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        //AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin2.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        insert tanka1;
        //insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, Juchusaki__c = acc1.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryo__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        Test.startTest();
        
        meisai1.ShohinShizaiM__c = shohin2.Id;

        try{
            update meisai1;
        }catch(Exception e){
            system.debug('エラーが発生してますよ。正しい動作ですよ。');
        }
        
        Test.stopTest();
    }
    
    // エラー：受注明細新規作成時、取引先単価マスタが存在しない
    static testMethod void myUnitTest3() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        insert shohin1;
        insert shohin2;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99, AccountTankaMHuyouFlg__c = false);
        insert acc1;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin2.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        insert tanka1;
        insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, Juchusaki__c = acc1.Id);
        insert juchu1;
        
        Test.startTest();
        
        try{
            // 受注明細データ作成
            JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryo__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
            insert meisai1;
        }catch(Exception e){
            system.debug('エラーが発生してますよ。正しい動作ですよ。');
        }
        
        Test.stopTest();
    }
    
    // 正常：受注データ更新時、取引先単価マスタが存在する
    static testMethod void myUnitTest4() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        //ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        insert shohin1;
        //insert shohin2;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99, AccountTankaMHuyouFlg__c = false);
        insert acc1;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2115, 12, 31));
        AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(2116, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        insert tanka1;
        insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, Juchusaki__c = acc1.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryo__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        Test.startTest();
        
        juchu1.JuchuUriageKakuteiBi__c = date.newInstance(2116, 1, 1);
        update juchu1;
        
        Test.stopTest();
    }
    
    // エラー：受注データ更新時、取引先単価マスタが存在しない
    static testMethod void myUnitTest5() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        //ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = false);
        insert shohin1;
        //insert shohin2;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99, AccountTankaMHuyouFlg__c = false);
        insert acc1;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2115, 12, 31));
        //AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(2116, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        insert tanka1;
        //insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, Juchusaki__c = acc1.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryo__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        Test.startTest();
        
        try{
            juchu1.JuchuUriageKakuteiBi__c = date.newInstance(2116, 1, 1);
            update juchu1;
        }catch(Exception e){
            system.debug('エラーが発生してますよ。正しい動作ですよ。');
        }
        
        Test.stopTest();
    }
    
    // 正常：取引先単価マスタ不要フラグtrue
    static testMethod void myUnitTest6() {
        // カスタム設定
        SystemParam__c sysCon = SystemParam__c.getOrgDefaults();
        sysCon.JuchuMeisaiSaidaiTorokusu__c = 45;
        insert sysCon;
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = true);
        ShohinShizaiM__c shohin2 = new ShohinShizaiM__c(name = 'テスト商品2', ShomiKigenNissu__c = 100, AccountTankaMHuyouFlg__c = true);
        insert shohin1;
        insert shohin2;
        
        // 取引先作成
        Account acc1 = new Account(name = '株式会社テスト1', Shimebi__c = 20, Kijitsu__c = 99, AccountTankaMHuyouFlg__c = true);
        insert acc1;
        
        // 取引先単価マスタ作成
        AccountTankaM__c tanka1 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(1900, 1, 1), TekiyoKikanMade__c = Date.newInstance(2115, 12, 31));
        AccountTankaM__c tanka2 = new AccountTankaM__c(Account__c = acc1.Id, ShohinShizaiM__c = shohin1.Id, ShomiKigenKakuhoNissu__c = 10, TekiyoKikanKara__c = Date.newInstance(2116, 1, 1), TekiyoKikanMade__c = Date.newInstance(2900, 1, 1));
        insert tanka1;
        insert tanka2;
        
        // 売掛データ作成
        UrikakeData__c Urikake1 = new UrikakeData__c(name = acc1.Name, SeikyuAccount__c = acc1.Id);
        insert urikake1;
        
        // 受注データ作成
        JuchuData__c juchu1 = new JuchuData__c(UrikakeData__c = urikake1.id, name = urikake1.Name, Juchusaki__c = acc1.Id);
        insert juchu1;
        
        // 受注明細データ作成
        JuchuMeisaiData__c meisai1 = new JuchuMeisaiData__c(JuchuSuryo__c = 15, name = juchu1.name, JuchuData__c = juchu1.Id, ShohinShizaiM__c = shohin1.Id, NohinSuryo__c = 0); 
        insert meisai1;
        
        Test.startTest();
        
        meisai1.ShohinShizaiM__c = shohin2.Id;
        update meisai1;
        
        juchu1.JuchuUriageKakuteiBi__c = date.newInstance(2116, 1, 1);
        update juchu1;
                
        Test.stopTest();
    }
}