src/objects/HachuMeisaiData__c.object
<CustomObject>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KaikakeData__c.object
<CustomObject>
    <fields>
        <fullName>Shiiresaki__c</fullName>
        <label>支払先</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>買掛データ</relationshipLabel>
        <relationshipName>KaikakeData_Shiiresaki</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShimeHizuke__c</fullName>
        <label>￥￥_締基準日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShimeKikanKara__c</fullName>
        <description>買掛データに集計される支払明細データの計上日範囲。

締日＝９９ 
　締基準日の月　の　同月　の　初日 

締日＜締基準日 
　締基準日の月　の　同月　の　締日＋１日 

締日≧締基準日 
　締基準日の月　の　前月　の　締日＋１日</description>
        <formula>IF(  Shiiresaki__r.Shimebi__c  = 99, 
 DATE( YEAR(ShimeHizuke__c), MONTH(ShimeHizuke__c), 1), 

    IF( Shiiresaki__r.Shimebi__c &lt; DAY( ShimeHizuke__c ),  
     DATE( YEAR(ShimeHizuke__c), MONTH(ShimeHizuke__c), Shiiresaki__r.Shimebi__c) + 1, 

        IF(
           MONTH(ShimeHizuke__c)==1,
           DATE(YEAR(ShimeHizuke__c)-1,12                                  ,Shiiresaki__r.Shimebi__c) + 1,
           DATE(YEAR(ShimeHizuke__c)  ,MONTH(ShimeHizuke__c)-1,Shiiresaki__r.Shimebi__c) + 1
        )

    )

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>締期間から</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShimeKikanMade__c</fullName>
        <description>買掛データに集計される支払明細データの計上日範囲。 

締日＝９９ 
　締期間から＋締期間月数の月－１ヶ月　の　最終日 

締日≠９９ 
　締期間から＋締期間月数の月　の　締日</description>
        <formula>IF( Shiiresaki__r.Shimebi__c = 99, 

    IF(
    MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c&gt;12,
    DATE(YEAR(ShimeKikanKaraNamachi__c)+1,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c-12,1),
    DATE(YEAR(ShimeKikanKaraNamachi__c)  ,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c   ,1)
    )-1
    ,
        IF(
        MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c&gt;12,
        DATE(YEAR(ShimeKikanKaraNamachi__c)+1,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c-12,Shiiresaki__r.Shimebi__c),
        DATE(YEAR(ShimeKikanKaraNamachi__c)  ,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c   ,Shiiresaki__r.Shimebi__c)
        )

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>締期間まで</label>
        <type>Date</type>
    </fields>
    <label>買掛データ</label>
    <nameField>
        <label>支払名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShiharaiMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>HachuMeisaiData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>発注明細データ</label>
        <referenceTo>HachuMeisaiData__c</referenceTo>
        <relationshipLabel>支払明細データ</relationshipLabel>
        <relationshipName>ShiharaiMeisaiData_HachuMeisaiData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KaikakeData__c</fullName>
        <label>買掛データ</label>
        <referenceTo>KaikakeData__c</referenceTo>
        <relationshipLabel>支払明細データ</relationshipLabel>
        <relationshipName>ShiharaiMeisaiData_KaikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NohinSuryo__c</fullName>
        <defaultValue>0</defaultValue>
        <label>納品数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nohinbi__c</fullName>
        <inlineHelpText>支払計上を行う日付。
買掛データの締期間に合わせて集計される。</inlineHelpText>
        <label>計上日</label>
        <type>Date</type>
    </fields>
    <label>支払明細データ</label>
    <nameField>
        <displayFormat>支払明細-{0000000000}</displayFormat>
        <label>支払明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>HachuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>発注明細</label>
        <referenceTo>HachuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_HachuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NyukoNichiji__c</fullName>
        <inlineHelpText>当在庫場所へ入庫した日時
・製造完了した日付を表す場合は消費期限の算出基準となる。
・在庫を移動した日付を表す場合は入庫確認の実施タイミングとなる。</inlineHelpText>
        <label>入庫日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NyukoShiharaiFlg__c</fullName>
        <formula>AND(
 ISBLANK(  ZenZaikoData__c  ) ,
 NOT( ISBLANK( HachuMeisai__c ) ) ,
 ISBLANK( ShiharaiMeisai__c ) ,
 ShukkoNyukoZumiFlg__c  
)</formula>
        <inlineHelpText>支払が必要で有ることを示す。

ON条件
　親入出庫データ空白（始祖）　かつ
　発注明細が入力済　かつ
　支払明細が空白　かつ
　出庫済入庫済フラグがON（出庫済かつ入庫済）
の場合。</inlineHelpText>
        <label>￥￥_入庫支払フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukoShiharaiTorikeshiFlg__c</fullName>
        <formula>AND(
 ISBLANK(  ZenZaikoData__c  ) ,
 NOT( ISBLANK( HachuMeisai__c ) ) ,
 NOT( ISBLANK( ShiharaiMeisai__c ) ),
 NOT( ShukkoNyukoZumiFlg__c )  
)</formula>
        <inlineHelpText>支払を取り消していることを示す。

ON条件
　親入出庫データ空白（始祖）　かつ
　発注明細が入力済　かつ
　支払明細が入力済　かつ
　出庫済入庫済フラグがOFF（出庫済かつ未入庫）
の場合。</inlineHelpText>
        <label>￥￥_入庫支払取消フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukoSuryo__c</fullName>
        <description>当在庫場所へ入庫した数量</description>
        <inlineHelpText>当在庫場所へ入庫した数量</inlineHelpText>
        <label>入庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShiharaiMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>支払明細</label>
        <referenceTo>ShiharaiMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_ShiharaiMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShiiresakiShokai__c</fullName>
        <formula>HachuMeisai__r.HachuData__r.Shiiresaki__c</formula>
        <label>￥￥_支払先照会</label>
        <type>Text</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/K08_NyukoShiharaiRendoLogic.cls
public with sharing class K08_NyukoShiharaiRendoLogic {

    // 買掛データ一覧
    public List<KaikakeData__c> kaikakeList;
    // 支払明細データ一覧
    List<ShiharaiMeisaiData__c> insShiharaiMeisaiList;
    // 作成対象在庫データ一覧
    List<ZaikoData__c> zaikoDataList;
    // 対象外在庫データ一覧
    List<ZaikoData__c> excludZaikoDataList;

    //現在のガバナリミットSystem.limits.getLimitQueryRowsを取得する。
    Integer limitQueryRows;

    // 在庫データの発注明細の発注データの仕入先Id一覧
    Set<Id> ShiiresakiIds;

    // コンストラクタ
    public K08_NyukoShiharaiRendoLogic(){
        // 何もしない
    }
    
    /**
     * 支払明細データを作成する処理
     */
    public void createShiharaiMeisai(List<ZaikoData__c> TriggerNew){

        //現在のガバナリミットSystem.limits.getLimitQueryRowsを取得する。
	    limitQueryRows = System.limits.getLimitQueryRows();

        // 作成対象在庫データ一覧を作成
        zaikoDataList = new List<ZaikoData__c>();
        // 対象外在庫データ一覧を作成
        excludZaikoDataList = new List<ZaikoData__c>();        

        // トリガーからの一覧を順に処理
        for(ZaikoData__c trgNew:TriggerNew){
            // 入庫支払フラグがTRUEの場合
            if (trgNew.NyukoShiharaiFlg__c){
                // 作成対象に追加
                zaikoDataList.add(trgNew);
            }
            // 入庫支払取消フラグがTRUEの場合
            if (trgNew.NyukoShiharaiTorikeshiFlg__c){
                // 支払明細削除対象に追加
                excludZaikoDataList.add(trgNew);
            }
        }

        // 支払明細削除対象が存在する場合
        if (!excludZaikoDataList.isEmpty()){
            // 支払明細を削除
            deleteShiharaiMeisai(excludZaikoDataList);            
        }

        // 支払明細作成対象が存在する場合
        if (!zaikoDataList.isEmpty()){
            
            // 在庫データの発注明細の発注データの仕入先Id一覧を作成
            ShiiresakiIds = new Set<Id>();
            for (ZaikoData__c zaiko :zaikoDataList){
                // 仕入先Idを一覧に追加
                ShiiresakiIds.add(zaiko.ShiiresakiShokai__c);
                
                system.debug('*** ShiiresakiId:' + zaiko.ShiiresakiShokai__c);
                
            }
            
            // 買掛データを重複せず新たに作成
            dedupKaikakeData(zaikoDataList);
            
            // 在庫データに関係する仕入先の新たに作成した買掛データも含め一覧を取得（最近作成された1000件）
            kaikakeList = [SELECT Id, ShimeKikanKara__c, ShimeKikanMade__c, Shiiresaki__c FROM KaikakeData__c 
                           WHERE Shiiresaki__c IN :ShiiresakiIds 
                           ORDER BY CreatedDate,LastModifiedDate 
                           LIMIT :limitQueryRows
                          ];
            
            // インサート用支払明細データ一覧作成
            insShiharaiMeisaiList = new List<ShiharaiMeisaiData__c>();
            
            // 在庫データを順に処理
            for (ZaikoData__c zaiko :zaikoDataList){
                
                system.debug('*** zaiko:' + zaiko);
                
                // 買掛データを順に処理
                for (KaikakeData__c kaikake :kaikakeList){
                    // 仕入先が一致しかつ入庫日時が該当仕入先の買掛データの締期間内の場合
                    if ( kaikake.Shiiresaki__c == zaiko.ShiiresakiShokai__c && kaikake.ShimeKikanKara__c <= Date.valueOf(zaiko.NyukoNichiji__c.format('yyyy-MM-dd hh:mm:ss')) &&  kaikake.ShimeKikanMade__c >= Date.valueOf(zaiko.NyukoNichiji__c.format('yyyy-MM-dd hh:mm:ss')) ){
                        // 買掛データに関連した支払明細データを新たに作成
                        createShiharaiMeisai(zaiko, kaikake);
                    }
                    
                }
                
            }
            
            // 支払明細データ一覧をインサート
            insert insShiharaiMeisaiList;
            
            // インサート済支払明細データ一覧を順に処理
            for (ShiharaiMeisaiData__c insShiharaiMeisai :insShiharaiMeisaiList){
                
                system.debug('*** insShiharaiMeisai:' + insShiharaiMeisai);
                
                // 在庫データを順に処理
                for (ZaikoData__c zaiko :zaikoDataList){
                    // 発注明細Idが一致した場合
                    if (zaiko.HachuMeisai__c == insShiharaiMeisai.HachuMeisaiData__c){
                        // 新たに作成した支払明細データを入出庫データに設定
                        zaiko.ShiharaiMeisai__c = insShiharaiMeisai.Id;
                    }
                    
                    system.debug('*** zaiko:' + zaiko);
                    
                }
            }

        }

    }

    /**
     * 買掛データの重複を排除する処理
     */
    public void dedupKaikakeData(List<ZaikoData__c> zaikoDataList){

        // フラグ初期化
        Boolean isNotDup = TRUE;

        // 既存買掛データ一覧を作成
        List<KaikakeData__c> existkaiKakeList = new List<KaikakeData__c>();

        // 在庫データを順に処理
        for (ZaikoData__c zaiko :zaikoDataList){

            // 重複無く買掛データがインサートされた場合（及び初回のループ）
            if (isNotDup){

                // 在庫データに関係する仕入先の既存の買掛データ一覧を取得（最近作成された1000件）「INSERT後のSELECTが必要なためfor()内でSELECT実行」
                existKaikakeList = [SELECT Id, ShimeKikanKara__c, ShimeKikanMade__c, Shiiresaki__c FROM KaikakeData__c 
                                    WHERE Shiiresaki__c IN :ShiiresakiIds 
                                    ORDER BY CreatedDate,LastModifiedDate 
                                    LIMIT :limitQueryRows
                                   ];
 
                System.debug('*** existKaikakeList:' + existKaikakeList);
                
            }

            // 既存の買掛データが取得されなかった場合
            if (existKaikakeList.isEmpty()){
                // 既存が無いため作成対象
                isNotDup = TRUE;
            }else{
                // 既存の買掛データが存在した場合　順に処理
                for(KaikakeData__c existKaikake :existKaikakeList){
                    // 該当の支払先で該当期間の入庫日時の場合
                    if (existkaikake.Shiiresaki__c == zaiko.ShiiresakiShokai__c && existkaikake.ShimeKikanKara__c <= Date.valueOf(zaiko.NyukoNichiji__c.format('yyyy-MM-dd hh:mm:ss')) &&  existkaikake.ShimeKikanMade__c >= Date.valueOf(zaiko.NyukoNichiji__c.format('yyyy-MM-dd hh:mm:ss'))){
                        // 既存のため対象外
                        isNotDup = FALSE;
                        // 以降の処理を中断
                        break;
                    }else{
                        // 既存が無いため作成対象
                        isNotDup = TRUE;
                    }
                }
            }

            // 重複しない買掛データの場合
            if(isNotDup){
                // 買掛データを作成
                createKaikakeData(zaiko);
            }

        }
    }

    /**
     * 買掛データを作成する処理
     */
    public void createKaikakeData(ZaikoData__c zaiko){

        // 新たに買掛データを作成
        KaikakeData__c insKaikake = new KaikakeData__c();
        insKaikake.Name = 'Name';
        insKaikake.Shiiresaki__c = zaiko.ShiiresakiShokai__c;
        insKaikake.ShimeHizuke__c = Date.valueOf(zaiko.NyukoNichiji__c.format('yyyy-MM-dd hh:mm:ss'));

        // 買掛データをインサート
        insert insKaikake;

        System.debug('*** insKaikake:' + insKaikake);
        
    }

    /**
     * 支払明細データを作成する処理
     */
    public void createShiharaiMeisai(ZaikoData__c zaiko, KaikakeData__c kaikake){

        // 支払明細データを新たに作成
        ShiharaiMeisaiData__c insShiharaiMeisai = new ShiharaiMeisaiData__c();
        insShiharaiMeisai.KaikakeData__c = kaikake.Id;
        insShiharaiMeisai.HachuMeisaiData__c = zaiko.HachuMeisai__c;
        insShiharaiMeisai.NohinSuryo__c = zaiko.NyukoSuryo__c;
        insShiharaiMeisai.Nohinbi__c = Date.valueOf(zaiko.NyukoNichiji__c.format('yyyy-MM-dd hh:mm:ss'));
        insShiharaiMeisaiList.add(insShiharaiMeisai);

        System.debug('*** insShiharaiMeisai:' + insShiharaiMeisai);

    }

    /**
     * 支払明細データを削除する処理
     */
    public void deleteShiharaiMeisai(List<ZaikoData__c> zaikos){
        
        Set<Id> delShiharaiMeisaiIds = new Set<Id>();
        for (ZaikoData__c zaiko :zaikos){
            if (zaiko.NyukoShiharaiTorikeshiFlg__c){
                delShiharaiMeisaiIds.add(zaiko.ShiharaiMeisai__c);
            }
        }

        List<ShiharaiMeisaiData__c> delShiharaiMeisaiList = new List<ShiharaiMeisaiData__c>();
        delShiharaiMeisaiList = [SELECT Id FROM ShiharaiMeisaiData__c 
                                 WHERE Id IN :delShiharaiMeisaiIds 
                                 LIMIT :limitQueryRows
                                ];
        
        System.debug('*** delShiharaiMeisaiList:' + delShiharaiMeisaiList);
        
        if(!delShiharaiMeisaiList.isEmpty()){
            delete delShiharaiMeisaiList;
        }
        
    }

}