src/objects/HachuData__c.object
<CustomObject>
    <fields>
        <fullName>HachushoBikoTitle__c</fullName>
        <formula>&quot;備考&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_備考タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoBiko__c</fullName>
        <formula>Biko__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_備考</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoDenpyoNo__c</fullName>
        <formula>&quot;発注No.&quot; +  DenpyoNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_伝票番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoHachubi__c</fullName>
        <formula>TEXT( YEAR( Hachubi__c ) ) + &quot;年&quot; +  LPAD( TEXT( MONTH( Hachubi__c ) ) , 2, &quot; &quot;)  + &quot;月&quot; +  LPAD( TEXT( DAY( Hachubi__c ) ) , 2, &quot; &quot;)  + &quot;日&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_発注日</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoHakkobi__c</fullName>
        <formula>&quot;発行日　&quot; + TEXT(YEAR(DATEVALUE(NOW()))) + LPAD(TEXT(MONTH(DATEVALUE(NOW()))), 2,&quot;0&quot;) + &quot;/&quot; + LPAD(TEXT(DAY(DATEVALUE(NOW()))), 2,&quot;0&quot;)</formula>
        <label>￥_発注書_発行日</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoIrisuTitle__c</fullName>
        <formula>&quot;入数&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_入数タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoKikakuTitle__c</fullName>
        <formula>&quot;規　　　格&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_規格タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoDenwa__c</fullName>
        <formula>&quot;TEL：0000-11-9876&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_元電話</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoFax__c</fullName>
        <formula>&quot;FAX：0000-11-1234&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_元ＦＡＸ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoJusho1__c</fullName>
        <formula>&quot;〒000-9999　XX県XX市XXX １－１&quot;</formula>
        <label>￥_発注書_元住所１</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoJusho2__c</fullName>
        <formula>&quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_元住所２</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoMei1__c</fullName>
        <formula>&quot;株式会社　XXXX&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_元名１</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoMei2__c</fullName>
        <formula>&quot;&quot;</formula>
        <label>￥_発注書_元名２</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoMotoYubinBango__c</fullName>
        <formula>&quot;〒&quot; + Nohinsaki__r.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_元郵便番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNoTitle__c</fullName>
        <formula>&quot;No.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_ＮＯタイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiDenwa__c</fullName>
        <formula>&quot;TEL：&quot; + Nohinsaki__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先電話</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiFax__c</fullName>
        <formula>&quot;FAX：&quot; + Nohinsaki__r.Fax</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先ＦＡＸ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiJusho1__c</fullName>
        <formula>Nohinsaki__r.BillingState + Nohinsaki__r.BillingCity + Nohinsaki__r.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先住所１</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiJusho2__c</fullName>
        <formula>&quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先住所２</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiMei1__c</fullName>
        <formula>Nohinsaki__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先名１</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiMei2__c</fullName>
        <formula>Nohinsaki__r.Site</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先名２</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNohinsakiYubinBango__c</fullName>
        <formula>&quot;〒&quot; +  Nohinsaki__r.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納品先郵便番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNoki__c</fullName>
        <formula>&quot;納期　&quot; + TEXT( YEAR( NohinYoteibi__c ) ) + &quot;年&quot; +  LPAD( TEXT( MONTH( NohinYoteibi__c ) ) , 2, &quot; &quot;)  + &quot;月&quot; +  LPAD( TEXT( DAY( NohinYoteibi__c ) ) , 2, &quot; &quot;)  + &quot;日&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納期</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNokikaitoTitle__c</fullName>
        <formula>IF ( HachuKakuteiFlg__c ,
 &quot;納品日&quot;,
 &quot;納品希望日&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納期回答タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShiiresakiCode__c</fullName>
        <formula>Shiiresaki__r.TorihikisakiCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_仕入先コード</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShiiresakiFax__c</fullName>
        <formula>&quot;FAX：&quot; +  Shiiresaki__r.Fax</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_仕入先ＦＡＸ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShiiresakiMei__c</fullName>
        <formula>Shiiresaki__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_仕入先名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShohinCodeTitle__c</fullName>
        <formula>&quot;商品ｺｰﾄﾞ&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_商品コードタイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShohinMeiTitle__c</fullName>
        <formula>&quot;商　品　名&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_商品名タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoSuryoTitle__c</fullName>
        <formula>&quot;数量&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_数量タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoTaniTitle__c</fullName>
        <formula>&quot;単位&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_単位タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoTantoshaMei__c</fullName>
        <formula>&quot;仕入担当：&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_担当者名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoTitle__c</fullName>
        <formula>IF ( HachuKakuteiFlg__c ,
 &quot;発注書&quot;,
 &quot;納期確認書&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_タイトル</label>
        <type>Text</type>
    </fields>
    <label>発注データ</label>
    <nameField>
        <displayFormat>発注-{0000000000}</displayFormat>
        <label>発注番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>HachuData__c</fullName>
        <label>発注データ</label>
        <referenceTo>HachuData__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_HachuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HachushoIrisu__c</fullName>
        <formula>ShohinShizaiM__r.Naiyoryo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_入数</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoKikaku__c</fullName>
        <formula>ShohinShizaiM__r.Kikaku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_規格</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoNoki__c</fullName>
        <formula>TEXT( MONTH( NohinYoteibi__c ) ) + &quot;/&quot; + TEXT( DAY( NohinYoteibi__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_納期</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShohinCode__c</fullName>
        <formula>ShohinShizaiM__r.ShohinShizaiCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_商品コード</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoShohinMei__c</fullName>
        <formula>LEFT(ShohinShizaiM__r.Name, 20)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_商品名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoSuryo__c</fullName>
        <formula>TEXT(  HachuSuryoSanshutsu__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_数量</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachushoTani__c</fullName>
        <formula>TaniPC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_発注書_単位</label>
        <type>Text</type>
    </fields>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>HachushoMeisaiMaxNum__c</fullName>
        <defaultValue>5</defaultValue>
        <label>発注書明細最大行数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/classes/K01_HachushoController.cls
public without sharing class K01_HachushoController {
    /** 発注データID */
    private Id urlId;

    /** 発注書明細最大行数*/
    private static final Integer pageDetailMaxRows = SystemParam__c.getInstance().HachushoMeisaiMaxNum__c.intValue();
    
    /** ページデータ リスト */
    public List<PageData> pageDatas {get; private set;}
    
    
    /**
     * コンストラクタ
     */
    public K01_HachushoController () {
        // URL発注データIDを取得する
        urlId = ApexPages.currentPage().getParameters().get('HdId');
        
        pageDatas = createPageData(urlId);
    }


    /** ページデータ作成処理 */
    private List<PageData> createPageData(Id urlId){
        // インスタンス化
        PageData pageData = new PageData();
        List<PageData> pageDatas = new List<PageData>();
        
        // 発注データ
        HachuData__c hachuData = this.doSearchHachuData(urlId);
        
        // 発注データ備考をリスト化
        String hachushoBiko = String.ValueOf(hachuData.HachushoBiko__c);
        List <String> memos = new List<String>();

        if(hachushoBiko != null && hachushoBiko.length() != 0) {
            hachushoBiko = Strings.doInsertNewLineB(hachushoBiko, 150);
            
            memos = hachushoBiko.split('\n',0);
        }

        pageData.hachushoBikos = memos;
        
        
        // 発注明細データ
        List<HachuMeisaiData__c> hachuMeisaiDatas = this.doSearchHachuMeisaiData(urlId);
        
        // 1ページ目のヘッダを設定
        pageData.headData = hachuData;
        
        // 発注明細データで繰り返し
        for(Integer i = 0, j = hachuMeisaiDatas.size(); i < j; i++){
            // ページデータに見積商品明細を追加
            pageData.detailDatas.add(hachuMeisaiDatas[i]); 
            
            // 明細行数が最大に達した時
            if(pageData.detailDatas.size() == pageDetailMaxRows && i + 1 <> j ){
                // ページデータリストに追加
                pageDatas.add(pageData);
                
                // 新しいページデータ作成
                pageData = new PageData();
                pageData.headData = hachuData;
                pageData.hachushoBikos = memos;
                pageData.pageNumber += pageDatas.size();
            }
        }
        
        // ページデータリストに追加
        pageDatas.add(pageData);
        
        return pageDatas;
    }


    //発注データを取得する
    private HachuData__c doSearchHachuData(Id hachuDataId){
        // 発注データ検索
        HachuData__c hachuData = [
            SELECT
                Id,
                Name,
                HachushoShiiresakiMei__c,       //発注書_仕入先名
                HachushoDenpyoNo__c,            //発注書_伝票番号
                HachushoHakkobi__c,             //発注書_発行日
                HachushoNoki__c,                //発注書_納期
                HachushoTantoshaMei__c,         //発注書_担当者名
                HachushoNohinsakiMei1__c,       //発注書_納品先名１
                HachushoNohinsakiMei2__c,       //発注書_納品先名２
                HachushoNohinsakiJusho1__c,     //発注書_納品先住所１
                HachushoNohinsakiJusho2__c,     //発注書_納品先住所２
                HachushoNohinsakiDenwa__c,      //発注書_納品先電話
                HachushoNohinsakiFax__c,        //発注書_納品先ＦＡＸ
                
                HachushoMotoMei1__c,            //発注書_元名１
                HachushoMotoMei2__c,            //発注書_元名２
                HachushoMotoJusho1__c,          //発注書_元住所１
                HachushoMotoJusho2__c,          //発注書_元住所２
                HachushoMotoDenwa__c,           //発注書_元電話
                HachushoMotoFax__c,             //発注書_元ＦＡＸ
                
                HachushoBiko__c,                //発注書_備考
                
                HachushoTitle__c,               //発注書_タイトル
                HachushoNoTitle__c,             //発注書_ＮＯタイトル
                HachushoShohinCodeTitle__c,     //発注書_商品コードタイトル
                HachushoKikakuTitle__c,         //発注書_規格タイトル
                HachushoShohinMeiTitle__c,      //発注書_商品名タイトル
                HachushoIrisuTitle__c,          //発注書_入数タイトル
                HachushoSuryoTitle__c,          //発注書_数量タイトル
                HachushoTaniTitle__c,           //発注書_単位タイトル
                HachushoNokikaitoTitle__c,      //発注書_納期回答タイトル
                HachushoBikoTitle__c,           //発注書_備考タイトル
                
                HachushoMotoYubinBango__c,      //発注書_元郵便番号
                HachushoShiiresakiCode__c,      //発注書_仕入先コード
                HachushoShiiresakiFax__c,       //発注書_仕入先ＦＡＸ
                HachushoNohinsakiYubinBango__c, //発注書_納品先郵便番号
                HachushoHachubi__c              //発注書_発注日
            FROM
                HachuData__c
            WHERE
                Id = :hachuDataId
        ];
        
        return hachuData;
    }
    
    
    //発注明細データを取得する
    private List<HachuMeisaiData__c> doSearchHachuMeisaiData(Id hachuDataId){
        // 発注明細データ検索
        List<HachuMeisaiData__c> hachuMeisaiDatas = [
            SELECT
                Id,
                Name,
                HachushoShohinCode__c,  //発注書_商品コード
                HachushoKikaku__c,      //発注書_規格
                HachushoShohinMei__c,   //発注書_商品名
                HachushoIrisu__c,       //発注書_入数
                HachushoSuryo__c,       //発注書_数量
                HachushoTani__c,        //発注書_単位
                HachushoNoki__c         //発注書_納期
            FROM
                HachuMeisaiData__c
            WHERE
                HachuData__c = :hachuDataId
            ORDER BY
                HachushoShohinCode__c
        ];
        
        return hachuMeisaiDatas;
    }
    
    
    /** ページデータクラス */
    public class PageData {
        public Integer pageNumber { get; private set; }
        public HachuData__c headData{ get; set; }
        public List<String> hachushoBikos{ get; set; }
        public List<HachuMeisaiData__c> detailDatas{ get; private set; }
              
        public PageData(){
            this.pageNumber = 1;
            this.hachushoBikos = new List<String>();
            this.detailDatas = new List<HachuMeisaiData__c>();
        }
    }
}