src/objects/HachuData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>発注確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <label>納品予定日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nohinsaki__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>納品先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>HachuData_Nohinsaki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注データ</label>
    <nameField>
        <displayFormat>発注-{0000000000}</displayFormat>
        <label>発注番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HachuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachuData__c</fullName>
        <label>発注データ</label>
        <referenceTo>HachuData__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_HachuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HachuKakuteiFlg__c</fullName>
        <formula>HachuData__r.HachuKakuteiFlg__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_発注確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HachuSuryoPC__c</fullName>
        <label>発注数量PC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <description>発注時には決まらず、納期回答があれば入力する</description>
        <inlineHelpText>発注時には決まらず、納期回答があれば入力する</inlineHelpText>
        <label>納品予定日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>発注明細データ</relationshipLabel>
        <relationshipName>HachuMeisaiData_ShohinShizaiM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>発注明細データ</label>
    <nameField>
        <displayFormat>発注明細-{0000000000}</displayFormat>
        <label>発注明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <type>TextArea</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HachuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>発注明細</label>
        <referenceTo>HachuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_HachuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NyukoNichiji__c</fullName>
        <inlineHelpText>当在庫場所へ入庫した日時
・製造完了した日付を表す場合は消費期限の算出基準となる。
・在庫を移動した日付を表す場合は入庫確認の実施タイミングとなる。</inlineHelpText>
        <label>入庫日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NyukoSuryo__c</fullName>
        <description>当在庫場所へ入庫した数量</description>
        <inlineHelpText>当在庫場所へ入庫した数量</inlineHelpText>
        <label>入庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShukkoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>実在庫状態以降。オフの場合は予約データ（未出庫）となる。</description>
        <inlineHelpText>実際に出庫を確認したことを表す。オフの場合は確認未実施となる。</inlineHelpText>
        <label>出庫フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zaikobasho__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>場所</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>入出庫データ</relationshipLabel>
        <relationshipName>ZaikoData_Zaikobasho</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZenShukkoNichiji__c</fullName>
        <description>当在庫場所へ入庫するために、前在庫場所を出庫した日時</description>
        <inlineHelpText>当在庫場所へ入庫するために、前在庫場所を出庫した日時</inlineHelpText>
        <label>出庫日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ZenShukkoSuryo__c</fullName>
        <description>当在庫場所へ入庫するために、前在庫場所を出庫した数量</description>
        <inlineHelpText>当在庫場所へ入庫するために、前在庫場所を出庫した数量</inlineHelpText>
        <label>出庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/K06_HatchuNyukoRendoLogic.cls
public with sharing class K06_HatchuNyukoRendoLogic {

    //コンストラクタ
    public K06_HatchuNyukoRendoLogic(){
        // なにもしない。
    }

    //在庫データを作成する処理
    public void createZaiko(HachuData__c obj){
        // 発注確定フラグtrueの場合に処理を実行
        if(obj.HachuKakuteiFlg__c){
            //発注データに紐付く発注明細データを取得
            List<HachuMeisaiData__c> meisaiList = new List<HachuMeisaiData__c>();
            // 発注明細データと紐付く在庫データがあれば取得
            meisaiList = [SELECT Id, ShohinShizaiM__c, HachuSuryoPC__c, NohinYoteibi__c, Biko__c, (SELECT Id FROM ZaikoData_HachuMeisai__r) FROM HachuMeisaiData__c WHERE HachuData__c = :obj.Id];

            for(HachuMeisaiData__c item :meisaiList){
                // 紐付く在庫データが存在しない
                if((item.ZaikoData_HachuMeisai__r).isEmpty()){
                    ZaikoData__c insZaiko = new ZaikoData__c();
                    insZaiko.HachuMeisai__c = item.Id;
                    insZaiko.Zaikobasho__c = obj.Nohinsaki__c;
                    insZaiko.ShukkoFlg__c = true;
                    insZaiko.ShohinShizaiM__c = item.ShohinShizaiM__c;
                    
                    insZaiko.ZenShukkoSuryo__c = item.HachuSuryoPC__c;
                    if(item.NohinYoteibi__c != null){
                        Time tmpTime = Time.newInstance(0, 0, 0, 0);
                        insZaiko.ZenShukkoNichiji__c = DateTime.newInstance(item.NohinYoteibi__c, tmpTime);
                        insZaiko.NyukoNichiji__c = DateTime.newInstance(item.NohinYoteibi__c, tmpTime);
                    }
                    insZaiko.NyukoSuryo__c = item.HachuSuryoPC__c;
                    insZaiko.Biko__c = item.Biko__c;
                    
                    insert insZaiko;
                }
            }
        }
    }
    
    /**
     * 発注データを削除した際に発注明細に紐づく在庫データを削除する処理
     */
    public void deleteZaiko(HachuData__c obj){

        //発注データに紐付く発注明細データを取得
        List<HachuMeisaiData__c> meisaiList = new List<HachuMeisaiData__c>();

        // 発注明細データと紐付く在庫データがあれば取得
        meisaiList = [SELECT Id, ShohinShizaiM__c, (SELECT Id FROM ZaikoData_HachuMeisai__r) FROM HachuMeisaiData__c WHERE HachuData__c = :obj.Id];

        List<ZaikoData__c> deleteZaikoList = new List<ZaikoData__c>();
        for(HachuMeisaiData__c item :meisaiList){
            for(ZaikoData__c zaikoItem :item.ZaikoData_HachuMeisai__r){
                deleteZaikoList.add(zaikoItem);
            }
        }

        if(!deleteZaikoList.isEmpty()){
            delete deleteZaikoLIst;
        }

    }

}