src/objects/JuchuData__c.object
<CustomObject>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>DenpyoGyoBango__c</fullName>
        <inlineHelpText>受注データ内の在庫データの連番が書き込まれる。
使用例：伝票出力ではソート順に使用するなど。</inlineHelpText>
        <label>伝票行番号</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JuchuData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NarabiJun__c</fullName>
        <inlineHelpText>受注明細の￥￥_明細ソートキー生値がWRFで書き込まれる。</inlineHelpText>
        <label>￥￥_伝票並び順</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J04_DempyoBangokKinyuLogic.cls
public with sharing class J04_DempyoBangokKinyuLogic {

    // コンストラクタ
    public J04_DempyoBangokKinyuLogic(){
        // 何もしない。
    }

    /**
     * 在庫データの伝票行番号に受注データ内の連番を書込む
     */
    public void onAfterUpdate(JuchuData__c[] oldObjs, JuchuData__c[] newObjs, Map<ID, JuchuData__c> juchuMap){
        // 受注データ配下の受注明細データ配下の「在庫データ」を取得する
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        zaikoList = [SELECT Id, DenpyoGyoBango__c, JuchuData__c, ShohinShizaiM__c FROM ZaikoData__c WHERE JuchuData__c IN :juchuMap.keySet() ORDER BY JuchuData__c ASC, NarabiJun__c ASC];
        
        // 連番設定用カウンタ
        Integer counter = 1;
        if(!zaikoList.isEmpty()){
            for(Integer i = 0; i < zaikoList.size(); i++){
                // 連番を書き込む
                zaikoList[i].DenpyoGyoBango__c = counter;
                
                // 現在の在庫データは最後の物である、または次の在庫データの参照する受注データは別の物である
                if(i == zaikoList.size() - 1 || zaikoList[i].JuchuData__c != zaikoList[i + 1].JuchuData__c){
                    // カウンタをリセット
                    counter = 1;
                }else{
                    // カウンタをインクリメント
                    counter = counter + 1;
                }
            }
            update zaikoList;
        }
    }
}