src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HikiateMemoALL__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <description>Apexにより記入。</description>
        <inlineHelpText>引当実行時時に不正検出された内容。</inlineHelpText>
        <label>警告＋：引当</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HikiateMemo__c</fullName>
        <inlineHelpText>引当実行時時に不正検出された内容。</inlineHelpText>
        <label>警告：引当</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDispUpdateButton__c</fullName>
        <formula>NOT( 

 OR(

 JidoHikiateFlg__c  ,
 JuchuUriageKakuteiFlg__c  ,
 UrikakeData__r.SeikyuKakuteiFlg__c 

 )

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>ON条件

引当スタンバイOFF
　かつ
受注確定OFF
　かつ
売掛締切ロックOFF</inlineHelpText>
        <label>￥￥_明細一括更新ボタン表示フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuError__c</fullName>
        <formula>IF (
 HikiateKanryoFlg__c  ,
 &quot;&quot; ,

IF ( 
 MeisaiGyosuChokaHanteiFlg__c , 
 &quot;商品登録の最大数 &quot; + TEXT($Setup.SystemParam__c.JuchuMeisaiSaidaiTorokusu__c) + &quot; 件 を超え現在 &quot; + TEXT( JuchuMeisaiDataGyosu__c ) + &quot; 件登録されています。　明細を &quot; + TEXT( JuchuMeisaiDataGyosu__c - $Setup.SystemParam__c.JuchuMeisaiSaidaiTorokusu__c ) + &quot; 件　削除するか　または　非同期引当（引当スタンバイ/引当非同期確定）　を実施して非同期最大数 &quot; +  TEXT( $Setup.SystemParam__c.JuchuMeisaiSaidaiHidokiTorokusu__c )  + &quot;件　以下として下さい。&quot;, 

IF ( 
 AND(
 UrikakeData__r.SeikyuKakuteiFlg__c,
 NOT( JuchuUriageKakuteiFlg__c ) 
 )  , 
 &quot;既に売掛確定フラグをONしている締請求期間に含まれる納品予定日（納品完了日）です。&quot; +  TEXT(UrikakeData__r.ShimeKikanMade__c + 1) + &quot; 以降の日付を選択するか都度請求として下さい。&quot;  , 

IF ( 
 UrikakeYoshinChoka__c ,
 &quot;該当請求先の売掛金額が与信限度額を超えています。　現在受注可能な金額は&quot; +
 TEXT(UrikakeData__r.SeikyuAccount__r.UrikakeYoshinZan__c)   +
 &quot;円までです。&quot;, 

&quot;&quot;

))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>受注内容に不正検出された内容。</inlineHelpText>
        <label>警告：受注</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JuchuSuryoMemo__c</fullName>
        <formula>IF (
 HikiateKanryoFlg__c  ,
 &quot;&quot; ,

IF (
 AND(
 NeedAllLot__c  != 0,
 NOT( OR( ShomiKigenKonzaiFlg__c, LotKonzaiFlg__c ))
 ),
 &quot;引当に失敗する可能性があります。ユニット混在フラグをONにしてください。&quot;,

IF (
 NeedReduction__c  != 0 ,
 &quot;引当に失敗する可能性があります。受注数量を減少してください。&quot;, 


&quot;&quot;

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>入力された数量に不正検出された内容。</inlineHelpText>
        <label>警告：数量</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KoteiKoseiMemoALL__c</fullName>
        <description>Apexにより記入。</description>
        <inlineHelpText>工程構成マスタのガイド内容が明細登録時に記入される。</inlineHelpText>
        <label>警告＋：構成</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MeisaiMemoALL__c</fullName>
        <inlineHelpText>明細一括更新時のエラーが記入される。</inlineHelpText>
        <label>警告＋：明細</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NohinByogaFlg__c</fullName>
        <formula>AND(
 HikiateKanryoFlg__c ,
 NOT(  JidoHikiateFlg__c  ) ,
 NOT( HikiateNashiFlg__c ) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>引当成功完了＝ON　かつ　引当スタンバイ＝OFF　かつ　引当無フラグ＝OFF　の場合にON。</inlineHelpText>
        <label>￥￥_描画フラグ_納品</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SonotaError__c</fullName>
        <formula>IF ( 
 HikiateKanryoFlg__c , 
 &quot;&quot; ,

IF ( 
 SeikyuKakushiKeikoku__c  ,
 &quot;すべての明細に 請求隠 設定することはできません。請求書の明細に表示する明細を最低１つ残してください。&quot;  , 

IF ( 
 AND(
 ZaikoNashiNohimbiSu__c  &lt;&gt; 0 ,
 NOT( HikiateNashiFlg__c ) ) , 
 &quot;入力した納品予定日では消費期限を超過している商品が有ります。新たな商品を入荷させて下さい。&quot;  , 

IF ( 
 AND( 
 NOT(JuchuKakuteiFlg__c) , 
 NOT( HikiateKanryoFlg__c ) , 
 HikiateKanryoJotaiFlg__c ) , 
 &quot;引当解除しました。再引当して下さい。&quot;, 

IF ( 
 AND( 
 NOT( JuchuKakuteiFlg__c ) , 
 HikiateKanryoFlg__c ) , 
 &quot;引当完了フラグ　OFF　で引当済み在庫を開放します。&quot;, 

IF ( 
 MeisaiFuseiCount__c &gt;= 1, 
 &quot;数量が未入力「0個」の明細が有りますので個数を入力して下さい。&quot;, 


&quot;&quot;

))))))</formula>
        <inlineHelpText>その他の受注データ登録時に不正検出された内容。</inlineHelpText>
        <label>警告：その他</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TourokuMemoALL__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <description>Apexにより記入。</description>
        <inlineHelpText>商品資材マスタの追加の示唆（推奨/禁止）内容。
内容に応じ登録内容に参考。</inlineHelpText>
        <label>警告＋：登録</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TourokuMemo__c</fullName>
        <description>Apexにより記入。</description>
        <inlineHelpText>商品資材マスタの追加時に不正検出された内容。
不正検出された結果として明細の追加は行われない。</inlineHelpText>
        <label>警告：登録</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DenpatsuJogai__c</fullName>
        <defaultValue>false</defaultValue>
        <label>￥￥_金額集計除外フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HikiateFuyoFig__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>引当処理を行わないお場合にON。
例）入出庫を伴わない受注。
例）返品や赤伝票。</inlineHelpText>
        <label>引当無</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JuchuSuryoCS__c</fullName>
        <label>C/S数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JuchuSuryoCT__c</fullName>
        <label>C/T数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JuchuSuryoPC__c</fullName>
        <label>PC数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JuchuSuryo__c</fullName>
        <label>受注数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KingakuMinus__c</fullName>
        <defaultValue>false</defaultValue>
        <description>・明細金額マイナスフラグ＝TRUE　＝＞　行金額＝行金額×(-1)　行税込＝行税込×(-1)　行税額＝行税額×(-1)　
・明細金額マイナスフラグ＝FALSE　＝＞　何もしない</description>
        <inlineHelpText>・明細金額マイナスフラグ＝TRUE　＝＞　行金額＝行金額×(-1)　行税込＝行税込×(-1)　行税額＝行税額×(-1)　
・明細金額マイナスフラグ＝FALSE　＝＞　何もしない</inlineHelpText>
        <label>赤伝票</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KingakuZero__c</fullName>
        <defaultValue>false</defaultValue>
        <description>・明細金額ゼロフラグ＝TRUE　＝＞　行金額＝0　行税込＝0　行税額＝0　
・明細金額ゼロフラグ＝FALSE　＝＞　何もしない</description>
        <inlineHelpText>・明細金額ゼロフラグ＝TRUE　＝＞　行金額＝0　行税込＝0　行税額＝0　
・明細金額ゼロフラグ＝FALSE　＝＞　何もしない</inlineHelpText>
        <label>金額０</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeisaiJyogai__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求書の明細に表示しない場合にON。</inlineHelpText>
        <label>請求隠</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeyasuZan__c</fullName>
        <formula>IF (
  TODAY()  &gt;   JuchuData__r.NohinYoteibi__c  ,
 &quot;過去日納品&quot;,

IF (
 JuchuData__r.HikiateKanryoFlg__c  ,
 &quot;引当済&quot;,

IF (
 ShomiKigenShokai__c &gt; ShohinShizaiM__r.SaiChoHambaiKigenHizuke__c ,
 &quot;期限 &quot; +  
 TEXT( ShomiKigenShokai__c - ShohinShizaiM__r.SaiChoHambaiKigenHizuke__c ) + 
 &quot;日超過&quot;,

IF (
 AND(
 JuchuData__r.JidoHikiateFlg__c ,
 JuchuSuryo__c  &lt;=  MeyasuHikakuTaishoSuryo__c 
 ),
 &quot;予約済&quot;,

IF (
 JuchuSuryo__c  &gt;  MeyasuHikakuTaishoSuryo__c ,
 &quot;× &quot; +  TEXT( MeyasuHikakuTaishoSuryo__c ) ,

IF (
 JuchuSuryo__c  &lt;=  MeyasuHikakuTaishoSuryo__c ,
 &quot;○&quot; + TEXT( MeyasuHikakuTaishoSuryo__c )  ,

 &quot;不明&quot;

))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>・受注データの引当成功完了＝ON　→　引当済
・受注データの引当スタンバイ＝ON　→　予約済
・消費期限照会＞最長販売期限日付　→　期限超過
・受注数量＞目安残数量　→　×
・受注数量≦目安残数量　→　○</inlineHelpText>
        <label>目安残</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NarabiJun__c</fullName>
        <formula>IF(
 JuchuData__r.ShohinShizaiCodeJun__c,
LPAD(ShohinShizaiM__r.ShohinShizaiCode__c, 18, &apos;0&apos;),

IF(
 JuchuData__r.ShohinShizaiMeiJun__c,
ShohinShizaiM__r.Name,

IF(
 JuchuData__r.JanCodeJun__c,
LPAD(ShohinShizaiM__r.JanCode__c, 18, &apos;0&apos;),

IF(
 JuchuData__r.SakuseiJun__c,
TEXT(CreatedDate),

IF(OR(
 ISBLANK(TorihikisakiTanka__c),  
 ISNULL(TorihikisakiTanka__c)),
LPAD(ShohinShizaiM__r.ShohinShizaiCode__c, 18, &apos;0&apos;),

IF(OR(
 ISBLANK(TorihikisakiTanka__r.NarabiJun__c),
 ISNULL(TorihikisakiTanka__r.NarabiJun__c)),
LPAD(ShohinShizaiM__r.ShohinShizaiCode__c, 18, &apos;0&apos;),

LPAD(TEXT(TorihikisakiTanka__r.NarabiJun__c), 18, &apos;0&apos;)

))))))</formula>
        <inlineHelpText>一覧編集画面のソート順及び、帳票のソート順で使用するソートキー。</inlineHelpText>
        <label>￥￥_明細ソートキー</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NohinJogai__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>納品書の明細に表示しない場合にON。</inlineHelpText>
        <label>納品隠</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinSuryo__c</fullName>
        <label>納品数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShohinBaika__c</fullName>
        <inlineHelpText>商品1個当たりの納品単価</inlineHelpText>
        <label>商品売単価</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ShohinShizaiMeisho__c</fullName>
        <inlineHelpText>各種帳票の明細に表記される。
空白保存で商品資材マスターの標準名称にリセットされる。</inlineHelpText>
        <label>商品資材名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuryoBairitsuCS__c</fullName>
        <formula>ShohinShizaiM__r.BaiRitsuCS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_C/S数量倍率</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SuryoBairitsuCT__c</fullName>
        <formula>ShohinShizaiM__r.BaiRitsuCT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_C/T数量倍率</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaniCS__c</fullName>
        <formula>IF (SuryoBairitsuCS__c &gt; 0,
&quot;*&quot; +  TEXT(SuryoBairitsuCS__c) +    ShohinShizaiM__r.TaniPC__c  ,
 &quot;&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>C/S数入力用の倍率表記。</inlineHelpText>
        <label>単位C/S</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaniCT__c</fullName>
        <formula>IF (SuryoBairitsuCT__c &gt; 0,
&quot;*&quot;+  TEXT(SuryoBairitsuCT__c) +  ShohinShizaiM__r.TaniPC__c  ,
 &quot;&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>C/T数入力用の倍率表記。</inlineHelpText>
        <label>単位C/T</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaniPC__c</fullName>
        <formula>&quot;*1&quot; + ShohinShizaiM__r.TaniPC__c</formula>
        <label>単位PC</label>
        <type>Text</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>Biko__c</fullName>
        <label>備考</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TaniCS__c</fullName>
        <label>単位C/S</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaniCT__c</fullName>
        <label>単位C/T</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaniPC__c</fullName>
        <label>単位PC</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/J01_JuchuDataControllerExtension.cls
public class J01_JuchuDataControllerExtension {

    // 受注確定フラグ
    public Boolean isDispUpdateButton {get; set;}
    // 納品入力描画フラグ
    public Boolean isNohinByoga {get; set;}
    // 警告表示フラグ
    public Boolean AlertFlg {get; set;}
    // 警告フラグ各種
    public Boolean SonotaErrorFlg {get; set;}
    public Boolean HikiateMemoFlg {get; set;}
    public Boolean HikiateMemoALLFlg {get; set;}
    public Boolean KoteiKoseiMemoALLFlg {get; set;}
    public Boolean JuchuErrorFlg {get; set;}
    public Boolean JuchuSuryoMemoFlg {get; set;}
    public Boolean TourokuMemoFlg {get; set;}
    public Boolean TourokuMemoALLFlg {get; set;}
    public Boolean MeisaiMemoALLFlg {get; set;}

    // 標準セットコントローラー
    public ApexPages.StandardSetController ssc {get; set;}

    // ページング用
    public Boolean hasNext {get; set;}
    public Boolean hasPrevious {get; set;}
    public Integer pageNumber;

    // 編集ページング用　明細データ一覧
    public List<JuchuMeisaiData__c> targetMeisaiList {get; set;}
    // クエリ用　明細データ一覧
    public List<JuchuMeisaiData__c> selctMeisaiList;
    // 受注データ 
    public JuchuData__c juchuData {get; set;}
    // 受注データID
    public Id juchuDataId;
    
    // コンストラクタ
    public J01_JuchuDataControllerExtension(ApexPages.StandardController stdController){

        // 受注データIDを取得
        juchuDataId = stdController.getId();

        // 受注データを取得
        getJuchuData();

        // 受注データフラグを取得
        getJuchuDataFlg();

        // ページ番号初期化
        pageNumber = 1;

        //セットコントローラー初期化
        initStdSetCon();

        //ページネイション情報取得
        initSwitchingPage();

    }

    //受注明細取得処理とセットコントローラー初期化
    public void initStdSetCon() {

        // 受注明細取得処理
        List<JuchuMeisaiData__c> selctMeisaiList = new List<JuchuMeisaiData__c>();
        
        selctMeisaiList = [SELECT Id, 
                           ShohinShizaiM__c, ShohinShizaiMeisho__c, MeyasuZan__c, Biko__c, 
                           KingakuZero__c, KingakuMinus__c, 
                           DenpatsuJogai__c, NohinJogai__c, MeisaiJyogai__c, HikiateFuyoFig__c, 
                           JuchuSuryo__c, JuchuSuryoCT__c, JuchuSuryoCS__c, JuchuSuryoPC__c, 
                           NohinSuryo__c, 
                           ShohinBaika__c,
                           TaniPC__c, TaniCS__c, TaniCT__c ,
                           SuryoBairitsuCS__c, SuryoBairitsuCT__c 
                           FROM JuchuMeisaiData__c 
                           WHERE JuchuData__c = :juchuDataId 
                           ORDER BY NarabiJun__c ASC
                          ];

        // セットコントローラー起動
        ssc = new ApexPages.StandardSetController(selctMeisaiList);
        // 1ページ行数設定
        ssc.setPageSize(10);
        // ページ番号番号設定
        ssc.setPageNumber(pageNumber);
        // セットコントローラーから一覧取得
        targetMeisaiList = ssc.getRecords();

    }
    
    //ページネイション情報取得
    public void initSwitchingPage() {
        // 次ページ有無
        hasNext = ssc.getHasNext();
        // 前ページ有無
        hasPrevious = ssc.getHasPrevious();
        // 現在のページ番号取得
        pageNumber = ssc.getPageNumber();
    }
    
    //保存ボタンを押した時の処理
    public void saveButton() {
        //明細一覧と受注データ更新
        updateMeisaiList();
        //ページネイション情報取得
        initSwitchingPage();
        //受注明細取得処理とセットコントローラー初期化
        initStdSetCon();
        // 受注データ側の表示を更新
        getJuchuData();
        // 受注データ側のフラグを更新
        getJuchuDataFlg();
    }

    //再表示ボタンを押した時の処理
    public void reDisplay() {
        //ページネイション情報取得
        initSwitchingPage();
        //受注明細取得処理とセットコントローラー初期化
        initStdSetCon();
        // 受注データ側の表示を更新
        getJuchuData();
        // 受注データ側のフラグを更新
        getJuchuDataFlg();
    }

    // ページ次ページ
    public void next(){
        // 一旦に初期化（編集途中のページネイションエラー対策）
        initStdSetCon();
        // 次ページを選択
        ssc.next();
        // ページを選択後の情報を取得
        initSwitchingPage();
        // ページを選択後の情報で初期化
        initStdSetCon();
    }

    // ページ前ページ
    public void previous(){
        // 一旦に初期化（編集途中のページネイションエラー対策）
        initStdSetCon();
        // 前ページを選択
        ssc.previous();
        // ページを選択後の情報を取得
        initSwitchingPage();
        // ページを選択後の情報で初期化
        initStdSetCon();
    }
    
    //受注明細と受注データ更新処理
    private void updateMeisaiList(){

        //エラー書込先を一旦空白
        JuchuData.MeisaiMemoALL__c = '';

        // DMLエクセプション想定
        try {
            //明細を更新
            update targetMeisaiList;
        } catch (System.DmlException e) {
            //エクセプション発生時はメッセージを受注データに書き込む
            for (Integer i = 0; i < e.getNumDml(); i++) {
                JuchuData.MeisaiMemoALL__c += '\n' + e.getDmlMessage(i);
            }
        }

        //メッセージを書込で受注データを更新
        update JuchuData;

    }

    //受注データ取得処理
    public void getJuchuData(){

        juchuData = new JuchuData__c();

        juchuData = [SELECT Id, 
                     IsDispUpdateButton__c, NohinByogaFlg__c,
                     SonotaError__c, JuchuError__c, HikiateMemo__c, JuchuSuryoMemo__c, TourokuMemo__c, 
                     HikiateMemoALL__c, KoteiKoseiMemoALL__c, TourokuMemoALL__c, MeisaiMemoALL__c
                     FROM JuchuData__c 
                     WHERE Id = :juchuDataId 
                     LIMIT 1
                    ];

    }

    //受注データフラグ取得処理
    public void getJuchuDataFlg(){

        // 描画切替フラグ設定
        isDispUpdateButton = JuchuData.IsDispUpdateButton__c;
        isNohinByoga = JuchuData.NohinByogaFlg__c;

        // 警告：その他 フラグ設定
        if (String.isNotBlank(juchuData.SonotaError__c)){ SonotaErrorFlg = TRUE; }else{ SonotaErrorFlg = FALSE; }
        // 警告：引当 フラグ設定
        if (String.isNotBlank(juchuData.HikiateMemo__c)){ HikiateMemoFlg = TRUE; }else{ HikiateMemoFlg = FALSE; }
        // 警告＋：引当 フラグ設定
        //if (String.isNotBlank(juchuData.HikiateMemoALL__c)){ HikiateMemoALLFlg = TRUE; }else{ HikiateMemoALLFlg = FALSE; }
        // 警告＋：引当 フラグ設定（非表示固定）
        HikiateMemoALLFlg = FALSE;
        // 警告＋：構成 フラグ設定
        //if (String.isNotBlank(juchuData.KoteiKoseiMemoALL__c)){ KoteiKoseiMemoALLFlg = TRUE; }else{ KoteiKoseiMemoALLFlg = FALSE; }
        // 警告＋：構成 フラグ設定（非表示固定）
        KoteiKoseiMemoALLFlg = FALSE;
        // 警告：受注 フラグ設定
        if (String.isNotBlank(juchuData.JuchuError__c)){ JuchuErrorFlg = TRUE; }else{ JuchuErrorFlg = FALSE; }
        // 警告：数量 フラグ設定
        if (String.isNotBlank(juchuData.JuchuSuryoMemo__c)){ JuchuSuryoMemoFlg = TRUE; }else{ JuchuSuryoMemoFlg = FALSE; }
        // 警告：登録 フラグ設定
        if (String.isNotBlank(juchuData.TourokuMemo__c)){ TourokuMemoFlg = TRUE; }else{ TourokuMemoFlg = FALSE; }
        // 警告＋：登録 フラグ設定
        //if (String.isNotBlank(juchuData.TourokuMemoALL__c)){ TourokuMemoALLFlg = TRUE; }else{ TourokuMemoALLFlg = FALSE; }
        // 警告＋：登録 フラグ設定（非表示固定）
        TourokuMemoALLFlg = FALSE;
        // 警告＋：明細 フラグ設定
        if (String.isNotBlank(juchuData.MeisaiMemoALL__c)){ MeisaiMemoALLFlg = TRUE; }else{ MeisaiMemoALLFlg = FALSE; }

        // 警告表示フラグ設定
        if (SonotaErrorFlg||HikiateMemoFlg||HikiateMemoALLFlg||KoteiKoseiMemoALLFlg||JuchuErrorFlg||JuchuSuryoMemoFlg||TourokuMemoFlg||TourokuMemoALLFlg||MeisaiMemoALLFlg){
            AlertFlg = TRUE;
        }else{
            AlertFlg = FALSE;
        }
        
    }

}