src/objects/JuchuData__c.object
<CustomObject>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J46_JyutyuSakujyoZaikoLogic.cls
public with sharing class J46_JyutyuSakujyoZaikoLogic {

    // コンストラクタ
    public J46_JyutyuSakujyoZaikoLogic(){
        // 何もしない。
    }
    
    public void deleteJuchuMeisai(set<Id> JuchuIdSet){

        // 削除対象の受注明細データのリスト
        List<JuchuMeisaiData__c> deleteJuchuMeisaiDataList = new List<JuchuMeisaiData__c>();
        deleteJuchuMeisaiDataList = [SELECT Id, JuchuData__c FROM JuchuMeisaiData__c WHERE JuchuData__c IN :JuchuIdSet];
        
        if(!deleteJuchuMeisaiDataList.isEmpty()){
            delete deleteJuchuMeisaiDataList;
        }

    }

}