src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>HikiateKanryoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>全ての商品の引当に成功した場合にON。
引当解除と再引当を行う場合は　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当成功完了</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>引当可能フラグON　かつ　当フラグ　ON　で在庫データの引当を試みます。
引当解除と再引当を行う場合は　引当成功完了　OFF　かつ　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当即時確定</label>
        <type>Checkbox</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JuchuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注明細</label>
        <referenceTo>JuchuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J47_JyutyuKakuteiTorikesiZaikoLogic.cls
public with sharing class J47_JyutyuKakuteiTorikesiZaikoLogic {

    // コンストラクタ
    public J47_JyutyuKakuteiTorikesiZaikoLogic(){
        // 何もしない。
    }

    public void deleteZaiko(JuchuData__c oldObjs, JuchuData__c newObjs){

        // 引当完了フラグと受注確定フラグが変更された場合のみ実行
        if(oldObjs.HikiateKanryoFlg__c != newObjs.HikiateKanryoFlg__c && oldObjs.JuchuKakuteiFlg__c != newObjs.JuchuKakuteiFlg__c){

            // 引当完了フラグfalseかつ受注確定フラグfalseの場合のみ実行
            if(!newObjs.HikiateKanryoFlg__c && !newObjs.JuchuKakuteiFlg__c){

                // 配下の受注明細の配下の在庫データを取得
                List<ZaikoData__c> deleteZaikoList = new List<ZaikoData__c>();
                deleteZaikoList = [SELECT Id FROM ZaikoData__c WHERE JuchuMeisai__c IN (SELECT Id FROM JuchuMeisaiData__c WHERE JuchuData__c = :newObjs.Id)];

                //配列が空でなければ削除実行
                if(!deleteZaikoList.isEmpty()){
                    system.debug(deleteZaikoList);
                    delete deleteZaikoList;
                }

            }
            
        }

    }
}