src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShohinShizaiM__c.object
<CustomObject>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShukaMikomiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuMeisaiData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>出荷明細データ</label>
        <referenceTo>JuchuMeisaiData__c</referenceTo>
        <relationshipLabel>消費見込データ</relationshipLabel>
        <relationshipName>ShukaMikomiData_JuchuMeisaiData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材マスタ</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ShukaMikomiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消費見込データ</label>
    <nameField>
        <displayFormat>消費見込-{000000000}</displayFormat>
        <label>消費見込番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J07_JuchuYosokuRendoLogic.cls
public with sharing class J07_JuchuYosokuRendoLogic {

    // コンストラクタ
    public J07_JuchuYosokuRendoLogic(){
        // 何もしない。
    }

    /**
     * 登録後処理
     */
    public void onAfterInsert(JuchuMeisaiData__c[] newObjs, Set<Id> juchuMeisaiDataIds){
        List<ShukaMikomiData__c> shukaMikomiDatas = [SELECT Id FROM ShukaMikomiData__c WHERE JuchuMeisaiData__c IN :juchuMeisaiDataIds];
        
        if(shukaMikomiDatas == null || shukaMikomiDatas.size() == 0) {
            List<ShukaMikomiData__c> insetDatas = new List<ShukaMikomiData__c>();
            
            // 受注明細データを参照する、出荷見込データが存在しない場合
            for(JuchuMeisaiData__c newObj: newObjs) {
                // 出荷見込データ：新規作成レコード
                ShukaMikomiData__c shukaMikomiData = new ShukaMikomiData__c();
            
                shukaMikomiData.JuchuMeisaiData__c = newObj.Id;
                shukaMikomiData.ShohinShizaiM__c = newObj.ShohinShizaiM__c;
                
                insetDatas.add(shukaMikomiData);
            }
            
            insert insetDatas;
        }
    }
    
    
    /**
     * 更新後処理
     */
    public void onAfterUpdate(JuchuMeisaiData__c[] oldObjs, JuchuMeisaiData__c[] newObjs, Set<Id> juchuMeisaiDataIds){
        List<ShukaMikomiData__c> shukaMikomiDatas = [
            SELECT Id,JuchuMeisaiData__c,ShohinShizaiM__c FROM ShukaMikomiData__c WHERE JuchuMeisaiData__c IN :juchuMeisaiDataIds];

        // 受注明細データを参照する、出荷見込データが存在する場合
        if(shukaMikomiDatas != null && shukaMikomiDatas.size() > 0) {
            // 出荷見込データ：更新
            for(ShukaMikomiData__c shukaMikomi: shukaMikomiDatas) {
                
                for(JuchuMeisaiData__c newObj: newObjs) {
                    if(shukaMikomi.JuchuMeisaiData__c == newObj.Id) {
                        shukaMikomi.ShohinShizaiM__c = newObj.ShohinShizaiM__c;
                        break;
                    }
                }
            }
            update shukaMikomiDatas;
        }
    }
    
    
    /**
     * 削除前処理
     */
    public void onBeforeDelete(Set<Id> juchuMeisaiDataIds){
        List<ShukaMikomiData__c> shukaMikomiDatas = [SELECT Id FROM ShukaMikomiData__c WHERE JuchuMeisaiData__c IN :juchuMeisaiDataIds];
        delete shukaMikomiDatas;
    }
}