src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>HikiateKanryoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>全ての商品の引当に成功した場合にON。
引当解除と再引当を行う場合は　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当成功完了</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HikiateZanjiKaijo__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>即時ではなく後ほど一括で引当を解除する場合にON。 

非同期引当の解除には本フラグにより非同期に引当解除が必要。</inlineHelpText>
        <label>引当非同期解除</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HikiateZanjiKakutei__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>即時ではなく後ほど一括引当を起動する場合にON。
スタンバイ予約と違い納品予定日の更新は行われない。</inlineHelpText>
        <label>引当非同期確定</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JidoHikiateFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>チェック有りで　後ほど　システムにより　受注確定引当　を行います。

継続的に引当スタンバイ状態にする場合は　引当スタンバイ予約　も合わせて設定が必要。</inlineHelpText>
        <label>引当スタンバイ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JidoHikiateYoyaku__c</fullName>
        <inlineHelpText>引当スタンバイを特定日付移行に継続的にONとする日付。

本日付移行に引当できなかった場合は納品請求日が自動的に繰上げされる。


例）入荷し次第に納品引当する場合。
例）未入荷の商品を先行し受注登録する場合。
例）入荷し引当した日付を納品請求日とする場合。</inlineHelpText>
        <label>引当スタンバイ予約</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JuchuKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>引当可能フラグON　かつ　当フラグ　ON　で在庫データの引当を試みます。
引当解除と再引当を行う場合は　引当成功完了　OFF　かつ　当フラグ　OFF　にします。</inlineHelpText>
        <label>引当即時確定</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JuchuUriageKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>受注データを確定し売掛データへの金額は集計を行う場合ON。</description>
        <inlineHelpText>納品の確定と請求の確定をする場合にON。

例）注文書FAXを受領し契約の意思確認が取れた。
例）商品を発送し先方から受領書を受け取った。</inlineHelpText>
        <label>納品請求確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MuJokenHikiateFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>引当可能フラグがOFFでも引当を実行することができるようにするフラグ。

引当可能フラグがOFFとなる場合に、引当即時確定がOFFとされる処理を抑止する。

非同期引当（引当スタンバイ/引当非同期確定）時にバッチApexによりONにされる。</inlineHelpText>
        <label>￥￥_無条件引当フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NohinYoteibi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>受注確定フラグOFFの場合に、売掛データの締期間を検索する日付。

出荷引当の試行時に、入出庫データの賞味期限を検索する日付。</inlineHelpText>
        <label>納品請求日</label>
        <type>Date</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J06_ShukkoRendoBatch.cls
global class J06_ShukkoRendoBatch implements Database.Batchable<sObject>, Database.Stateful {

    global Database.Querylocator start(Database.BatchableContext inBC) {
        // 受注データを全件取得する
        return Database.getQueryLocator('SELECT Id, HikiateZanjiKaijo__c, JidoHikiateFlg__c, HikiateZanjiKakutei__c, HikiateKanryoFlg__c, JidoHikiateYoyaku__c, NohinYoteibi__c, JuchuUriageKakuteiFlg__c FROM JuchuData__c ORDER BY HikiateZanjiKaijo__c, JidoHikiateFlg__c, HikiateZanjiKakutei__c,NohinYoteibi__c,CreatedDate');
    }

    global void execute(Database.BatchableContext inBC, List<JuchuData__c> inScope) {
        // 更新用受注データリスト作成
        List<JuchuData__c> updJuchuList = new List<JuchuData__c>();
        
        // 前処理から受け取った受注データをループ
        for(JuchuData__c item :inScope){

            //引当スタンバイがONのレコードは引当即時確ONを試行する。スタンバイ予約をOFFにする。
            if( item.JidoHikiateFlg__c){

                system.debug('*** JidoHikiate :' + item.JidoHikiateFlg__c);

                item.MuJokenHikiateFlg__c = true;
                item.JidoHikiateFlg__c = false ;
                item.JuchuKakuteiFlg__c = true;
            }

            //引当非同期確定がONのレコードは引当即時確ONを試行する。引当漸次確定はOFFにする。
            if( item.HikiateZanjiKakutei__c && !item.HikiateZanjiKaijo__c && !item.HikiateKanryoFlg__c){

                system.debug('*** HikiateZanjiKakutei :' + item.HikiateZanjiKakutei__c);

                item.MuJokenHikiateFlg__c = true;
                item.HikiateZanjiKakutei__c = false;
                item.JuchuKakuteiFlg__c = true;
            }

            //引当非同期解除がONのレコードは引当成功完了OFFを実行する。引当非同期解除はOFFにする。納品請求確定フラグもOFFにする。
            if( item.HikiateZanjiKaijo__c && !item.HikiateZanjiKakutei__c && item.HikiateKanryoFlg__c){

                system.debug('*** HikiateZanjiKaijo :' + item.HikiateZanjiKaijo__c);

                item.MuJokenHikiateFlg__c = false;
                item.HikiateZanjiKaijo__c = false ;
                item.HikiateKanryoFlg__c = false ;
                item.JuchuUriageKakuteiFlg__c = false;
            }

            // 更新用受注データListに受注データインスタンスを追加する。
            updJuchuList.add(item);

        }
        
        // 更新用受注データListを更新する。  
        if(!updJuchuList.isEmpty()){
            // 入力規則エラーが発生するため対応
            try{
                update updJuchuList;                
            }catch (System.DmlException e) {
                System.debug('*** updJuchuList DmlException: ' + e);
            }
        }

        Id batchId = inBc.getJobId();
        List<AsyncApexJob> asyncApexJobList = new List<AsyncApexJob>();
        asyncApexJobList = [SELECT Id,ParentJobId,Status,JobType,CreatedDate,CompletedDate FROM AsyncApexJob WHERE ParentJobId = :batchId OR Id = :batchId];
        if(!asyncApexJobList.isEmpty()){
            for(AsyncApexJob aaJob :asyncApexJobList){
                System.debug('*** AsyncApexJob = ' + aaJob);
                
            }
        }

    }

    /**
     * 終了処理
     */
    global void finish(Database.BatchableContext inBC) {
    
    }
}