src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>KariNohinshoDenpyoNoTitle__c</fullName>
        <formula>&quot;納品管理No.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_伝票番号タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoDenpyoNo__c</fullName>
        <formula>DenpyoNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_伝票番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoFooter__c</fullName>
        <formula>IF(OR(ISBLANK(Nohinsaki__c), ISNULL(Nohinsaki__c)),
  $Setup.SystemParam__c.NohinshoFooter__c,
  IF(OR(ISBLANK(Nohinsaki__r.NohinshoFooter__c), ISNULL(Nohinsaki__r.NohinshoFooter__c)),
    $Setup.SystemParam__c.NohinshoFooter__c,
    Nohinsaki__r.NohinshoFooter__c
  )
)</formula>
        <label>￥_納品書_フッタ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoGyoTitle__c</fullName>
        <formula>&quot;No.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_行タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoHassobi__c</fullName>
        <formula>Biko__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_発送日</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoHinbanTitle__c</fullName>
        <formula>&quot;品番&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_品番タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoHinmeiTitle__c</fullName>
        <formula>&quot;品　　名&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_品名タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoKenTitle__c</fullName>
        <formula>&quot;検&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_検タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoKen__c</fullName>
        <formula>&quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_検</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoKikakuBikoTitle__c</fullName>
        <formula>&quot;備　考&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_規格備考タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinMoto__c</fullName>
        <formula>&quot;納品元　XYZ株式会社&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品元</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinbiTitle__c</fullName>
        <formula>&quot;納品日&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品日タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinbi__c</fullName>
        <formula>TEXT(YEAR( NohinYoteibi__c )) + &quot;/&quot; + TEXT(MONTH( NohinYoteibi__c )) + &quot;/&quot; + TEXT(DAY( NohinYoteibi__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品日</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinsakiCDTitle__c</fullName>
        <formula>&quot;納品先CD&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品先ＣＤタイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinsakiCD__c</fullName>
        <formula>Nohinsaki__r.TorihikisakiCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品先ＣＤ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinsakiDenwa__c</fullName>
        <formula>&quot;TEL　&quot; + IF(ISBLANK(Nohinsaki__c), Juchusaki__r.Phone, Nohinsaki__r.Phone)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品先電話</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinsakiMei1__c</fullName>
        <formula>IF(ISBLANK(Nohinsaki__c),
  Juchusaki__r.BillingPostalCode + &quot;　&quot; + Juchusaki__r.BillingState + Juchusaki__r.BillingCity + Juchusaki__r.BillingStreet,
  Nohinsaki__r.BillingPostalCode + &quot;　&quot; + Nohinsaki__r.BillingState + Nohinsaki__r.BillingCity + Nohinsaki__r.BillingStreet
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_納品先名１</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNohinsakiMei2__c</fullName>
        <formula>IF(ISBLANK(Nohinsaki__c),
  Juchusaki__r.SeishikiMeisho__c &amp; &apos;　&apos; &amp; Juchusaki__r.Keisho__c,
  Nohinsaki__r.SeishikiMeisho__c &amp; &apos;　&apos;  &amp; Nohinsaki__r.Keisho__c
)</formula>
        <label>￥_納品書_納品先名２</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNyuryokushaTitle__c</fullName>
        <formula>&quot;入力者&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_入力者タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoNyuryokusha__c</fullName>
        <formula>LastModifiedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_入力者</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoShomiKigenTitle__c</fullName>
        <formula>&quot;消費期限&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_期限タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoShutsuTitle__c</fullName>
        <formula>&quot;出&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_出タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoShutsu__c</fullName>
        <formula>&quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_出</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoSuryoTitle__c</fullName>
        <formula>&quot;数量&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_数量タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoTitle__c</fullName>
        <formula>&quot;納　品　書&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoTokuisakiCDTitle__c</fullName>
        <formula>&quot;得意先CD&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_得意先ＣＤタイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoTokuisakiCD__c</fullName>
        <formula>Juchusaki__r.TorihikisakiCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_得意先ＣＤ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NouhinsyoShutsuryokuzumiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>納品書発行を実行でON。</inlineHelpText>
        <label>納品書出力済フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KariNohinshoHinban__c</fullName>
        <formula>ShohinShizaiM__r.ShohinShizaiCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_品番</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoHinmei__c</fullName>
        <formula>IF (
 JuchuData__r.HikiateKanryoFlg__c ,

IF (
 ISBLANK( TorihikisakiTanka__r.AiteShohinShizaimei__c ) ,
 LEFT( ShohinShizaiMeisho__c , 60) ,
 LEFT(TorihikisakiTanka__r.AiteShohinShizaimei__c, 60)),

IF (
 ISBLANK( TorihikisakiTanka__r.AiteShohinShizaimei__c ) ,
 LEFT( ShohinShizaiMeisho__c , 35) ,
 LEFT(TorihikisakiTanka__r.AiteShohinShizaimei__c, 35))

)</formula>
        <label>￥_納品書_品名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoKikakuBiko__c</fullName>
        <formula>IF (  NOT(ISBLANK( Biko__c ))  ,
 Biko__c ,

IF (  NOT(JuchuData__r.HikiateKanryoFlg__c)  ,
 NisugataSanko__c,

 &quot;&quot;

) )</formula>
        <inlineHelpText>備考に記入がある場合は備考内容を出力。

　でなければ

引当未完了の場合は荷姿参考を出力。
　または
引当完了後は空白を出力。</inlineHelpText>
        <label>￥_納品書_備考</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NarabiJun__c</fullName>
        <formula>IF(
 JuchuData__r.ShohinShizaiCodeJun__c,
LPAD(ShohinShizaiM__r.ShohinShizaiCode__c, 18, &apos;0&apos;),

IF(
 JuchuData__r.ShohinShizaiMeiJun__c,
ShohinShizaiM__r.Name,

IF(
 JuchuData__r.JanCodeJun__c,
LPAD(ShohinShizaiM__r.JanCode__c, 18, &apos;0&apos;),

IF(
 JuchuData__r.SakuseiJun__c,
TEXT(CreatedDate),

IF(OR(
 ISBLANK(TorihikisakiTanka__c),  
 ISNULL(TorihikisakiTanka__c)),
LPAD(ShohinShizaiM__r.ShohinShizaiCode__c, 18, &apos;0&apos;),

IF(OR(
 ISBLANK(TorihikisakiTanka__r.NarabiJun__c),
 ISNULL(TorihikisakiTanka__r.NarabiJun__c)),
LPAD(ShohinShizaiM__r.ShohinShizaiCode__c, 18, &apos;0&apos;),

LPAD(TEXT(TorihikisakiTanka__r.NarabiJun__c), 18, &apos;0&apos;)

))))))</formula>
        <inlineHelpText>一覧編集画面のソート順及び、帳票のソート順で使用するソートキー。</inlineHelpText>
        <label>￥￥_明細ソートキー</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NohinJogai__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>納品書の明細に表示しない場合にON。</inlineHelpText>
        <label>納品隠</label>
        <type>Checkbox</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>NohinshoFontSize__c</fullName>
        <defaultValue>14</defaultValue>
        <label>納品書品名フォントサイズ</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NohinshoLineByteNum__c</fullName>
        <defaultValue>160</defaultValue>
        <label>納品書品名改行バイト数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NohinshoMeisaiMaxNum__c</fullName>
        <defaultValue>18</defaultValue>
        <label>納品書明細最大行数</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JuchuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注明細</label>
        <referenceTo>JuchuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KariNohinshoKikakuBiko__c</fullName>
        <formula>IF ( ISBLANK(Biko__c) ,

&quot;ロット&quot; + 
LotBango__c + 
&quot;　　（&quot; + 
NisugataSanko__c + 
&quot;）&quot; 
,

LEFT(Biko__c, 19)

)</formula>
        <inlineHelpText>備考に記入がある場合は備考内容を出力。

　でなければ

ロット番号　と　荷姿参考　を出力。</inlineHelpText>
        <label>￥_納品書_備考</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoShomiKigen__c</fullName>
        <formula>LPAD(TEXT(YEAR(ShomiKigen__c)), 4,&quot;0&quot;)
 + &quot;/&quot; + 
LPAD(TEXT(MONTH(ShomiKigen__c)), 2,&quot;0&quot;)
 + &quot;/&quot; + 
LPAD(TEXT(DAY(ShomiKigen__c)), 2,&quot;0&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_消費期限</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KariNohinshoSuryo__c</fullName>
        <formula>TEXT( ZenShukkoSuryo__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_納品書_数量</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NarabiJun__c</fullName>
        <inlineHelpText>受注明細の￥￥_明細ソートキー生値がWRFで書き込まれる。</inlineHelpText>
        <label>￥￥_伝票並び順</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J22_NohinshoController.cls
public without sharing class J22_NohinshoController{
    /** 受注データID */
    private Id urlId;

    /** 明細最大行数*/
    private static final Integer pageDetailMaxRows = SystemParam__c.getInstance().NohinshoMeisaiMaxNum__c.intValue();
    
    /** 納品書品名改行バイト数*/
    public static final Integer nohinshoLineByteNum  = SystemParam__c.getInstance().NohinshoLineByteNum__c.intValue();
    
    /** 納品書品名フォントサイズ*/
    public Integer nohinshoFontSize {get{return SystemParam__c.getInstance().NohinshoFontSize__c.intValue();}}

    /** ページデータ リスト */
    public List<PageData> pageDatas {get; private set;}
    
    
    /**
     * コンストラクタ
     */
    public J22_NohinshoController () {
        // URL受注データIDを取得する
        urlId = ApexPages.currentPage().getParameters().get('JdId');

        this.pageDatas = createPageData(urlId);
    }
    
    
    /**
     * 納品書出力済フラグを更新する
     */
    public void doUpdate(){
        if(null != pageDatas && pageDatas.size() > 0){
            // 受注データ
            JuchuData__c juchuData = pageDatas[0].headData;
            
            // 納品書　を　発行した際に　受注データ.納品書出力済フラグ　を　TRUE　にする
            juchuData.NouhinsyoShutsuryokuzumiFlg__c = true;
            update juchuData;
        }
    }
    
    
    /** ページデータ作成処理 */
    private List<PageData> createPageData(Id urlId){
        // インスタンス化
        PageData pageData = new PageData();
        List<PageData> pageDatas = new List<PageData>();

        // 在庫データリスト
        List<ZaikoData__c> zaikoDataAll = this.doSearchZaikoData(urlId);

        // 受注データ
        JuchuData__c juchuData = new JuchuData__c();
        
        if(zaikoDataAll != null && zaikoDataAll.size() > 0) {
            juchuData = zaikoDataAll[0].JuchuMeisai__r.JuchuData__r;
        }else{
            juchuData = doSearchJuchuData(urlId);
        }

        // 受注明細データリスト
        List<JuchuMeisaiData__c> juchuMeisaiDatas = this.doSearchJuchuMeisai(urlId);

        // 受注明細データと在庫データマップ
        Map<Id,List<ZaikoData__c>> meisaiZaikoMap = new Map<Id,List<ZaikoData__c>>();
        
        // 受注明細データで繰り返し、受注明細データと在庫データマップを作成
        for(Integer i = 0, j = juchuMeisaiDatas.size(); i < j; i++) {
            List<ZaikoData__c> zaikoDatas = new List<ZaikoData__c>();
            
            for(Integer m = 0, n = zaikoDataAll.size(); m < n; m++){
                if(zaikoDataAll[m].JuchuMeisai__c == juchuMeisaiDatas[i].Id) {
                    zaikoDatas.add(zaikoDataAll[m]);
                }
            }
            meisaiZaikoMap.put(juchuMeisaiDatas[i].Id, zaikoDatas);
        }

        // 1ページ目のヘッダを設定
        pageData.headData = juchuData;
        Integer pageRows = 0;

        // 受注明細データで繰り返し
        for(Integer i = 0, j = juchuMeisaiDatas.size(); i < j; i++){
            
            // 受注明細データと入金データ
            DetailWrapper detailWrap = new DetailWrapper();
            
            // 受注明細データ
            detailWrap.meisaiData = juchuMeisaiDatas[i];
            
            // 品名をリスト化
            String hinmei = String.ValueOf(juchuMeisaiDatas[i].KariNohinshoHinmei__c);
            List <String> hinmeis = new List<String>();

            if(hinmei != null && hinmei.length() != 0) {
                hinmei = Strings.doInsertNewLineB(hinmei, nohinshoLineByteNum);
            
                hinmeis = hinmei.split('\n',0);
            }

            detailWrap.hinmeis = hinmeis;
            pageRows++;

            for(Integer m = 0, n = zaikoDataAll.size(); m < n; m++){
                if(zaikoDataAll[m].JuchuMeisai__c == juchuMeisaiDatas[i].Id) {
                    detailWrap.zaikoDatas.add(zaikoDataAll[m]);
                    pageRows++;

                    // 明細行数が最大行数に達した時　かつ　最後受注明細以外の場合
                    if(pageRows == pageDetailMaxRows && (i != (j-1)) ){
                        // ページデータに受注データと受注明細データを追加
                        pageData.detailDatas.add(detailWrap);
                        
                        // ページデータリストに追加
                        pageDatas.add(pageData);
                        
                        // 新しいページデータ作成
                        pageData = new PageData();
                        detailWrap = new DetailWrapper();
                        pageData.headData = juchuData;
                        pageData.pageNumber += pageDatas.size();
                        
                        pageRows = 0;
                    }
                }
            }
            
            // 一つの受注明細が２ページに分かれないように改ページを行う。（１明細でMAX行以上ある場合は仕方ないけど）
            // 明細の在庫データ数がページの残した行数に入れない場合、次のページに回す、最後の明細の場合、下記処理を行わない
            if( (i != (j-1)) && ((pageDetailMaxRows - pageRows) < (meisaiZaikoMap.get(juchuMeisaiDatas[i+1].Id).size()+1)) ) {
                // ページデータに受注データと受注明細データを追加
                        pageData.detailDatas.add(detailWrap);
                        
                        // ページデータリストに追加
                        pageDatas.add(pageData);
                        
                        // 新しいページデータ作成
                        pageData = new PageData();
                        detailWrap = new DetailWrapper();
                        pageData.headData = juchuData;
                        pageData.pageNumber += pageDatas.size();
                        
                        pageRows = 0;
            }
            
            // ページデータに受注データと受注明細データを追加
            pageData.detailDatas.add(detailWrap);
        }
        
        // ページデータリストに追加
        pageDatas.add(pageData);

        return pageDatas;
    }


    // 在庫データを取得する
    private List<ZaikoData__c> doSearchZaikoData(Id urlId) {
        
        // 在庫データ検索
        List<ZaikoData__c> zaikoDatas = [
                SELECT
                    Id,
                    Name,
                    JuchuMeisai__r.JuchuData__r.KariNohinshoTitle__c,               //仮納品書_タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinMoto__c,           //仮納品書_納品元
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinsakiMei1__c,       //仮納品書_納品先名１
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinsakiMei2__c,       //仮納品書_納品先名２
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinsakiDenwa__c,      //仮納品書_納品先電話
                    JuchuMeisai__r.JuchuData__r.KariNohinshoTokuisakiCD__c,         //仮納品書_得意先ＣＤ
                    JuchuMeisai__r.JuchuData__r.KariNohinshoTokuisakiCDTitle__c,    //仮納品書_得意先ＣＤタイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinsakiCD__c,         //仮納品書_納品先ＣＤ
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinsakiCDTitle__c,    //仮納品書_納品先ＣＤタイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinbi__c,             //仮納品書_納品日
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNohinbiTitle__c,        //仮納品書_納品日タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoDenpyoNo__c,            //仮納品書_伝票番号
                    JuchuMeisai__r.JuchuData__r.KariNohinshoDenpyoNoTitle__c,       //仮納品書_伝票番号タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNyuryokusha__c,         //仮納品書_入力者
                    JuchuMeisai__r.JuchuData__r.KariNohinshoNyuryokushaTitle__c,    //仮納品書_入力者タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoKen__c,                 //仮納品書_検
                    JuchuMeisai__r.JuchuData__r.KariNohinshoKenTitle__c,            //仮納品書_検タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoShutsu__c,              //仮納品書_出
                    JuchuMeisai__r.JuchuData__r.KariNohinshoShutsuTitle__c,         //仮納品書_出タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoHassobi__c,             //仮納品書_発送日
                    JuchuMeisai__r.JuchuData__r.KariNohinshoGyoTitle__c,            //仮納品書_行タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoHinbanTitle__c,         //仮納品書_品番タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoHinmeiTitle__c,         //仮納品書_品名タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoShomiKigenTitle__c,     //仮納品書_賞味期限タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoSuryoTitle__c,          //仮納品書_数量タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoKikakuBikoTitle__c,     //仮納品書_規格備考タイトル
                    JuchuMeisai__r.JuchuData__r.KariNohinshoFooter__c,              //￥_仮納品書_フッタ
                    
                    JuchuMeisai__r.KariNohinshoHinban__c,                           //仮納品書_品番
                    JuchuMeisai__r.KariNohinshoHinmei__c,                          //仮納品書_品名
                    JuchuMeisai__r.KariNohinshoKikakuBiko__c,                      //仮納品書_規格備考
                    
                    KariNohinshoShomiKigen__c,                                      //仮納品書_賞味期限
                    KariNohinshoKikakuBiko__c,                                      //仮納品書_規格備考
                    KariNohinshoSuryo__c                                           //仮納品書_数量
                FROM
                    ZaikoData__c
                WHERE
                    JuchuMeisai__r.JuchuData__c = :urlId
                AND JuchuMeisai__r.NohinJogai__c = FALSE
                ORDER BY
                    JuchuMeisai__r.KariNohinshoHinban__c,                           //仮納品書_品番
                    KariNohinshoShomiKigen__c                                       //仮納品書_賞味期限
            ];
        return zaikoDatas;
    }


    // 受注明細データを取得する
    private List<JuchuMeisaiData__c> doSearchJuchuMeisai(Id urlId) {
        
        // 受注明細タデータ検索
        List<JuchuMeisaiData__c> juchuMeisais = [
                SELECT
                    Id,
                    Name,
                    KariNohinshoHinban__c,                           //仮納品書_品番
                    KariNohinshoHinmei__c,                          //仮納品書_品名
                    KariNohinshoKikakuBiko__c                       //仮納品書_規格備考
                FROM
                    JuchuMeisaiData__c
                WHERE
                    JuchuData__c = :urlId
                AND NohinJogai__c = FALSE
                ORDER BY
                    NarabiJun__c ASC
            ];
        return juchuMeisais;
    }
    

    // 受注データを取得する
    private JuchuData__c doSearchJuchuData(Id urlId) {
    
        JuchuData__c zaikoData = [
            SELECT
                Id,
                Name,
                KariNohinshoTitle__c,               //仮納品書_タイトル
                KariNohinshoNohinMoto__c,           //仮納品書_納品元
                KariNohinshoNohinsakiMei1__c,       //仮納品書_納品先名１
                KariNohinshoNohinsakiMei2__c,       //仮納品書_納品先名２
                KariNohinshoNohinsakiDenwa__c,      //仮納品書_納品先電話
                KariNohinshoTokuisakiCD__c,         //仮納品書_得意先ＣＤ
                KariNohinshoTokuisakiCDTitle__c,    //仮納品書_得意先ＣＤタイトル
                KariNohinshoNohinsakiCD__c,         //仮納品書_納品先ＣＤ
                KariNohinshoNohinsakiCDTitle__c,    //仮納品書_納品先ＣＤタイトル
                KariNohinshoNohinbi__c,             //仮納品書_納品日
                KariNohinshoNohinbiTitle__c,        //仮納品書_納品日タイトル
                KariNohinshoDenpyoNo__c,            //仮納品書_伝票番号
                KariNohinshoDenpyoNoTitle__c,       //仮納品書_伝票番号タイトル
                KariNohinshoNyuryokusha__c,         //仮納品書_入力者
                KariNohinshoNyuryokushaTitle__c,    //仮納品書_入力者タイトル
                KariNohinshoKen__c,                 //仮納品書_検
                KariNohinshoKenTitle__c,            //仮納品書_検タイトル
                KariNohinshoShutsu__c,              //仮納品書_出
                KariNohinshoShutsuTitle__c,         //仮納品書_出タイトル
                KariNohinshoHassobi__c,             //仮納品書_発送日
                KariNohinshoGyoTitle__c,            //仮納品書_行タイトル
                KariNohinshoHinbanTitle__c,         //仮納品書_品番タイトル
                KariNohinshoHinmeiTitle__c,         //仮納品書_品名タイトル
                KariNohinshoShomiKigenTitle__c,     //仮納品書_賞味期限タイトル
                KariNohinshoSuryoTitle__c,          //仮納品書_数量タイトル
                KariNohinshoKikakuBikoTitle__c,     //仮納品書_規格備考タイトル
                KariNohinshoFooter__c               //￥_仮納品書_フッタ
            FROM
                JuchuData__c
            WHERE
                Id = :urlId
        ];
        return zaikoData;
    }

    /** ページデータクラス */
    public class PageData {
        public Integer pageNumber { get; private set; }
        public JuchuData__c headData{ get; set; }
        public List<DetailWrapper> detailDatas{ get; private set; }
        
        public PageData(){
            this.pageNumber = 1;
            this.detailDatas = new List<DetailWrapper>();
        }
    }
    
    
    /** ラッパークラス */
    public class DetailWrapper {
        public JuchuMeisaiData__c meisaiData { get; set; }
        public List<ZaikoData__c> zaikoDatas { get; set; }
        public List<String> hinmeis { get; set; }
        
        public DetailWrapper(){
            this.zaikoDatas = new List<ZaikoData__c>();
        }
    }
    
    
}