src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KeshikomiData__c.object
<CustomObject>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>消込値引データ</relationshipLabel>
        <relationshipName>NyukinData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消込値引データ</label>
    <nameField>
        <label>消込値引名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SystemParam__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>SeikyushoAtesakiHidariChoseiMm__c</fullName>
        <defaultValue>19</defaultValue>
        <label>請求書宛先左余白調整(mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SeikyushoAtesakiUeChoseiMm__c</fullName>
        <defaultValue>3</defaultValue>
        <label>請求書宛先上余白調整(mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SeikyushoMeisaiMaxNum__c</fullName>
        <defaultValue>36</defaultValue>
        <label>請求書明細最大行数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SeikyushoTitleShitaChoseiMm__c</fullName>
        <defaultValue>20</defaultValue>
        <label>請求書タイトル下余白調整(mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SeikyushoTitleUeChoseiMm__c</fullName>
        <defaultValue>10</defaultValue>
        <label>請求書タイトル上余白調整(mm)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>システム設定</label>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyushoAisatsu__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;毎度格別のお引立てを賜り厚く御礼申しあげます　下記の通りお見積りさせていただきます&quot;,
 &quot;毎度格別のお引立てを賜り厚く御礼申しあげます　下記の通りご請求させていただきます&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_あいさつ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoDenpyoHizukeTitle__c</fullName>
        <formula>&quot;納品日付&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_伝票日付タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoDenpyoNoTitle__c</fullName>
        <formula>&quot;納品管理No. &quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_伝票番号タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoGinko1__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;&quot;,
 SeikyuAccount__r.OfurikomisakiGinko1__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_銀行１</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoGinko2__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;&quot;,
 SeikyuAccount__r.OfurikomisakiGinko2__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_銀行２</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoGinkoTitle__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
  DempyoTitle__c ,
 &quot;－－－　お振込先銀行　－－－&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_銀行タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower01Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;&quot;,
 &quot;①別請求お支払漏れ&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段01タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower01__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 null,
 SeikyuAccount__r.SeikyuZumiKaishuGakuSokei__c  -  KekuteiMiKaishuZandaka__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段01</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower02Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;①お見積り金額&quot;,
 &quot;②今回お買上金額&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段02タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower02__c</fullName>
        <formula>ZeiBetsuGakuKei__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段02</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower03Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;②消費税&quot;,
 &quot;③今回の消費税&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段03タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower03__c</fullName>
        <formula>ShohiZeiGaku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段03</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower04Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;③お値引き&quot;,
 &quot;④今回控除額&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段04タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower04__c</fullName>
        <formula>KakuteiKaishuNebikiGaku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段04</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower05Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;お見積り額①+②-③&quot;,
 &quot;ご請求額①+②+③-④&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段05タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoLower05__c</fullName>
        <formula>SeikyuAccount__r.SeikyuZumiKaishuGakuSokei__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_下段05</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyushoSeikyusakiBusho__c</fullName>
        <formula>IF(OR(ISBLANK(Tantosha__c), ISNULL(Tantosha__c)),
  SeikyuAccount__r.SeishikiMeisho__c + &quot; &quot; + SeikyuAccount__r.Keisho__c,
  Tantosha__r.Department
)</formula>
        <label>￥_請求書_請求先部署</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoSeikyusakiJusho__c</fullName>
        <formula>SeikyuAccount__r.BillingState + SeikyuAccount__r.BillingCity + SeikyuAccount__r.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_請求先住所</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoSeikyusakiMei__c</fullName>
        <formula>IF(ISBLANK(Tantosha__c),
  &quot;&quot;,
   Tantosha__r.Title  + &quot;　&quot; + Tantosha__r.LastName + Tantosha__r.FirstName + &quot;　&quot; + Tantosha__r.Keisho__c 
)</formula>
        <label>￥_請求書_請求先名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoSeikyusakiYubinBango__c</fullName>
        <formula>&quot;〒&quot; +  SeikyuAccount__r.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_請求先郵便番号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoShamei__c</fullName>
        <formula>&quot;&quot;</formula>
        <label>￥_請求書_社名</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoShohinMeiKikakuTitle__c</fullName>
        <formula>&quot;商品名／規格&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_商品名規格タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoSuryoTitle__c</fullName>
        <formula>&quot;数　量&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_数量タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoTaniTitle__c</fullName>
        <formula>&quot;単位&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_単位タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoTitle__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;お見積り書&quot;,
 &quot;ご請求　明細書&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper01Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c , 
&quot;有効期限&quot;, 
&quot;対象期間&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段01タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper01__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c , 
TEXT(YEAR(  ShimeKikanKaraNamachi__c - 1 )) + &quot;/&quot; + 
TEXT(MONTH( ShimeKikanKaraNamachi__c - 1 )) + &quot;/&quot; +
TEXT(DAY( ShimeKikanMadeNamachi__c )) , 
TEXT(YEAR(  ShimeKikanKaraNamachi__c  )) + &quot;/&quot; + 
TEXT(MONTH( ShimeKikanKaraNamachi__c )) + &quot;/&quot; + 
TEXT(DAY( ShimeKikanKaraNamachi__c )) + &quot;～&quot; + 
TEXT(YEAR(  ShimeKikanMadeNamachi__c  )) + &quot;/&quot; + 
TEXT(MONTH( ShimeKikanMadeNamachi__c )) + &quot;/&quot; + 
TEXT(DAY( ShimeKikanMadeNamachi__c )) 
)</formula>
        <label>￥_請求書_上段01</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper02Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;お支払い予定&quot;,
 &quot;お支払い期限&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段02タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper02__c</fullName>
        <formula>TEXT(YEAR(   SeikyuKaishuKigen__c   )) + &quot;/&quot; + 
TEXT(MONTH( SeikyuKaishuKigen__c )) + &quot;/&quot; + 
TEXT(DAY( SeikyuKaishuKigen__c ))</formula>
        <label>￥_請求書_上段02</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper03Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;納品予定数&quot;,
 &quot;納品数&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段03タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper03__c</fullName>
        <formula>TEXT(KakuteiDenpyoMaisu__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段03</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper04Title__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;&quot;,
 &quot;請求No.&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段04タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper04__c</fullName>
        <formula>IF ( SeikyuYoteiMode__c ,
 &quot;&quot;,
 DenpyoNo__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段04</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper05Title__c</fullName>
        <formula>&quot;弊社担当者&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥_請求書_上段05タイトル</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyushoUpper05__c</fullName>
        <formula>LastModifiedBy.LastName  +  LastModifiedBy.FirstName</formula>
        <label>￥_請求書_上段05</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeikyusyoShutsuryokuzumiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>請求書発行を実行でON。</inlineHelpText>
        <label>請求書出力済フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N01_SeikyushoController.cls
public without sharing class N01_SeikyushoController {

    /** 売掛データID */
    private Id urlId;

    /** 請求書明細最大行数*/
    private static final Integer pageDetailMaxRows = SystemParam__c.getInstance().SeikyushoMeisaiMaxNum__c.intValue();
    
    /** 請求書宛先左余白調整(mm)*/
    public Integer atesakiHidariChoseiMm {get{return SystemParam__c.getInstance().SeikyushoAtesakiHidariChoseiMm__c.intValue();}}
    
    /** 請求書宛先上余白調整(mm)*/
    public Integer atesakiUeChoseiMm {get{return SystemParam__c.getInstance().SeikyushoAtesakiUeChoseiMm__c.intValue();}}
    
    /** 請求書タイトル上余白調整(mm)*/
    public Integer titleUeMm {get{return SystemParam__c.getInstance().SeikyushoTitleUeChoseiMm__c.intValue();}}
    
    /** 請求書タイトル下余白調整(mm)*/
    public Integer titleShitaMm {get{return SystemParam__c.getInstance().SeikyushoTitleShitaChoseiMm__c.intValue();}}
    
    /** ページデータ リスト */
    public List<PageData> pageDatas {get; private set;}
    
    private UrikakeData__c urikakeData;
    
    
    /**
     * コンストラクタ
     */
    public N01_SeikyushoController () {
        // URL売掛データIDを取得する
        urlId = ApexPages.currentPage().getParameters().get('UdId');
        
        // 売掛データ
        urikakeData = this.doSearchUrikakeData(urlId);
        
        pageDatas = createPageData(urlId);
        
    }
    
     /**
     * 請求書出力済フラグを更新する
     */
    public void doUpdate(){
        // 請求書　を　発行した際に　売掛データ.請求書出力済フラグ　を　TRUE　にする
        urikakeData.SeikyusyoShutsuryokuzumiFlg__c = true;
        update urikakeData;
    }
    
    /** ページデータ作成処理 */
    private List<PageData> createPageData(Id urlId){
        // インスタンス化
        PageData pageData = new PageData();
        List<PageData> pageDatas = new List<PageData>();
        
        // 売掛データ請求書_あいさつをリスト化
        String aisatsu = String.ValueOf(urikakeData.SeikyushoAisatsu__c);
        List <String> aisatsus = new List<String>();

        if(aisatsu != null && aisatsu.length() != 0) {
            aisatsu = Strings.doInsertNewLineB(aisatsu, 44);
            
            aisatsus = aisatsu.split('\n',0);
        }

        pageData.aisatsuDatas = aisatsus;
        
        // 受注明細データ
        List<JuchuMeisaiData__c> juchuMeisaiDataAll = this.doSearchJuchuMeisaiData(urlId);

        // 受注データ
        List<JuchuData__c> juchuDatas = this.doSearchJuchuData(juchuMeisaiDataAll);

        // 入金データ
        List<KeshikomiData__c> keshikomiDatas = this.doSearchKeshikomiData(urlId);
        
        // 1ページ目のヘッダを設定
        pageData.headData = urikakeData;
        
        Integer pageRows = 0;

        // 受注データで繰り返し
        for(Integer i = 0, j = juchuDatas.size(); i < j; i++){
            // 受注データと受注明細データ
            DetailWrapper detailWrap = new DetailWrapper();
            
            // 受注データ
            detailWrap.juchuData = juchuDatas[i];
            
            pageRows++;
            
            for(Integer m = 0, n = juchuMeisaiDataAll.size(); m < n; m++){
                if(juchuMeisaiDataAll[m].JuchuData__c == juchuDatas[i].Id) {
                    detailWrap.juchuMeisaiDatas.add(juchuMeisaiDataAll[m]);
                    pageRows++;

                    // 明細行数が最大に達した時
                    // （受注データが最後レコード　AND　（受注明細データが最後レコード　OR　入金データなし））の場合、次のページを作らない
                    if(pageRows >= pageDetailMaxRows && 
                       ( (i != (j-1)) || ( (i == (j-1)) && ( (m != (n-1)) || keshikomiDatas.size()!=0 ) ) )
                        ){
                        
                        // ページデータに受注データと受注明細データを追加
                        pageData.detailDatas.add(detailWrap);
                        
                        // ページデータリストに追加
                        pageDatas.add(pageData);
                        
                        // 新しいページデータ作成
                        pageData = new PageData();
                        detailWrap = new DetailWrapper();
                        pageData.headData = urikakeData;
                        pageData.aisatsuDatas = aisatsus;
                        pageData.pageNumber += pageDatas.size();
                        
                        pageRows = 0;
                    }
                }
            }
            
            // ページデータに受注データと受注明細データを追加
            pageData.detailDatas.add(detailWrap);
        }
        
        
        // 入金データで繰り返し
        for(Integer i = 0, j = keshikomiDatas.size(); i < j; i++){
            pageData.keshikomiDatas.add(keshikomiDatas[i]);
            pageRows++;
            
            // 明細行数が最大に達した時（入金データが最後レコードの場合、次のページを作らない）
            if(pageRows == pageDetailMaxRows && i != (j-1) ){
                
                // ページデータリストに追加
                pageDatas.add(pageData);
                
                // 新しいページデータ作成
                pageData = new PageData();
                pageData.headData = urikakeData;
                pageData.aisatsuDatas = aisatsus;
                pageData.pageNumber += pageDatas.size();
                
                pageRows = 0;
            }
        }
        
        // ページデータリストに追加
        pageDatas.add(pageData);
        
        return pageDatas;
    }
    
    
    //売掛データを取得する
    private UrikakeData__c doSearchUrikakeData(Id urikakeDataId){
        // 売掛データ検索
        UrikakeData__c urikakeData = [
            SELECT
                Id,
                Name,
                SeikyushoShamei__c,                     //請求書_社名
                SeikyushoSeikyusakiYubinBango__c,       //請求書_請求先郵便番号
                SeikyushoSeikyusakiJusho__c,            //請求書_請求先住所
                SeikyushoSeikyusakiBusho__c,            //請求書_請求先部署
                SeikyushoSeikyusakiMei__c,              //請求書_請求先名
                SeikyushoTitle__c,                      //請求書_タイトル
                SeikyushoAisatsu__c,                    //請求書_あいさつ
                SeikyushoGinkoTitle__c,                 //請求書_銀行タイトル
                SeikyushoGinko1__c,                     //請求書_銀行１
                SeikyushoGinko2__c,                     //請求書_銀行２

                SeikyushoUpper01Title__c,        //請求書_上段01タイトル
                SeikyushoUpper01__c,             //請求書_上段01
                SeikyushoUpper02Title__c,        //請求書_上段02タイトル
                SeikyushoUpper02__c,             //請求書_上段02
                SeikyushoUpper03Title__c,        //請求書_上段03タイトル
                SeikyushoUpper03__c,             //請求書_上段03
                SeikyushoUpper04Title__c,        //請求書_上段04タイトル
                SeikyushoUpper04__c,             //請求書_上段04
                SeikyushoUpper05Title__c,        //請求書_上段05タイトル
                SeikyushoUpper05__c,             //請求書_上段05

                SeikyushoLower01Title__c,        //請求書_下段01タイトル
                SeikyushoLower01__c,             //請求書_下段01
                SeikyushoLower02Title__c,        //請求書_下段02タイトル
                SeikyushoLower02__c,             //請求書_下段02
                SeikyushoLower03Title__c,        //請求書_下段03タイトル
                SeikyushoLower03__c,             //請求書_下段03
                SeikyushoLower04Title__c,        //請求書_下段04タイトル
                SeikyushoLower04__c,             //請求書_下段04
                SeikyushoLower05Title__c,        //請求書_下段05タイトル
                SeikyushoLower05__c,             //請求書_下段05

                SeikyushoDenpyoHizukeTitle__c,          //請求書_伝票日付タイトル
                SeikyushoDenpyoNoTitle__c,              //請求書_伝票番号タイトル
                SeikyushoShohinMeiKikakuTitle__c,       //請求書_商品名規格タイトル
                SeikyushoSuryoTitle__c,                 //請求書_数量タイトル
                SeikyushoTaniTitle__c,                  //請求書_単位タイトル
                SeikyushoTankaTitle__c,                 //請求書_単価タイトル
                SeikyushoKingakuTitle__c,               //請求書_金額タイトル
                SeikyushoBikoTitle__c                   //請求書_備考タイトル

            FROM
                UrikakeData__c
            WHERE
                Id = :urikakeDataId
        ];
        
        return urikakeData;
    }
    
    
    //受注明細データを取得する
    private List<JuchuMeisaiData__c> doSearchJuchuMeisaiData(Id urikakeDataId){
        // 受注明細データ検索
        List<JuchuMeisaiData__c> juchuMeisaiDatas = [
            SELECT
                Id,
                Name,
                JuchuData__c,                   //受注データ
                SeikyushoMeisaiShohinMei__c,    //請求書_明細商品名
                SeikyushoMeisaiKikaku__c,       //請求書_明細規格
                SeikyushoMeisaiSuryo__c,        //請求書_明細数量
                SeikyushoMeisaiTani__c,         //請求書_明細単位
                SeikyushoMeisaiTanka__c,        //請求書_明細単価
                SeikyushoMeisaiKingaku__c,      //請求書_明細金額
                SeikyushoMeisaiBiko__c          //請求書_明細備考
            FROM
                JuchuMeisaiData__c
            WHERE
                SeikyuShoTaishoGai__c = False
            and JuchuData__r.UrikakeData__c = :urikakeDataId
            ORDER BY
                JuchuData__r.SeikyushoDenpyoNo__c,      //受注データ．請求書_伝票番号
                NarabiJun__c ASC           //受注明細データ．並び順
        ];
        
        return juchuMeisaiDatas;
    }
    
    
    // 受注データを取得する
    private List<JuchuData__c> doSearchJuchuData(List<JuchuMeisaiData__c> juchuMeisaiDatas){
        
        Set<Id> juchuIds = new Set<Id>();
        
        //受注データIDを取得する
        if (juchuMeisaiDatas != null && juchuMeisaiDatas.size() > 0) {
            for(Integer i=0, j=juchuMeisaiDatas.size(); i<j; i++) {
                juchuIds.add(juchuMeisaiDatas[i].JuchuData__c);
            }
        }
        
        List<JuchuData__c> juchuDatas = new List<JuchuData__c>();
        
        // 受注データ検索
        if (juchuIds != null && juchuIds.size() > 0) {
            juchuDatas = [
                SELECT
                    Id,
                    Name,
                    JuchuUriageKakuteiBi__c,
                    SeikyushoDenpyoHizuke__c,   //請求書_伝票日付
                    SeikyushoDenpyoNo__c,       //請求書_伝票番号
                    SeikyushoDenpyoTanka__c,    //請求書_伝票単価
                    SeikyushoDenpyoKingaku__c,  //請求書_伝票金額
                    SeikyushoDenpyoBiko__c,      //請求書_伝票備考
                    SeikyushoDempyoSetsumei__c //請求書_伝票説明
                FROM
                    JuchuData__c
                WHERE
                    Id In :juchuIds
                    AND DenpyoKingakuZeroFlg__c = false
                    AND JuchuUriageKakuteiFlg__c = true
                ORDER BY
                    SeikyushoDenpyoNo__c        //受注データ．請求書_伝票番号
            ];
        }
        return juchuDatas;
    }
    
    
    // 入金データを取得する
    private List<KeshikomiData__c> doSearchKeshikomiData(Id urikakeDataId){
        
        // 入金データ検索
        List<KeshikomiData__c> keshikomiDatas = [
                SELECT
                    Id,
                    Name,
                    SeikyushoNyukinKingaku__c,      //請求書_入金金額
                    SeikyushoNyukinShohinMei__c,    //請求書_入金商品名
                    SeikyushoNyukinHizuke__c        //請求書_入金日付
                FROM
                    KeshikomiData__c
                WHERE
                    UrikakeData__c = :urikakeDataId
                AND SeikyuMeisaiFlg__c = TRUE
                ORDER BY
                    SeikyushoNyukinHizuke__c,        //請求書_入金日付
                    Biko__c                          //備考
            ];
        return keshikomiDatas;
    }
    
    
    /** ページデータクラス */
    public class PageData {
        public Integer pageNumber { get; private set; }
        public UrikakeData__c headData{ get; set; }
        public List<String> aisatsuDatas { get; set; }
        public List<DetailWrapper> detailDatas{ get; private set; }
        public List<KeshikomiData__c> keshikomiDatas{ get; private set; }
        
        public PageData(){
            this.pageNumber = 1;
            this.detailDatas = new List<DetailWrapper>();
            this.keshikomiDatas = new List<KeshikomiData__c>();
        }
    }
    
    
    /** ラッパークラス */
    public class DetailWrapper {
        public JuchuData__c juchuData { get; set; }
        public List<JuchuMeisaiData__c> juchuMeisaiDatas { get; set; }
        
        public DetailWrapper(){
            this.juchuMeisaiDatas = new List<JuchuMeisaiData__c>();
        }
    }
}