src/objects/JuchuData__c.object
<CustomObject>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JuchuMeisaiData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <label>受注出荷データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipLabel>出荷明細データ</relationshipLabel>
        <relationshipName>JuchuMeisaiData_JuchuData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>出荷明細データ</label>
    <nameField>
        <label>出荷明細名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注データ</label>
        <referenceTo>JuchuData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JuchuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注明細</label>
        <referenceTo>JuchuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J41_DenpyoShutsuryokuShienLogic.cls
public with sharing class J41_DenpyoShutsuryokuShienLogic {

    // コンストラクタ
    public J41_DenpyoShutsuryokuShienLogic(){
        // 何もしない。
    }
    
    public void setJuchuId(ZaikoData__c[] newObjs){
        Set<Id> meisaiIdSet = new Set<Id>();
        
        // 登場する受注明細データのIdのsetを作成する
        for(ZaikoData__c item :newObjs){
            if(item.JuchuMeisai__c != null){
                meisaiIdSet.add(item.JuchuMeisai__c);
            }
        }

        
        // 取得した受注明細に対応する受注データを取得
        List<JuchuMeisaiData__c> meisaiList = new List<JuchuMeisaiData__c>();
        meisaiList = [SELECT Id, JuchuData__c FROM JuchuMeisaiData__c WHERE Id IN :meisaiIdSet];
        
        // key:受注明細のId,value:受注データのIdのMapを作成する。
        Map<Id, Id> meisaiJuchuMap = new Map<Id, Id>();
        for(JuchuMeisaiData__c item :meisaiList){
            meisaiJuchuMap.put(item.Id, item.JuchuData__c);
        }

        // 在庫データに受注Idを設定する
        for(ZaikoData__c item :newObjs){
            if(item.JuchuMeisai__c != null){
                item.JuchuData__c = meisaiJuchuMap.get(item.JuchuMeisai__c);
            }
        }
    }
}