src/objects/JuchuData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuUriageKakuteiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>受注データを確定し売掛データへの金額は集計を行う場合ON。</description>
        <inlineHelpText>納品の確定と請求の確定をする場合にON。

例）注文書FAXを受領し契約の意思確認が取れた。
例）商品を発送し先方から受領書を受け取った。</inlineHelpText>
        <label>納品請求確定フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SaikenMihasseiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>商品（サービス）の納品前に請求を行う場合にON。
債権未発生フラグONの売掛データに集約される。
先払請求を行う際にON。</inlineHelpText>
        <label>先払債権無フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONする。
受注データの都度請求フラグONが集約される。
部分請求を行う際にON。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UrikakeDataShokaibi__c</fullName>
        <formula>IF ( JuchuUriageKakuteiFlg__c ,
  JuchuUriageKakuteibi__c ,
  NohinYoteibi__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売掛データを検索する際の基準となる日付。

売掛データの新規生成時は、締期間起算日に代入される。

受注確定フラグONの場合は受注確定日。
受注確定フラグOFFの場合は提供予定日。</inlineHelpText>
        <label>￥￥_売掛データ照会日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>受注出荷データ</relationshipLabel>
        <relationshipName>JuchuData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>受注出荷データ</label>
    <nameField>
        <label>受注出荷</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SaikenMihasseiFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>商品（サービス）の納品前に請求を行う場合にON。トリガによりONされる。
受注データの債権未発生フラグONが集約される。</inlineHelpText>
        <label>先払債権無フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShimeHizuke__c</fullName>
        <inlineHelpText>締め期間算出用の基準となる日付。

本日付を含む形で締期間（請求起算日～請求締日）が算出される。</inlineHelpText>
        <label>請求起算基準日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShimeKikanKara__c</fullName>
        <formula>IF( KahenSeikyuFlg__c, 
 ShimeKikanKaraShudo__c , 

IF( TsudoSeikyuFlg__c, 
 ShimeHizuke__c, 

IF( SeikyuAccount__r.Shimebi__c = 99, 
 DATE( YEAR(ShimeHizuke__c), MONTH(ShimeHizuke__c), 1), 

IF( SeikyuAccount__r.Shimebi__c &lt; DAY( ShimeHizuke__c ),  
 DATE( YEAR(ShimeHizuke__c), MONTH(ShimeHizuke__c), SeikyuAccount__r.Shimebi__c) + 1, 

 IF(
    MONTH(ShimeHizuke__c)==1,
    DATE(YEAR(ShimeHizuke__c)-1,12                                  ,SeikyuAccount__r.Shimebi__c) + 1,
    DATE(YEAR(ShimeHizuke__c)  ,MONTH(ShimeHizuke__c)-1,SeikyuAccount__r.Shimebi__c) + 1
 )

))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売掛データに集計される受注データの計上日範囲。

可変請求ON
　請求起算日（手動）
　
都度請求ON
　請求起算基準日

締日＝９９
　締基準日の月　の　同月　の　初日

締日＜締基準日
　締基準日の月　の　同月　の　締日＋１日

締日≧締基準日
　締基準日の月　の　前月　の　締日＋１日</inlineHelpText>
        <label>請求起算日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShimeKikanMade__c</fullName>
        <formula>IF( KahenSeikyuFlg__c, 
 ShimeKikanMadeShudo__c , 

IF( TsudoSeikyuFlg__c, 
 ShimeHizuke__c, 

IF( SeikyuAccount__r.Shimebi__c = 99, 
 IF(
    MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c&gt;12,
    DATE(YEAR(ShimeKikanKaraNamachi__c)+1,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c-12,1),
    DATE(YEAR(ShimeKikanKaraNamachi__c)  ,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c   ,1)
 )-1
 ,
 IF(
    MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c&gt;12,
    DATE(YEAR(ShimeKikanKaraNamachi__c)+1,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c-12,SeikyuAccount__r.Shimebi__c),
    DATE(YEAR(ShimeKikanKaraNamachi__c)  ,MONTH(ShimeKikanKaraNamachi__c)+ShimekikanTsukisu__c   ,SeikyuAccount__r.Shimebi__c)
 )

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>売掛データに集計される受注データの計上日範囲。

可変請求ON
　請求締日（手動）
　
都度請求ON
　請求起算基準日

締日＝９９
　締期間から＋締期間月数の月－１ヶ月　の　最終日

締日≠９９
　締期間から＋締期間月数の月　の　締日</inlineHelpText>
        <label>請求締日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TsudoSeikyuFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>締請求から独立した請求集計を行う際にONされる。トリガによりONされる。
受注データの都度請求フラグONが集約される。</inlineHelpText>
        <label>都度請求フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N13_JuchuUrikakeRendoLogic.cls
public with sharing class N13_JuchuUrikakeRendoLogic {
    
    // コンストラクタ
    public N13_JuchuUrikakeRendoLogic(){
        // 何もしない。
    }
    
    //更新時に受注データを売掛データに紐付けし直す処理
    public void UpdateJuchuData(JuchuData__c oldObj, JuchuData__c newObj){

        // 新旧の受注確定フラグ、売掛データ照会日、都度請求フラグ、債権無フラグが異なる場合のみ処理実行
        if(oldObj.JuchuUriageKakuteiFlg__c != newObj.JuchuUriageKakuteiFlg__c || oldObj.SaikenMihasseiFlg__c != newObj.SaikenMihasseiFlg__c || oldObj.UrikakeDataShokaibi__c != newObj.UrikakeDataShokaibi__c || oldObj.TsudoSeikyuFlg__c != newObj.TsudoSeikyuFlg__c){

            // 更新した受注データが現在紐付いている売掛データ
            UrikakeData__c nowUrikake = [SELECT id, SeikyuAccount__c, TsudoSeikyuFlg__c, SaikenMihasseiFlg__c FROM UrikakeData__c WHERE id = :newObj.UrikakeData__c LIMIT 1];

            // 更新した受注データが紐付くべき売掛データ
            List<UrikakeData__c> parentUrikake = new List<UrikakeData__c>();
            
            // 受注データの関連先の売掛データを売掛データ照会日、都度請求フラグ、債権無フラグを元に検索
            parentUrikake = [SELECT Id FROM UrikakeData__c WHERE SeikyuAccount__c = :nowUrikake.SeikyuAccount__c AND ShimeKikanKara__c <= :newObj.UrikakeDataShokaibi__c AND ShimeKikanMade__c >= :newObj.UrikakeDataShokaibi__c AND TsudoSeikyuFlg__c = :newObj.TsudoSeikyuFlg__c AND SaikenMihasseiFlg__c = :newObj.SaikenMihasseiFlg__c LIMIT 1];

            // 売掛データが見つからなければ作成
            if(parentUrikake.isEmpty()){
                parentUrikake.add(new UrikakeData__c(name = 'XXXX', SeikyuAccount__c = nowUrikake.SeikyuAccount__c, ShimeHizuke__c = newObj.UrikakeDataShokaibi__c, TsudoSeikyuFlg__c = newObj.TsudoSeikyuFlg__c, SaikenMihasseiFlg__c = newObj.SaikenMihasseiFlg__c ));
                insert parentUrikake;
            }
 
            // 売掛データに受注データを紐付け
            newObj.UrikakeData__c = parentUrikake[0].id;

        }
    }

}