src/objects/KeshikomiData__c.object
<CustomObject>
    <fields>
        <fullName>NyukinChosei__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>請求調整</label>
        <referenceTo>NyukinChoseiM__c</referenceTo>
        <relationshipLabel>消込値引データ</relationshipLabel>
        <relationshipName>NyukinData_NyukinChosei</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UrikakeData__c</fullName>
        <label>請求集計データ</label>
        <referenceTo>UrikakeData__c</referenceTo>
        <relationshipLabel>消込値引データ</relationshipLabel>
        <relationshipName>NyukinData_UrikakeData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消込値引データ</label>
    <nameField>
        <label>消込値引名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NyukinChoseiM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>NyukinChoseiM_Account</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>請求調整マスタ</label>
    <nameField>
        <displayFormat>請求調整-{0000000000}</displayFormat>
        <label>請求調整番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N08_ChoseiIkkatsuHaneiLogic.cls
public with sharing class N08_ChoseiIkkatsuHaneiLogic {

    // コンストラクタ
    public N08_ChoseiIkkatsuHaneiLogic(){
        // 何もしない。
    }

    /**
     * 登録後処理
     */
    public void onAfterInsert(UrikakeData__c[] urikakeObjs){
        
        List<KeshikomiData__c> keshikomiDatas = new List<KeshikomiData__c>();

        Set<Id> SeikyuAccounIds = new Set<Id>();
        for (UrikakeData__c urikak :urikakeObjs){
            SeikyuAccounIds.add(urikak.SeikyuAccount__c);
        }
        
        List<NyukinChoseiM__c> nyukinMSTs = new List<NyukinChoseiM__c>();
        nyukinMSTs = [SELECT Id,Account__c FROM NyukinChoseiM__c WHERE Account__c IN :SeikyuAccounIds];

        for(UrikakeData__c  urikakeObj :urikakeObjs) {

            for (NyukinChoseiM__c nyukinMST :nyukinMSTs){

                if (nyukinMST.Account__c == urikakeObj.SeikyuAccount__c){

                    KeshikomiData__c keshikomi = new KeshikomiData__c();
                    keshikomi.NyukinChosei__c = nyukinMST.Id;
                    keshikomi.UrikakeData__c = urikakeObj.Id;
                    keshikomiDatas.add(keshikomi);
                    
                }
                
            }
                                    
        }
        
        //配列が空の場合を考慮
        if(!keshikomiDatas.isEmpty()){
            //配列をインサート
            insert keshikomiDatas;
        }
    }

    public void onAfterUpdate(UrikakeData__c[] urikakeObjs){

		// 抽出用のIDの一覧作成
        Set<String> urikakeDataIDs = new Set<String>();
        for(UrikakeData__c  urikakeObj :urikakeObjs) {
            urikakeDataIDs.add(urikakeObj.Id);
        }

        //更新対象の入金データ一覧を取得
        List<KeshikomiData__c> keshikomiDataExist = [SELECT Id, UrikakeData__c FROM KeshikomiData__c WHERE UrikakeData__c = :urikakeDataIDs];
        
        //配列が空の場合を考慮
        if(!keshikomiDataExist.isEmpty()){
            //配列更新
            update keshikomiDataExist;
        }
        
        
    }

}