src/objects/KeshikomiData__c.object
<CustomObject>
    <fields>
        <fullName>KeshikomiKingaku__c</fullName>
        <label>消込入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NyukinJutoFlg__c</fullName>
        <description>トリガ処理時の抽出条件として使用。</description>
        <formula>NyukinKeshikomiCounter__c  &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>入金消込リンクが作成されている場合ON。
不明入金データから充当されている場合ON。</inlineHelpText>
        <label>入金充当フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukinKeshikomiHantei__c</fullName>
        <formula>AND(

 ISBLANK( NyukinChosei__c ) ,
 KeshikomiKingaku__c  &gt; 0 ,
 SokuKeshikomi__c 

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>請求調整が空白
　かつ　消込入金額　が　￥１円以上を判定。
　かつ　自動消込チェック　が　ON。</inlineHelpText>
        <label>￥￥_入金消込リンク判定</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SeikyuSakiID__c</fullName>
        <formula>UrikakeData__r.SeikyuAccount__r.Id</formula>
        <inlineHelpText>トリガ処理用　請求先ID　の取得用</inlineHelpText>
        <label>￥￥_請求先ID</label>
        <type>Text</type>
    </fields>
    <label>消込値引データ</label>
    <nameField>
        <label>消込値引名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NyukinData__c.object
<CustomObject>
    <fields>
        <fullName>KeshikomiJutoZumiFlg__c</fullName>
        <formula>ZanKingaku__c &lt;= 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>残金額　が無くなった場合ON。
不明入金が請求消込に全て充当された場合ON。</inlineHelpText>
        <label>消込充当済フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukinBi__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>入金日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NyukinGaku__c</fullName>
        <label>入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SeikyuAccounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ZanKingaku__c</fullName>
        <formula>NyukinGaku__c  -  KeshikomiKingakuKei__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>入金額　－　消込入金額計　の残金</inlineHelpText>
        <label>残金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>入金データ</label>
    <nameField>
        <displayFormat>入金-{0000000000}</displayFormat>
        <label>入金データ名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NyukinKeshikomiLink__c.object
<CustomObject>
    <fields>
        <fullName>KeshikomiData__c</fullName>
        <label>消込値引データ</label>
        <referenceTo>KeshikomiData__c</referenceTo>
        <relationshipName>KeshikomiDatas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KeshikomiKingaku__c</fullName>
        <formula>KeshikomiData__r.KeshikomiKingaku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>￥￥_消込入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NyukinData__c</fullName>
        <label>入金データ</label>
        <referenceTo>NyukinData__c</referenceTo>
        <relationshipName>NyukinDatas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>入金充当リンク</label>
    <nameField>
        <displayFormat>入金充当-{0000000000}</displayFormat>
        <label>入金充当名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/N17_FumeiNyukinJutoLogic.cls
public class N17_FumeiNyukinJutoLogic {

    // コンストラクタ
    public N17_FumeiNyukinJutoLogic(){
        // 何もしない。
    }

    public void fumeiNyukinJuto(List<KeshikomiData__c> kekoList){

        //現在のガバナリミットSystem.limits.getLimitQueryRowsを取得する。
	    Integer limitQueryRows = System.limits.getLimitQueryRows();

        //不明入金データの検出結果用フラグ。
        Boolean foundNyukinData;

        //インサート用の入金消込リンク一覧を作成する。
		List<NyukinKeshikomiLink__c> insertNyKeLinkList = new List<NyukinKeshikomiLink__c>();

        //消込データの請求先IDの一覧を作成する。
		Set<ID> kekoAccIDSet = new Set<ID>();
		for(KeshikomiData__c keko : kekoList) {
			kekoAccIDSet.add(keko.SeikyuSakiID__c);
		}

        //取得した請求先に関連する不明入金データ(消込充当済フラグOFFで、入金額が少額で入金日が古いから）を取得する。
        List<NyukinData__c> nyukinDataList = new List<NyukinData__c>();
        nyukinDataList = [SELECT Id, ZanKingaku__c, KeshikomiJutoZumiFlg__c, SeikyuAccount__c, NyukinGaku__c, NyukinBi__c FROM NyukinData__c WHERE SeikyuAccount__c = :kekoAccIDSet AND KeshikomiJutoZumiFlg__c = FALSE ORDER BY NyukinGaku__c ASC, NyukinBi__c ASC LIMIT :limitQueryRows ];

        system.debug('*** nyukinDataList: ' + nyukinDataList);

        //消込データを順に処理する。
        for(KeshikomiData__c keko :kekoList){

            //不明入金データの検出結果の判定OFFにリセット。
            foundNyukinData = false;

            //入金消込リンク判定がONかつ入金充当フラグOFFの消込データのみ処理する。
            if(keko.NyukinKeshikomiHantei__c && !keko.NyukinJutoFlg__c){
                                
                //不明入金データを順に処理する。
                for(NyukinData__c nyukinData :nyukinDataList){

                    //消込データの消込入金額と請求先IDが一致する不明入金データの場合。
                    if(!foundNyukinData && nyukinData.SeikyuAccount__c == keko.SeikyuSakiID__c && nyukinData.ZanKingaku__c == keko.KeshikomiKingaku__c){
                        NyukinKeshikomiLink__c insertNyKeLink = new NyukinKeshikomiLink__c();
                        insertNyKeLink.KeshikomiData__c = keko.Id;
                        insertNyKeLink.NyukinData__c = nyukinData.Id;
                        insertNyKeLinkList.add(insertNyKeLink);
                        foundNyukinData = true;
                    }
                    //消込データの消込入金額以上で請求先IDが一致する不明入金データの場合。
                    if(!foundNyukinData && nyukinData.SeikyuAccount__c == keko.SeikyuSakiID__c && nyukinData.ZanKingaku__c >= keko.KeshikomiKingaku__c){
                        NyukinKeshikomiLink__c insertNyKeLink = new NyukinKeshikomiLink__c();
                        insertNyKeLink.KeshikomiData__c = keko.Id;
                        insertNyKeLink.NyukinData__c = nyukinData.Id;
                        insertNyKeLinkList.add(insertNyKeLink);
                        foundNyukinData = true;
                    }
                    
                }
                
            }
            
        }

        //検出された不明入金データに対応した入金消込リンクを作成する。
        insert insertNyKeLinkList;

    }

}