src/objects/NyukinChoseiM__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>NyukinChoseiM_Account</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>請求調整マスタ</label>
    <nameField>
        <displayFormat>請求調整-{0000000000}</displayFormat>
        <label>請求調整番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UrikakeData__c.object
<CustomObject>
    <fields>
        <fullName>SeikyuAccount__c</fullName>
        <label>請求取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UrikakeData_SeikyuAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>売掛データ</label>
    <nameField>
        <label>売掛名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UrikakeDataTriggerHandlerTest.cls
@isTest
private class UrikakeDataTriggerHandlerTest {
    
    static testMethod void myUnitTest1() {
        // 取引先作成
        List<Account> accList = new List<Account>();
        accList.add(new Account(name = '株式会社テスト20150217N08', Type = '請求先'));
        insert accList;

        // 入金調整マスタ作成
        List<NyukinChoseiM__c> nyukinMSTList = new List<NyukinChoseiM__c>();
        nyukinMSTList.add(new NyukinChoseiM__c(Account__c = accList[0].Id));
        insert nyukinMSTList;
        
        Test.startTest();
        // 売掛データ作成
        List<UrikakeData__c> urikakeList = new List<UrikakeData__c>();
        urikakeList.add(new UrikakeData__c(name = '売掛データテスト20150217N08', SeikyuAccount__c = accList[0].Id));
        insert urikakeList;
        
        Test.stopTest();
    }
}