src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>ShomiKigenNissu__c</fullName>
        <inlineHelpText>製品が製造完了後に正常に消費（使用)出来る期間。
例：食品であれば賞味期限など。
例：機械部品であれば保証期間など。</inlineHelpText>
        <label>消費期限日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>IdouTorikesiFlg__c</fullName>
        <formula>AND(
 NOT( ISBLANK( ZenZaikoData__c ) ) ,
 NOT( ISBLANK( ZenShukkoNichiji__c  ) ) ,
 ShukkoFlg__c ,
 ZenShukkoSuryo__c  &gt;= 1
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>トリガーの動作に必要。</inlineHelpText>
        <label>￥￥_移動取消フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>実在庫状態以降。オフの場合は予約データ（未入庫）となる。</description>
        <inlineHelpText>実際に入庫を確認したことを表す。オフの場合は確認未実施となる。</inlineHelpText>
        <label>入庫フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NyukoSuryo__c</fullName>
        <description>当在庫場所へ入庫した数量</description>
        <inlineHelpText>当在庫場所へ入庫した数量</inlineHelpText>
        <label>入庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigen__c</fullName>
        <label>消費期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShukkoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>実在庫状態以降。オフの場合は予約データ（未出庫）となる。</description>
        <inlineHelpText>実際に出庫を確認したことを表す。オフの場合は確認未実施となる。</inlineHelpText>
        <label>出庫フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZaikoSuryo__c</fullName>
        <label>在庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZenShukkoNichiji__c</fullName>
        <description>当在庫場所へ入庫するために、前在庫場所を出庫した日時</description>
        <inlineHelpText>当在庫場所へ入庫するために、前在庫場所を出庫した日時</inlineHelpText>
        <label>出庫日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ZenShukkoSuryo__c</fullName>
        <description>当在庫場所へ入庫するために、前在庫場所を出庫した数量</description>
        <inlineHelpText>当在庫場所へ入庫するために、前在庫場所を出庫した数量</inlineHelpText>
        <label>出庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZenZaikoData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>出庫元の入出庫データ</inlineHelpText>
        <label>親入出庫データ</label>
        <referenceTo>ZaikoData__c</referenceTo>
        <relationshipLabel>入出庫データ</relationshipLabel>
        <relationshipName>ZaikoData_ZenZaikoData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J49_ZaikoIdouTorikesiLogicTest.cls
@isTest
private class J49_ZaikoIdouTorikesiLogicTest {

    static testMethod void myUnitTest1() {
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 在庫データ作成
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, ShomiKigen__c = Date.newInstance(2016, 1, 1), NyukoFlg__c = true);
        insert zaiko1;
        ZaikoData__c zaiko2 = new ZaikoData__c(zenZaikoData__c = zaiko1.Id, NyukoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, ShomiKigen__c = Date.newInstance(2016, 1, 1), NyukoFlg__c = false);
        insert zaiko2;
        
        zaiko2.ZenShukkoNichiji__c = Date.today();
        zaiko2.ShukkoFlg__c = true;
        zaiko2.ZenShukkoSuryo__c = 1;
        update zaiko2;

        ZaikoData__c zaiko3 = new ZaikoData__c();
        zaiko3 = [SELECT Id, IdouTorikesiFlg__c, ZenZaikoData__c , ZenShukkoNichiji__c , ShukkoFlg__c, ZenShukkoSuryo__c FROM ZaikoData__c WHERE Id = :zaiko2.Id];
        
        Test.startTest();
        delete zaiko3;
        Test.stopTest();
    }
}