src/objects/ShohinShizaiM__c.object
<CustomObject>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Y06_UpdateZaikoDataBatchTest.cls
@isTest
private class Y06_UpdateZaikoDataBatchTest {

    static testMethod void myUnitTest1() {
        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1');
        shohinList.add(shohin1);
        insert shohinList;
        
        // 出荷見込みデータ作成
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        ZaikoData__c zaiko1 = new ZaikoData__c(ShohinShizaiM__c = shohin1.Id, name='テスト在庫データ1');
        zaikoList.add(zaiko1);
        insert zaikoList;
        
        Test.startTest();
        Database.executeBatch(new Y06_UpdateZaikoDataBatch());
        Test.stopTest();
    }
}