src/objects/ShohinShizaiM__c.object
<CustomObject>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShukaMikomiData__c.object
<CustomObject>
    <fields>
        <fullName>MotoHizuke__c</fullName>
        <inlineHelpText>出荷データの納品予定日をWFRをで反映。</inlineHelpText>
        <label>元日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材マスタ</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ShukaMikomiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消費見込データ</label>
    <nameField>
        <displayFormat>消費見込-{000000000}</displayFormat>
        <label>消費見込番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Y01_ZaikoKeppinKeikokuControllerTest.cls
@isTest
private class Y01_ZaikoKeppinKeikokuControllerTest {

    static testMethod void myUnitTest1() {
        // 商品資材作成
        List<ShohinShizaiM__c> shohinList = new List<ShohinShizaiM__c>();
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1');
        shohinList.add(shohin1);
        insert shohinList;
        
        // 出荷見込みデータ作成
        List<ShukaMikomiData__c> shukaList = new List<ShukaMikomiData__c>();
        ShukaMikomiData__c shuka1 = new ShukaMikomiData__c(ShohinShizaiM__c = shohin1.Id, MotoHizuke__c = Date.today());
        shukaList.add(shuka1);
        insert shukaList;
        
        // 在庫データ作成
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        ZaikoData__c zaiko1 = new ZaikoData__c(ShohinShizaiM__c = shohin1.Id, name='テスト在庫データ1');
        zaikoList.add(zaiko1);
        insert zaikoList;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('shohinId', shohin1.Id);
        Y01_ZaikoKeppinKeikokuController controller = new Y01_ZaikoKeppinKeikokuController();
        controller.init();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(DataBase.query('select id from ShohinShizaiM__c'));
        Y01_ZaikoKeppinKeikokuController extension = new Y01_ZaikoKeppinKeikokuController(sc);
    }
}