src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>YosokuTaishoSuryo__c</fullName>
        <formula>HyojunALLSuryo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>標準混ユニット数量</inlineHelpText>
        <label>予測対象在庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShukaMikomiData__c.object
<CustomObject>
    <fields>
        <fullName>Hizuke__c</fullName>
        <description>元日付　≧　本日　＝　元日付	
元日付　＜　本日　＝　元日付　＋　実績反映年数　×　３５６
元日付　＜　本日　＝　元日付　＋　実績反映月数　×　３０
元日付　＜　本日　＝　元日付　＋　実績反映日数</description>
        <formula>IF (  MotoHizuke__c  &lt;  TODAY() ,
 MotoHizuke__c  + 
 ShohinShizaiM__r.JissekiHaneiNissu__c +
 ShohinShizaiM__r.JissekiHaneiTsukisu__c * 30 +
 ShohinShizaiM__r.JissekiHaneiNensu__c * 365
 ,
 MotoHizuke__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>元日付が到来前
　→　元日付（出荷予定日など）として、仮出荷引当参考値などとする。

元日付の到来後
　→　商品資材マスタの実績反映日数/月数/年数を加算し消費予測値とする。</inlineHelpText>
        <label>消費予測日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材マスタ</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ShukaMikomiData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>消費見込データ</label>
    <nameField>
        <displayFormat>消費見込-{000000000}</displayFormat>
        <label>消費見込番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>YosokuTaishoSuryo__c</fullName>
        <formula>IF (  YoteiZaikoFlg__c  , 
 NyukoSuryo__c , 
IF ( HikiateMachiFlg__c ,
 ZaikoSuryo__c ,
 0
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>予測対象数量（予定込）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Y01_ZaikoKeppinKeikokuController.cls
public with sharing class Y01_ZaikoKeppinKeikokuController {
    public Y01_ZaikoKeppinKeikokuController(){
    }
    
    public Y01_ZaikoKeppinKeikokuController(ApexPages.StandardController controller){
    }
    
    public pageReference init(){
        // URLより商品資材のID取得
        String shohinId = ApexPages.CurrentPage().getParameters().get('ShohinId');
        
        // SOQLの制限を設定。念の為半分の数よりマイナス1しておく
        Integer limitNum = (Limits.getLimitQueryRows() / 2) -1;

        // 出荷見込更新
        List<ShukaMikomiData__c> shukaList = new List<ShukaMikomiData__c>();
        shukaList = [SELECT Id FROM ShukaMikomiData__c WHERE ShohinShizaiM__c = :shohinId ORDER BY Hizuke__c LIMIT :limitNum];
        update shukaList;
        
        // 在庫データ更新
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        zaikoList = [SELECT Id FROM ZaikoData__c WHERE ShohinShizaiM__c = :shohinId ORDER BY YosokuTaishoSuryo__c DESC  LIMIT :limitNum];
        update zaikoList;
        
        return new PageReference('/' + shohinId);
    }
}