src/objects/ShohinShizaiM__c.object
<CustomObject>
    <fields>
        <fullName>ShomiKigenNissu__c</fullName>
        <inlineHelpText>製品が製造完了後に正常に消費（使用)出来る期間。
例：食品であれば賞味期限など。
例：機械部品であれば保証期間など。</inlineHelpText>
        <label>消費期限日数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品資材マスタ</label>
    <nameField>
        <label>商品資材名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>NyukoFlg__c</fullName>
        <defaultValue>false</defaultValue>
        <description>実在庫状態以降。オフの場合は予約データ（未入庫）となる。</description>
        <inlineHelpText>実際に入庫を確認したことを表す。オフの場合は確認未実施となる。</inlineHelpText>
        <label>入庫フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShohinShizaiM__c</fullName>
        <label>商品資材</label>
        <referenceTo>ShohinShizaiM__c</referenceTo>
        <relationshipName>ZaikoData_ShohinShizaiM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ShomiKigen__c</fullName>
        <label>消費期限</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ZaikoSuryo__c</fullName>
        <label>在庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zaikobasho__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>場所</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>入出庫データ</relationshipLabel>
        <relationshipName>ZaikoData_Zaikobasho</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZenShukkoNichiji__c</fullName>
        <description>当在庫場所へ入庫するために、前在庫場所を出庫した日時</description>
        <inlineHelpText>当在庫場所へ入庫するために、前在庫場所を出庫した日時</inlineHelpText>
        <label>出庫日時</label>
        <type>DateTime</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Z04_ZaikoidouTourokuControllerExtensTest.cls
@isTest
private class Z04_ZaikoidouTourokuControllerExtensTest {

    static testMethod void myUnitTest1() {

        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = 'テスト倉庫');
        Account acc2 = new Account(name = 'テスト移動先');
        insert acc1;
        insert acc2;

        // 在庫データ作成
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc1.Id, ShomiKigen__c = Date.newInstance(2016, 1, 1), NyukoFlg__c = true);
        zaikoList.add(zaiko1);
        insert zaikoList;

        // 空在庫データ作成
        List<ZaikoData__c> nullZaikoList = new List<ZaikoData__c>();


        Test.startTest();

        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ZaikoData__c'));
        Z04_ZaikoidouTourokuControllerExtension extension = new Z04_ZaikoidouTourokuControllerExtension(ssc);
        ApexPages.currentPage().getParameters().put('retUrl', 'XXX');

        // 選択するレコード無
        ssc.setSelected(nullZaikoList);
        extension = new Z04_ZaikoidouTourokuControllerExtension(ssc);
        extension.init();

        // 選択するレコードを設定
        ssc.setSelected(zaikoList);
        extension = new Z04_ZaikoidouTourokuControllerExtension(ssc);
        extension.init();

        // 正常：クリアボタン押下
        extension.clearButton();

        // エラー：各種値が未入力
        extension.jikkouButton();
        
        // エラー：在庫数量 < 移動数量
        extension.targetDispZaikoList[0].idouSuryo = 100;
        extension.jikkouButton();

        // 正常：キャンセルボタン押下
        extension.cancelButton();
        
        // 正常：移動が実行される
        extension.targetDispZaikoList[0].idouSuryo = 1;
        extension.targetDispZaikoList[0].newZaiko.ZenShukkoNichiji__c = date.today();
        extension.targetDispZaikoList[0].newZaiko.Zaikobasho__c = acc2.Id;
        extension.jikkouButton();
        
        Test.stopTest();
       
    }
    
    // 移動場所（一括）を使用したパターン
    static testMethod void myUnitTest2() {
        
        // 商品資材作成
        ShohinShizaiM__c shohin1 = new ShohinShizaiM__c(name = 'テスト商品1', ShomiKigenNissu__c = 100);
        insert shohin1;
        
        // 取引先作成
        Account acc1 = new Account(name = 'テスト倉庫');
        Account acc2 = new Account(name = 'テスト移動先');
        insert acc1;
        insert acc2;

        // 在庫データ作成
        List<ZaikoData__c> zaikoList = new List<ZaikoData__c>();
        ZaikoData__c zaiko1 = new ZaikoData__c(ZaikoSuryo__c = 10, name = 'a', ShohinShizaiM__c = shohin1.Id, Zaikobasho__c = acc1.Id, ShomiKigen__c = Date.newInstance(2016, 1, 1), NyukoFlg__c = true);
        zaikoList.add(zaiko1);
        insert zaikoList;
                

        Test.startTest();

        // 画面起動
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(DataBase.query('select id from ZaikoData__c'));
        Z04_ZaikoidouTourokuControllerExtension extension = new Z04_ZaikoidouTourokuControllerExtension(ssc);

        // 選択するレコードを設定
        ssc.setSelected(zaikoList);
        extension = new Z04_ZaikoidouTourokuControllerExtension(ssc);
        extension.init();

        // 正常：クリアボタン押下
        extension.clearButton();
        
        // 正常：移動が実行される
        extension.allMove = TRUE;
        extension.allSelect.ZenShukkoNichiji__c = date.today();
        extension.allSelect.Zaikobasho__c = acc2.Id;
        extension.jikkouButton();
        
        Test.stopTest();
       
    }
}