src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>IdouTorikesiFlg__c</fullName>
        <formula>AND(
 NOT( ISBLANK( ZenZaikoData__c ) ) ,
 NOT( ISBLANK( ZenShukkoNichiji__c  ) ) ,
 ShukkoFlg__c ,
 ZenShukkoSuryo__c  &gt;= 1
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>トリガーの動作に必要。</inlineHelpText>
        <label>￥￥_移動取消フラグ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZaikoSuryo__c</fullName>
        <label>在庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZenShukkoSuryo__c</fullName>
        <description>当在庫場所へ入庫するために、前在庫場所を出庫した数量</description>
        <inlineHelpText>当在庫場所へ入庫するために、前在庫場所を出庫した数量</inlineHelpText>
        <label>出庫数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZenZaikoData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>出庫元の入出庫データ</inlineHelpText>
        <label>親入出庫データ</label>
        <referenceTo>ZaikoData__c</referenceTo>
        <relationshipLabel>入出庫データ</relationshipLabel>
        <relationshipName>ZaikoData_ZenZaikoData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J49_ZaikoIdouTorikesiLogic.cls
public with sharing class J49_ZaikoIdouTorikesiLogic {

    // コンストラクタ
    public J49_ZaikoIdouTorikesiLogic(){
        // 何もしない。
    }
    
    /**
     * 在庫データの削除時に親在庫に数量を戻す処理
     */
    public void henkyakuZaikoSuryo(ZaikoData__c[] oldObjs){
        List<Id> zenZaikoIdList = new List<Id>();
        
        // 前在庫データのIdのリストを作成
        for(ZaikoData__c zaikoItem :oldObjs){
            // 移動取消フラグがtrue
            if(zaikoItem.IdouTorikesiFlg__c){
                zenZaikoIdList.add(zaikoItem.ZenZaikoData__c);
            }
        }
        
        // 親在庫データのリストを作成
        List<ZaikoData__c> zenZaikoList = new List<ZaikoData__c>();
        zenZaikoList = [SELECT Id, zaikoSuryo__c FROM ZaikoData__c WHERE Id IN :zenZaikoIdList];
        
    
        // アップデート対象リスト
        List<ZaikoData__c> updZaikoDataList = new List<ZaikoData__c>();
        
        // 在庫データ削除時に入庫数量を親在庫データの在庫数に足す処理開始
        for(ZaikoData__c zaikoItem :oldObjs){
            // 移動取消フラグが
            if(zaikoItem.IdouTorikesiFlg__c){
                // 親在庫データのリストを回して対象の物を探す
                for(ZaikoData__c zenItem :zenZaikoList){
                    if(zaikoItem.ZenZaikoData__c == zenItem.Id){
                        // 対象の親在庫データの在庫数量に前出庫数量を足し込む（値が格納されていた場合のみ）
                        if(zenItem.ZaikoSuryo__c >= 0 && zaikoItem.ZenShukkoSuryo__c >= 0){
                        zenItem.ZaikoSuryo__c = zenItem.ZaikoSuryo__c + zaikoItem.ZenShukkoSuryo__c;
                        updZaikoDataList.add(zenItem);                            
                        }
                    }
                }
            }
        }
        
        if(!updZaikoDataList.isEmpty()){
            update updZaikoDataList;
        }
    }
}