src/objects/ZaikoData__c.object
<CustomObject>
    <fields>
        <fullName>JuchuMeisai__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>受注明細</label>
        <referenceTo>JuchuMeisaiData__c</referenceTo>
        <relationshipName>ZaikoData_JuchuMeisai</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>入出庫データ</label>
    <nameField>
        <label>入出庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/J48_JyutyuMeisaiSakujyoZaikoLogic.cls
public with sharing class J48_JyutyuMeisaiSakujyoZaikoLogic {

    // コンストラクタ
    public J48_JyutyuMeisaiSakujyoZaikoLogic(){
        // 何もしない。
    }

    public void deleteZaikoData (Set<Id> meisaiIdSet){

        // 削除対象の在庫データのリスト
        List<ZaikoData__c> deleteZaikoDataList = new List<ZaikoData__c>();
        deleteZaikoDataList = [SELECT Id, JuchuMeisai__c FROM ZaikoData__c WHERE JuchuMeisai__c IN :meisaiIdSet];
        
        if(!deleteZaikoDataList.isEmpty()){
            delete deleteZaikoDataList;

        }
    }
}